{
  "Success": true,
  "Error": "",
  "Data": {
    "SC": "-- [r4stl1n] RSING Indicator\n-- \n-- This is a implementation of the RSING indicator purposed by Alon Horesh\n--\n-- This indicator measures price momentum strength by taking the following into account\n--\n-- 1. A focus on strength only; The Value of the indiactor \n--    reflects the strength of the price momentum\n--\n-- 2. A positive high value reflects stronger price momentum to the upside\n--    Negative values reflect strong downward price movement.\n--    Prices close to zero reflect no momentum in current price action\n--\n-- 3. Volume is an important part of the calculations supporting the\n--    the price momentum.\n--------------------------------\n-- You are on your own with this script\n-------------------------------- \n-- ~Bored and programming~\n    \n-- Define command\nDefineCommand('RSING', 'RSING')\n \nlocal rsingLength = DefineParameter(NumberType, 'rsingLength', 'RSING length', false, 20, 'Number,InputShortLength')\n \nlocal wma = WMA(GetVolume(),rsingLength)\nlocal range = HighPrices()-LowPrices()\nlocal std = STDDEV(range,rsingLength,1)\n \nlocal vwr = GetVolume() / wma\nlocal blr = range / std\nlocal irr = MOM(ClosePrices(),rsingLength)\n \nlocal rsing = WMA(vwr * blr * irr,rsingLength)\n \nDefineOutput(NumberType, rsing, 'RSING', 'TradeBotContainer, IndicatorContainer, Signal Helpers')",
    "CR": {
      "IV": true,
      "C": {
        "CN": "RSING",
        "CD": "RSING",
        "MC": false,
        "US": false,
        "UL": false,
        "OH": false,
        "P": [
          {
            "Index": 0,
            "Name": "rsingLength",
            "Type": 1,
            "IsRequired": false,
            "IsHidden": false,
            "IsField": false,
            "AllowNull": true,
            "Description": "RSING length",
            "ScriptType": null,
            "Suggestion": [
              4403
            ]
          }
        ],
        "O": {
          "Index": 0,
          "Name": "result",
          "Type": 1,
          "IsRequired": false,
          "IsHidden": false,
          "IsField": false,
          "AllowNull": false,
          "Description": "RSING",
          "ScriptType": null,
          "Suggestion": [
            7003,
            7000,
            6019,
            6012,
            6013,
            6000,
            6001,
            6002,
            6003,
            6004,
            6011,
            6005,
            6006,
            6022,
            6014,
            8303,
            6007,
            6021,
            6008,
            6009,
            6016,
            6017,
            6018,
            6020,
            6015,
            6010
          ]
        },
        "OI": []
      },
      "CR": [],
      "CL": [
        "1754459740 ||| 0 ||| Compiling script...",
        "1754459740 ||| 0 ||| TIP: You might want to draw a chart combined with your strategy. You can do this by using one of the command in the Charting category.",
        "1754459740 ||| 0 ||| TIP: Using OptimizedForInterval() in combination with the technical analysis commands will improve the backtest speed.",
        "1754459740 ||| 0 ||| Field rsingLength found.",
        "1754459740 ||| 0 ||| DefineParameter(): Input parameter suggestion added: Number",
        "1754459740 ||| 0 ||| Output found. Type: Number. Result: (UserData)",
        "1754459740 ||| 0 ||| DefineOutput(): Output suggestion added: TradeBotContainer",
        "1754459740 ||| 0 ||| DefineOutput(): Output suggestion added: IndicatorContainer",
        "1754459740 ||| 0 ||| DefineOutput(): Output suggestion added: BoolToSignal",
        "1754459740 ||| 0 ||| DefineOutput(): Output suggestion added: ConvertSignal",
        "1754459740 ||| 0 ||| DefineOutput(): Output suggestion added: DelaySignal",
        "1754459740 ||| 0 ||| DefineOutput(): Output suggestion added: GetAboveBelowSignal",
        "1754459740 ||| 0 ||| DefineOutput(): Output suggestion added: GetBuySellLevelSignal",
        "1754459740 ||| 0 ||| DefineOutput(): Output suggestion added: GetConsensusSignal",
        "1754459740 ||| 0 ||| DefineOutput(): Output suggestion added: GetCrossOverUnderSignal",
        "1754459740 ||| 0 ||| DefineOutput(): Output suggestion added: GetRemoteSignal",
        "1754459740 ||| 0 ||| DefineOutput(): Output suggestion added: GetSuperSignal",
        "1754459740 ||| 0 ||| DefineOutput(): Output suggestion added: GetThresholdSignal",
        "1754459740 ||| 0 ||| DefineOutput(): Output suggestion added: GetUnanimousSignal",
        "1754459740 ||| 0 ||| DefineOutput(): Output suggestion added: GetWebHookSignal",
        "1754459740 ||| 0 ||| DefineOutput(): Output suggestion added: GetWeightedConsensusSignal",
        "1754459740 ||| 0 ||| DefineOutput(): Output suggestion added: HindSightSignal",
        "1754459740 ||| 0 ||| DefineOutput(): Output suggestion added: IgnoreSignalIf",
        "1754459740 ||| 0 ||| DefineOutput(): Output suggestion added: PositionToBool",
        "1754459740 ||| 0 ||| DefineOutput(): Output suggestion added: ReverseSignal",
        "1754459740 ||| 0 ||| DefineOutput(): Output suggestion added: SaveRemoteSignal",
        "1754459740 ||| 0 ||| DefineOutput(): Output suggestion added: SignalMapper",
        "1754459740 ||| 0 ||| DefineOutput(): Output suggestion added: SignalProperties",
        "1754459740 ||| 0 ||| DefineOutput(): Output suggestion added: SignalToBool",
        "1754459740 ||| 0 ||| DefineOutput(): Output suggestion added: SignalToLog",
        "1754459740 ||| 0 ||| DefineOutput(): Output suggestion added: SignalWeight",
        "1754459740 ||| 0 ||| DefineOutput(): Output suggestion added: UseSignalIf",
        "1754459740 ||| 0 ||| Compile test OK."
      ],
      "LCE": [],
      "VCE": [],
      "I": [],
      "O": 500,
      "HT": false,
      "HO": false,
      "SS": false,
      "MS": false,
      "LS": false,
      "MT": false,
      "OD": false,
      "MM": false,
      "RSB": false,
      "TAU": false
    },
    "UID": "02f3cd9afebb46bf9d4c9b6ef5e6e823",
    "SID": "06415811f5454c2d838c34f0df29da76",
    "SN": "RSING Momentum Indicator ",
    "SD": "",
    "ST": 0,
    "SS": 0,
    "CN": "RSING",
    "IC": true,
    "IV": true,
    "CU": 1754459725,
    "UU": 1754459741,
    "FID": -1
  }
}
