{
  "Success": true,
  "Error": "",
  "Data": {
    "SC": "-- [huluvublue]\n-- SMIbot0.6.2\n-- bc1pmygwepesljqk87ccvnvglv07ak5t80xw9ffxaq9ah20vjtvt5vcq9kpa5z\n\nfunction SMIErgodicOscillator(shortPeriod, longPeriod, signalPeriod, maType, source)\n    local tsi = TSI(source, shortPeriod, longPeriod)\n    local signal = MA(tsi, signalPeriod, maType) \n    return tsi, signal\nend\n\n-- Inputs\nlocal shortPeriod = Input('Short Period', 5, '')\nlocal longPeriod = Input('Long Period', 20, '')\nlocal signalPeriod = Input('Signal Period', 5, '')\nlocal maType = InputMaTypes('Moving Average Type', EmaType, '') \nlocal allowLongs = Input('Allow Long Positions', true, 'bool')\nlocal allowShorts = Input('Allow Short Positions', true, 'bool')\nlocal prices = ClosePrices()\n\n-- Get the SMI Ergodic Oscillator and Signal line\nlocal oscillator, signalLine = SMIErgodicOscillator(shortPeriod, longPeriod, signalPeriod, maType, prices)\n\n-- Plot the indicator\nPlot(1, 'Oscillator', oscillator, 'fuchsia')\nPlot(1, 'Signal Line', signalLine, 'orange')\n\n-- Plot the histogram\nlocal histogram = oscillator - signalLine\nlocal histoPlot = Plot(1, \"Histogram\", histogram, Gray)\nPlotHistogram(histoPlot, Maroon, true)  \n\n-- Trading Logic\nlocal currentPosition = GetPositionDirection()\n\nif CrossOver(oscillator, signalLine) then\n    -- Buy when oscillator crosses above the signal line\n    if currentPosition ~= PositionLong and allowLongs then\n        DoBuy('Go long')\n    elseif currentPosition == PositionShort then\n        DoExitPosition('Exit short position')\n    end\nelseif CrossUnder(oscillator, signalLine) then\n    -- Go short when oscillator crosses below the signal line\n    if currentPosition ~= PositionShort and allowShorts then\n        DoShort('Go short')\n    elseif currentPosition == PositionLong then\n        DoExitPosition('Exit long position')\n    end\nend\n\nlocal profit = GetBotProfit()\nPlot(2, \"PnL\", profit, 'green')\nPlot(2, \"\", 0, 'white')\n\n",
    "CR": {
      "IV": true,
      "C": null,
      "CR": [],
      "CL": [
        "1752256770 ||| 0 ||| Compiling script...",
        "1752256770 ||| 0 ||| TIP: Using OptimizedForInterval() in combination with the technical analysis commands will improve the backtest speed.",
        "1752256770 ||| 0 ||| Registered input 'Short Period'",
        "1752256770 ||| 0 ||| Registered input 'Long Period'",
        "1752256770 ||| 0 ||| Registered input 'Signal Period'",
        "1752256770 ||| 0 ||| Registered input 'Moving Average Type'",
        "1752256770 ||| 0 ||| Registered input 'Allow Long Positions'",
        "1752256770 ||| 0 ||| Registered input 'Allow Short Positions'",
        "1752256770 ||| 0 ||| Compile test OK."
      ],
      "LCE": [],
      "VCE": [],
      "I": [
        {
          "T": 0,
          "ST": -1,
          "G": "",
          "K": "12-12-20-25.Short Period",
          "EK": "12-12-20-25",
          "N": "Short Period",
          "TT": "",
          "V": "5",
          "D": "5",
          "O": null,
          "MIN": 0.0,
          "MAX": 0.0
        },
        {
          "T": 0,
          "ST": -1,
          "G": "",
          "K": "13-13-19-24.Long Period",
          "EK": "13-13-19-24",
          "N": "Long Period",
          "TT": "",
          "V": "20",
          "D": "20",
          "O": null,
          "MIN": 0.0,
          "MAX": 0.0
        },
        {
          "T": 0,
          "ST": -1,
          "G": "",
          "K": "14-14-21-26.Signal Period",
          "EK": "14-14-21-26",
          "N": "Signal Period",
          "TT": "",
          "V": "5",
          "D": "5",
          "O": null,
          "MIN": 0.0,
          "MAX": 0.0
        },
        {
          "T": 3,
          "ST": -1,
          "G": "",
          "K": "15-15-15-27.Moving Average Type",
          "EK": "15-15-15-27",
          "N": "Moving Average Type",
          "TT": "",
          "V": "Ema",
          "D": "Ema",
          "O": {
            "Sma": "Sma",
            "Ema": "Ema",
            "Wma": "Wma",
            "Dema": "Dema",
            "Tema": "Tema",
            "Trima": "Trima",
            "Kama": "Kama",
            "Mama": "Mama",
            "T3": "T3"
          },
          "MIN": 0.0,
          "MAX": 0.0
        },
        {
          "T": 2,
          "ST": -1,
          "G": "",
          "K": "16-16-19-24.Allow Long Positions",
          "EK": "16-16-19-24",
          "N": "Allow Long Positions",
          "TT": "bool",
          "V": "True",
          "D": "True",
          "O": null,
          "MIN": 0.0,
          "MAX": 0.0
        },
        {
          "T": 2,
          "ST": -1,
          "G": "",
          "K": "17-17-20-25.Allow Short Positions",
          "EK": "17-17-20-25",
          "N": "Allow Short Positions",
          "TT": "bool",
          "V": "True",
          "D": "True",
          "O": null,
          "MIN": 0.0,
          "MAX": 0.0
        }
      ],
      "O": 500,
      "HT": false,
      "HO": false,
      "SS": true,
      "MS": true,
      "LS": true,
      "MT": true,
      "OD": false,
      "MM": false,
      "RSB": false,
      "TAU": false
    },
    "UID": "02f3cd9afebb46bf9d4c9b6ef5e6e823",
    "SID": "22dd22b7bb93438b860422ba38775e8d",
    "SN": "SMIbot_0.6.2-orig",
    "SD": "",
    "ST": 0,
    "SS": 0,
    "CN": "",
    "IC": false,
    "IV": true,
    "CU": 1752256762,
    "UU": 1752256771,
    "FID": -1
  }
}
