{
  "Success": true,
  "Error": "",
  "Data": {
    "SC": "Log('Tip wallet ERC20: 0xaa28dE4372CA0a8BC36722886E9749f70DF32382')\nEnableHighSpeedUpdates(true)\nHideOrderSettings()\nHideTradeAmountSettings()\n \n-- Always start with ALL Trade Settings options UN-TICKED to let the bot preparing values.\n-- Test with default values before changing anything to understand the bot.\n-- PAY ATTENTION to the log warning if you feel something is off before screeaming the bot is not working.\n \n-- inputs\n    InputGroupHeader('Super Trend Setting')  \n        local short_lookback = Input('01A. Short Period', 8, '')\n        local short_atr = Input('02. Short ATR', 3, '')\n        local long_lookback = Input('01. Long Period', 21, '')\n        local long_atr = Input('02. Long ATR', 8, '')\n \n    InputGroupHeader('Trade Settings')\n        local okLong = Input('01A. Long Entry', false, 'Allow bot to open Long')\n        local okProfitL = Input('01B. Long Exit', false, 'Allow bot to exit Long')\n        local okShort = Input('02A. Short Entry', false, 'Allow bot to open Short')\n        local okProfitS = Input('02B. Short Exit', false, 'Allow bot to exit Short')\n        local okReduce = Input('03. BalRatio Reduction', false, 'Allow Bal Ratio based size reduction')\n        local okDerisk = Input('04. Risk Reduction', false, 'Allow Signal based size reduction')\n        local oneWay = Input('05. Not Hedge', false, 'Selec this if the market is NOT HEDGE mode')\n        local onlyWeekdays = Input('06. Only Weekdays', false, 'Bot will close any position and not trading during weekend')\n \n    InputGroupHeader('Bot Settings')\n        local wtfStop = Input('01. Stop at no position', false, 'Deactivate bot when there is no open position.')\n        local clearSlot = Input('02. Recalculate Slot Size', false, 'If activated will ALWAYS calculating slot size. If not activatated slot size will only calculated when there is no open position.')\n        local FOL = Input('03. Force Open Long', false, 'Force open LONG position')\n        local FEL = Input('04. Force Exit Long', false, 'Force exit LONG position')\n        local FOS = Input('05. Force Open Short', false, 'Force open SHORT position')\n        local FES = Input('06. Force Exit Short', false, 'Force exit SHORT position')\n        local wtfLoss = Input('07. Pause at % LOSS', 0, 'Pause trading until next day UTC when LOSS % below this. 0 is disalbe.')\n        local wtfProfit = Input('08. Pause at % PROFIT', 0, 'Pause trading until next day UTC when PROFIT % above this. 0 is disable.')\n                                                                            \n    InputGroupHeader('Backtest Settings')\n        local wtfBal = Input('01. Deactivate on Over Budget', false, 'ONLY FOR BACKTEST. Disable bot when Bal. Ratio hit trigger')\n    \n    InputGroupHeader('Custom Wallet')\n        local testWallet = Input('01. Activate Custom Wallet', false, 'Use custom wallet amount. A must in Haaslab')\n        local testBal = Input('02. Custom Wallet Balance', 0, 'Amount of custom wallet')\n    \n    InputGroupHeader('Budget')\n        local startBal = Input('01. Starting Balance ', 0, 'Starting trading balance which also maximum COST to limit working balance (margin cost + unrealised loss)')\n        local stopAtprofit = Input('02. Profit Limit %', 0, 'Deactivate bot when bot gaining this % amount from the starting balance')\n        local stopAtloss = Input('03. Loss Limit %', 0, 'Deactivate bot when bot losing this % amount from the highest balance recorded')\n        local leverage = Input('04. Leverage', 50, 'MUST be filled and same as in exchange setting. Important for trading budget')\n        local contVal = Input('05. Inverse Contract Value', 10, 'ONLY if bot trading on INVERSE Futures then enter the Contract Value. Ignore if not') \n        \n    InputGroupHeader('Safety')\n        local slTrigger = Input('01.Fix SL %', 0, '0 is disable, else DISREGARDING RISK REDUCTION option and signal bot will derisking when % price change againts average entry.')\n        local slDistance = Input('02. Min. Dynamic SL %', 1, 'Signal based min % price distance from 1st entry to calculate stop loss price.')\n        local reduceTrigger = Input('03. Bal Ratio Trigger', 0.8, 'Ratio between working balance and trading balance to trigger size reduction')\n        local reduceSize = Input('04. Size Reduction %', 100, 'SHOULD BE factors of 100. In risk reduction: 1st reduction 25%, 2nd reduction 50% and so on. In balance ratio reduction: balRatio > Bal. Ratio Trigger then fixed 25% reduction')\n        local reduceOrderType = InputOrderType('05. Reduction Order Type', MakerOrCancelOrderType, 'The order type for size reduction')\n        local profitOut = Input('06. Profit Hodl %', 100, '% of the bot profit taken out or not compounded into trading balance calculation')\n        local dynamicHodl = Input('07. Dynamic Hodl', false, 'After in profit will only take out profit if current profit < 80% of highest profit recorded.')\n        local delay = Input('08. SL Delay (Min)', 0, 'Stop the bot from opening new long/short order for X minutes after close at loss.')\n \n    InputGroupHeader('Order')\n        local orderCount = Input('01. Orders Count', 1, 'How many total filled orders are allowed for DCA.')\n        local slotBudget = Input('02. Risk % per order', 1, '1 = risk losing ~1% of trading balance PER ORDER if SL hit from current order price. Total risk PER POSITION = order count * risk.') \n        local orderDistance = Input('02A. Fix Orders Distance %', 0, 'Minimum % price distance from filled order to the next.')\n        local dynamicDist = Input('02B. Dynamic Order Distance %', true, 'Auto calculate order distance. If ticked will ignore Order Distance value')\n        local slotSizeD = Input('03A. Min. Order Size ', 0, 'Minimum order size if Dynamic Slot Size activated. Static amount if Dynamic Slot Size disabled.')\n        local autoSlot = Input('03B. Dynamic Order Size', true, 'Dynamically change order size. Calculated based on distance to SL price.')\n        \n    InputGroupHeader('Profit')\n        local RR = Input('01. Reward to Risk', 3, 'Reward to risk ratio. 2 = reward 2x risk. At this level bot will close position.')\n        local halvingAt = Input('02. Halving %', 0, '% of profit price change to start halving size at doubling rate. 0 is disable. If 1 = 1st at 1%, 2nd when 2% and so on.')\n        local tpOrderType = InputOrderType('03. TP Order Type', MakerOrCancelOrderType, 'The order type for take-profit')\n \n---------------------\n-- DATA\n    local getMarket = PriceMarket()\n    local getAccount = AccountGuid()\n    local cp = CurrentPrice(getMarket)\n    local ct = Time()\n    local cd = CurrentDate()\n    local prevDate = Load('prevDate', cd - 1)\n    local today = CurrentDay()\n    local mainInterval = CurrentInterval()\n \n    -- counters \n        local highestP = Load('highestP', 0)\n        local lowestP = Load('lowestP', 0)\n        local SRCounter = Load('SRCounter', 0)\n \n    -- Indicators\n        local o, h, l, c, p = OptimizedForInterval(mainInterval, function()\n            local o = OpenPrices()\n            local h = HighPrices()\n            local l = LowPrices()\n            local c = ClosePrices()\n            local p = HLCPrices()\n            \n            return o, h, l, c, p\n            end)\n        \n        local o2 = ArrayGet(o, 2)\n        local h2 = ArrayGet(h, 2)\n        local l2 = ArrayGet(l, 2)\n        local c2 = ArrayGet(c, 2)\n \n        local H3 = c + ((h - l) * 0.275)\n        local L3 = c - ((h - l) * 0.275)\n \n        local ma = SMA(p, 21)\n        Plot(0, 'Pivot SMA', ma, Yellow)\n        local longMA = c < ma\n        local shortMA = c > ma\n        local fastST = CC_SuperTrendExt(h, l, c, c, short_lookback, short_atr)\n        local slowST = CC_SuperTrendExt(h, l, c, c, long_lookback, long_atr)\n        Plot(0, 'Slow SuperTrend', slowST, DarkGray)\n        Plot(0, 'Fast SuperTrend', fastST, White)\n \n \n---------------------\n-- POSITIONS\n            local hedge_longPosId = Load(getMarket..'hedge_longPosId', NewGuid())\n            local hedge_shortPosId = Load(getMarket..'hedge_shortPosId', NewGuid())\n \n            local dir_l = GetPositionDirection(hedge_longPosId)\n            local aep_l = GetPositionEnterPrice(hedge_longPosId)\n            local pamt_l = GetPositionAmount(hedge_longPosId)\n            local delta_l = pamt_l > 0 and (cp.close - aep_l) / aep_l * 100 or 0\n            local proi_l = delta_l * leverage \n \n            local dir_s = GetPositionDirection(hedge_shortPosId)\n            local aep_s = GetPositionEnterPrice(hedge_shortPosId)\n            local pamt_s = GetPositionAmount(hedge_shortPosId)\n            local delta_s = pamt_s > 0 and (aep_s - cp.close) / aep_s * 100 or 0\n            local proi_s = delta_s * leverage\n \n        -- DELTA\n            local topDeltaL = Load('topDeltaL', 0)\n            local btmDeltaL = Load('btmDeltaL', 0)\n            if pamt_l > 0 and delta_l > topDeltaL then \n                Save('topDeltaL', delta_l) \n            elseif pamt_l > 0 and delta_l < btmDeltaL then \n                Save('btmDeltaL', delta_l) \n            elseif pamt_l == 0 then \n                Save('topDeltaL', 0)\n                Save('btmDeltaL', 0)\n            end\n            --Log('deltaL '..delta_l..' topDeltaL '..topDeltaL..' btmDeltaL '..btmDeltaL)\n \n            local topDeltaS = Load('topDeltaS', 0)\n            local btmDeltaS = Load('btmDeltaS', 0)\n            if pamt_s > 0 and delta_s > topDeltaS then \n                Save('topDeltaS', delta_s)\n            elseif pamt_s > 0 and delta_s < btmDeltaS then \n                Save('btmDeltaS', delta_s)  \n            elseif pamt_s == 0 then \n                Save('topDeltaS', 0)\n                Save('btmDeltaS', 0)\n            end\n            --Log('deltaS '..delta_s..' topDeltaS '..topDeltaS..' btmDeltaS '..btmDeltaS)\n \n        -- manage position ids\n            if pamt_l == 0 and IsPositionClosed(hedge_longPosId) then\n                if IsAnyOrderOpen(hedge_longPosId) then\n                    CancelAllOrders(hedge_longPosId)\n                else\n                    hedge_longPosId = NewGuid()\n                    dir_l = GetPositionDirection(hedge_longPosId)\n                    aep_l = GetPositionEnterPrice(hedge_longPosId)\n                    pamt_l = GetPositionAmount(hedge_longPosId)\n                    proi_l = delta_l * leverage \n                end\n            end\n            \n            if pamt_s == 0 and IsPositionClosed(hedge_shortPosId) then\n                if IsAnyOrderOpen(hedge_shortPosId) then\n                    CancelAllOrders(hedge_shortPosId)\n                else\n                    hedge_shortPosId = NewGuid()\n                    dir_s = GetPositionDirection(hedge_shortPosId)\n                    aep_s = GetPositionEnterPrice(hedge_shortPosId)\n                    pamt_s = GetPositionAmount(hedge_shortPosId)\n                    proi_s = delta_s * leverage\n                end\n            end\n        \n        -- get pos id\n            local getPositionId = function(isLong)\n                return isLong and hedge_longPosId or hedge_shortPosId\n            end\n \n---------------------\n-- WALLET CHECK\n    local profitLabel = ProfitLabel(getMarket)\n    if profitLabel == nil then profitLabel = QuoteCurrency(getMarket) end\n \n    -- inverse or not\n        if profitLabel == 'USD' or profitLabel == 'USDT' or profitLabel == 'BUSD' or profitLabel == 'USDC' then\n            isInverse = false \n        else\n            isInverse = true \n        end\n \n    -- check balance usage\n        if pamt_l > 0 then\n            usedLong = isInverse and ((pamt_l * contVal) / leverage) / cp.close or (pamt_l * aep_l) / leverage\n            getProfitL = isInverse and (cp.close - aep_l) * (leverage * usedLong) / cp.close or (cp.close - aep_l) * pamt_l\n        else \n            getProfitL = 0\n            usedLong = 0\n        end\n \n        if pamt_s > 0 then\n            usedShort = isInverse and ((pamt_s * contVal) / leverage) / cp.close or (pamt_s * aep_s) / leverage\n            getProfitS = isInverse and (aep_s - cp.close) * (leverage * usedShort) / cp.close or (aep_s - cp.close) * pamt_s\n        else \n            getProfitS = 0\n            usedShort = 0\n        end\n \n        local getProfit = getProfitL + getProfitS\n        local botProfit = GetBotProfit()\n        local netbotProfit = botProfit + getProfit\n \n    -- trading balance\n        local xchangeBal = WalletAmount(getAccount, profitLabel)\n        local walletBal = testWallet and testBal + botProfit\n                            or xchangeBal\n        local workBal = usedLong + usedShort - getProfit\n        local botBalance = startBal + botProfit\n        local netBalance = startBal + netbotProfit - usedLong - usedShort\n \n        if dynamicHodl and botProfit >= highestP * 0.8 then \n            profitOut = 0 \n        end \n \n        local maxCost = botProfit > 0 \n                        and botBalance - (botProfit * profitOut / 100)\n                        or botBalance  \n        \n    \n    -- balance warning\n        local balRatio = startBal > 0 and workBal / maxCost or 0\n        local okBalance = walletBal >= maxCost\n \n        if balRatio > 0.5 and balRatio < 0.8 then \n            Log('Working balance is > 50% of Budget!!!', Yellow) \n        end\n \n        if balRatio > 0.8 then \n            LogWarning('Working balance is > 80% of Budget!!!') \n        end\n \n        local BRCounter = Load('BRCounter', 0)\n        if balRatio > BRCounter then Save('BRCounter', balRatio) end\n    \n \n---------------------        \n-- WTF\n    if stopAtloss > 0 then  \n        if startBal + highestP > AddPerc(startBal, stopAtloss) then \n            if pamt_l == 0 and pamt_s == 0 and botBalance < SubPerc(startBal + highestP, stopAtloss) then \n                DeactivateBot('Bot loss limit reached.', true)\n            elseif netBalance < SubPerc(startBal + highestP, stopAtloss) then \n                if pamt_l != 0 then \n                    FEL = true \n                end \n \n                if pamt_s != 0 then \n                    FES = true \n                end \n            end\n            Log('Bot will stop when Bot Balance < '..SubPerc(startBal + highestP, stopAtloss)..' '..profitLabel, Yellow)\n            Plot(2, 'Stop @ Loss', SubPerc(startBal + highestP, stopAtloss), {c=Aqua, s=Step}) \n        else \n            Log('Stop at loss will start when Bot Balance > '..AddPerc(startBal, stopAtloss)..' '..profitLabel, Yellow)\n        end   \n    end \n \n    if stopAtprofit > 0 then  \n        if pamt_l == 0 and pamt_s == 0 and botBalance > AddPerc(startBal, stopAtprofit) then \n            DeactivateBot('Bot profit target reached.', true)\n        elseif netBalance > AddPerc(startBal, stopAtprofit) then \n                if pamt_l != 0 then \n                    FEL = true \n                end \n \n                if pamt_s != 0 then \n                    FES = true \n                end \n            Log('Bot will deactivate when Bot Balance > '..AddPerc(startBal, stopAtprofit)..' '..profitLabel, Yellow)\n        end   \n    end \n \n    if onlyWeekdays then\n        if today == 1 or today == 7 then \n            FEL = true \n            FES = true\n            Log('Not trading on weekend')\n        end\n        Log('Bot will not trading on weekend', Yellow)\n    end\n \n    if wtfBal then\n        if balRatio > reduceTrigger then\n            DeactivateBot('Deactivated because over budget', true)\n        end\n        Log('STOP at over budget safety activated. Is this a backtest ?', Yellow)\n    end\n \n    if wtfLoss != 0 or wtfProfit != 0 then\n        local pBalance = Load('pBalance', botBalance)\n \n        if wtfLoss != 0 then\n            local baseLoss = SubPerc(startBal, wtfLoss)\n            local targetAmount = maxCost * wtfLoss / 100\n            local lossLimit = botBalance - targetAmount\n            local newLL = Load('newLL', baseLoss)\n            Log('Bot will rest at Bot Balance below '..newLL..' '..profitLabel, DarkGreen)        \n            \n            if botBalance < newLL then\n                if prevDate != cd then \n                    Save('prevDate', cd)\n                end\n                Save('pBalance', botBalance)\n                Save('newLL', lossLimit) \n            end\n \n            if botBalance > pBalance then \n                Save('newLL', lossLimit)\n            end\n            Plot(2, 'Loss Limit', newLL, {c=Purple, s=Step}) \n        end\n \n        if wtfProfit != 0 then \n            local baseProfit = AddPerc(startBal, wtfProfit)\n            local targetAmount = maxCost * wtfProfit / 100\n            local profitLimit = botBalance + targetAmount\n            local newPL = Load('newPL', baseProfit)\n            Log('Bot will rest at Bot Balance above '..newPL..' '..profitLabel, DarkGreen)\n            \n            if botBalance > newPL then\n                if prevDate != cd then \n                    Save('prevDate', cd)\n                end\n                Save('pBalance', botBalance) \n                Save('newPL', profitLimit)\n            end\n \n            if botBalance < pBalance then \n                Save('newPL', profitLimit)\n            end\n            Plot(2, 'Profit Limit', newPL, {c=Purple, s=Step}) \n        end\n \n        if prevDate == cd \n            and botBalance == pBalance\n            and botProfit != 0\n            and pamt_l == 0\n            and pamt_s == 0 then \n                okLong = false\n                okShort = false\n            Log('Target reached, Bot is resting.', DarkGreen) \n            ChartSetOptions(-2, 'Resting Signal')\n            PlotSignalBar(-2, White)\n        end \n \n        Log('pBalance '..pBalance..' botBalance '..botBalance)\n        Plot(2, 'pBalance', pBalance) \n    end\n \n    if wtfStop then\n        local longNull = pamt_l == 0\n        local shortNull = pamt_s == 0\n        if longNull and shortNull then\n            DeactivateBot('Deactivated by No Position', true)\n        else\n            LogWarning('Will deactivate on No Position, waiting...maybe next second, maybe never :)')\n        end\n        Log('Deactivate on No Position is active.', Yellow)\n    end\n \n \n---------------------\n-- DYNAMICS\n    local LLP = LastLongPrice()\n    local longTrim = Load('LT', 0) \n    local longFilled = Load('LFM', 0)\n \n    local LSP = LastShortPrice()\n    local shortTrim = Load('ST', 0)\n    local shortFilled = Load('SFM', 0)\n    --Plot(8, 'LT ', longTrim, Green)\n    --Plot(8, 'ST ', shortTrim, Red)\n \n    -- ENTRY TP SL\n        -- ENTRY  \n            local longPrice = cp.bid\n            local shortPrice = cp.ask\n \n        -- SL\n            if longFilled == 0 then  \n                if slTrigger != 0 then \n                    longSLP = SubPerc(longPrice, slTrigger)\n                else \n                    longSLP = Min(SubPerc(fastST, slDistance), slowST) \n                end\n            elseif longFilled == 1 and longTrim == 0 then\n                Save('longSLP', longSLP)  \n            elseif longTrim >= 1 then\n                longSLP = AddPerc(Load('longSLP'), halvingAt * (longTrim + 1))\n            else \n                longSLP = Load('longSLP')\n            end\n        \n            if shortFilled == 0 then \n                if slTrigger != 0 then \n                    shortSLP = AddPerc(shortPrice, slTrigger)\n                else \n                    shortSLP = Max(AddPerc(fastST, slDistance), slowST)\n                end\n            elseif shortFilled == 1 and shortTrim == 0 then\n                Save('shortSLP', shortSLP)\n            elseif shortTrim >= 1 then \n                shortSLP = SubPerc(Load('shortSLP'), halvingAt * (shortTrim + 1))\n            else\n                shortSLP = Load('shortSLP')\n            end\n \n            local longSL_range = longPrice - longSLP\n            local shortSL_range = shortSLP - shortPrice\n \n        -- TP\n            local longTPrange = aep_l - longSLP\n            if pamt_l != 0 and longTrim == 0 then \n                exitPriceL = aep_l + (longTPrange * RR)\n                Save('EPL', exitPriceL)\n            else \n                exitPriceL = Load('EPL', H3)\n            end\n \n            local shortTPrange = shortSLP - aep_s\n            if pamt_s != 0 and shortTrim == 0 then \n                exitPriceS = aep_s - (shortTPrange * RR)\n                Save('EPS', exitPriceS)\n            else \n                exitPriceS = Load('EPS', L3)\n            end\n \n    -- the force\n        if FEL then \n            okLong = false\n            okProfitL = false\n            exitPriceL = cp.ask\n            LET = 'Forced'\n            Log('FORCE EXIT LONG POSITION ACTIVATED', Red) \n        end \n        \n        if FES then\n            okShort = false\n            okProfitS = false\n            exitPriceS = cp.bid\n            SET = 'Forced'\n            Log('FORCE EXIT SHORT POSITION ACTIVATED', Red) \n        end\n \n        --Log('Last Price Long: '..LLP..' | Short: '..LSP)\n        --Log('Exit Price -> Long: '..exitPriceL..' | Short: '..exitPriceS)\n        --Log('Enter Price -> Long: '..longPrice..' | Short: '..shortPrice)         \n \n    -- SLOT SIZE\n        if autoSlot then   \n            local risk = slotBudget / 100 * maxCost\n            --Log('risk '..risk..' longSL_range '..longSL_range..' shortSL_range '..shortSL_range)  \n \n            local sizeL = isInverse and (risk * longSLP / longSL_range ) * (longPrice / contVal) or risk / longSL_range\n            slotSizeL = sizeL > slotSizeD and sizeL or slotSizeD\n            \n            local sizeS = isInverse and (risk * shortSLP / shortSL_range) * (shortPrice / contVal) or risk / shortSL_range\n            slotSizeS = sizeS > slotSizeD and sizeS or slotSizeD\n            --Log('slotSizeL '..slotSizeL..' slotSizeS '..slotSizeS)\n        else\n            slotSizeL = slotSizeD \n            slotSizeS = slotSizeD \n        end\n \n        local halvingAtL = halvingAt\n        local halvingAtS = halvingAt\n        if fastST > slowST and c > fastST then \n            halvingAtS = halvingAt / 2\n            Log('Strong uptrend', Green)\n        elseif fastST > slowST and c < fastST then\n            halvingAtS = halvingAt / 2\n            Log('Weak uptrend', Green(50))        \n        elseif fastST < slowST and c < fastST then \n            halvingAtL = halvingAt / 2\n            Log('Strong downtrend', Red)\n        elseif fastST < slowST and c > fastST then \n            halvingAtL = halvingAt / 2\n            Log('Downtrend', Red(50))\n        end\n    \n    -- ORDER COST \n        local longCost = isInverse and ((slotSizeL * contVal) / leverage) / longPrice or (slotSizeL * longPrice) / leverage\n        local shortCost = isInverse and ((slotSizeS * contVal) / leverage) / shortPrice or (slotSizeS * shortPrice) / leverage\n        --Log('Cost Long: '..longCost..' Short: '..shortCost)\n \n \n---------------------\n-- EXECUTION\n    local ODL = PercentageChange(longSLP, aep_l) / orderCount \n    local ODS = PercentageChange(aep_s, shortSLP) / orderCount\n    if orderCount > 1 and longFilled == 1 and longTrim == 0 then \n        Save('ODL', ODL)\n    end \n    if orderCount > 1 and shortFilled == 1 and shortTrim == 0 then \n        Save('ODS', ODS)\n    end\n    local orderDistanceL = Load('ODL', ODL)\n    local orderDistanceS = Load('ODS', ODS)\n    --Log('ODL '..orderDistanceL..' ODS '..orderDistanceS)\n    \n    --LONG\n        --OPEN\n            local longOpen1 = pamt_l == 0\n                                and l > fastST\n                                and l2 > fastST\n                                and longPrice > AddPerc(longSLP, slDistance)\n                                and c < o \n                                and c2 < o2\n                                and fastST > slowST\n                                and longMA\n            local longOpen2 = orderCount > 1\n                                and pamt_l != 0\n                                and L3 < SubPerc(LLP, IfElse(dynamicDist, orderDistanceL, orderDistance)) \n                                and L3 > AddPerc(longSLP, IfElse(dynamicDist, orderDistanceL, orderDistance))\n \n            if longOpen1 then \n                LT = '1stOrder'\n            elseif longOpen2 then\n                longPrice = L3\n                LT = 'DCA'\n            elseif FOL then \n                longPrice = L3\n                LT = 'ForceLong' \n            end\n \n            local longOpen = okLong\n                                and okBalance\n                                and longFilled < orderCount\n                                and cp.close > longPrice\n                                and longCost < maxCost / 2 \n                                and IfElse(oneWay, pamt_s == 0, true)\n                                and (longOpen1 or longOpen2)\n \n        --DERISK\n            local okLongDerisk1 = pamt_l > 0\n                                    and (cp.ask < longSLP or fastST < slowST)\n            local okLongDerisk2 = pamt_l > 0\n                                    and halvingAt > 0\n                                    and delta_l > 0\n                                    and IfElse(okProfitL, cp.close < SubPerc(exitPriceL, halvingAtL), true) \n                                    and not okLongDerisk1\n \n            local longFSL = slTrigger > 0\n                            and pamt_l > 0\n                            and H3 < SubPerc(aep_l, slTrigger)\n \n            if okLongDerisk1 then \n                LDP = cp.ask\n                LDT = 'Derisking'\n            elseif okLongDerisk2 then\n                LDPc = AddPerc(aep_l, halvingAtL * (longTrim + 1)) \n                LDP = IfElse(cp.close < LDPc, LDPc, cp.ask)\n                LDT = 'LongHalving'\n                PlotSignalBar(3, Green)\n            else \n                LDP = longSLP\n            end\n \n            local okLongDerisk = okDerisk\n                                    and pamt_l > 0\n                                    and (okLongDerisk1 or okLongDerisk2)\n \n        --EXIT                        \n            local longExit1 = pamt_l > 0\n                                and halvingAt == 0\n                                and delta_l > 0\n                                and c > fastST\n            local longExit2 = pamt_l > 0\n                                and halvingAt != 0\n                                and H3 > exitPriceL\n                                and cp.close > SubPerc(exitPriceL, halvingAtL)\n            local longExit3 = pamt_l > 0 \n                                and halvingAt != 0\n                                and delta_l > halvingAtL\n                                and c < fastST\n                                and c < ma\n \n            if longExit1 then \n                LET = 'LE1'\n            elseif longExit2 then \n                exitPriceL = H3\n                LET = 'LE2'\n            elseif longExit3 then \n                exitPriceL = cp.ask\n                LET = 'LE3'\n            end\n \n            local longExit = okProfitL\n                                and not okLongDerisk\n                                and not FEL\n                                and (longExit1 or longExit2 or longExit3)\n \n    --SHORT \n        --OPEN       \n            local shortOpen1 = pamt_s == 0 \n                                and h < fastST \n                                and h2 < fastST\n                                and shortPrice < SubPerc(shortSLP, slDistance)\n                                and c > o \n                                and c2 > o2\n                                and fastST < slowST\n                                and shortMA\n            local shortOpen2 = orderCount > 1\n                                and pamt_s != 0\n                                and H3 > AddPerc(LSP, IfElse(dynamicDist, orderDistanceS, orderDistance))\n                                and H3 < SubPerc(shortSLP, IfElse(dynamicDist, orderDistanceS, orderDistance))\n \n            if shortOpen1 then \n                ST = '1stOrder'\n            elseif shortOpen2 then \n                shortPrice = H3\n                ST = 'DCA'\n            elseif FOS then \n                shortPrice = H3\n                LT = 'ForceShort'\n            end\n \n            local shortOpen = okShort\n                                and okBalance\n                                and shortFilled < orderCount\n                                and cp.close < shortPrice\n                                and shortCost < maxCost / 2 \n                                and IfElse(oneWay, pamt_l == 0, true)\n                                and (shortOpen1 or shortOpen2)\n        \n        --DERISK\n            local okShortDerisk1 = pamt_s > 0\n                                    and (cp.bid > shortSLP or fastST > slowST)\n            local okShortDerisk2 = pamt_s > 0\n                                    and halvingAt > 0\n                                    and delta_s > 0\n                                    and IfElse(okProfitS, cp.close > AddPerc(exitPriceS, halvingAtS), true) \n                                    and not okShortDerisk1\n            \n            local shortFSL = slTrigger > 0\n                                and pamt_s > 0 \n                                and L3 > AddPerc(aep_s, slTrigger)\n \n            if okShortDerisk1 then \n                SDP = cp.bid\n                SDT = 'Derisking'\n            elseif okShortDerisk2 then \n                SDPc = SubPerc(aep_s, halvingAtS * (shortTrim + 1)) \n                SDP = IfElse(cp.close > SDPc, SDPc, cp.bid)\n                SDT = 'ShortHalving'\n                PlotSignalBar(3, Red)\n            else \n                SDP = SubPerc(aep_s, halvingAtS * (shortTrim + 1))\n            end\n \n            local okShortDerisk = okDerisk\n                                    and (okShortDerisk1 or okShortDerisk2)\n \n        --EXIT                        \n            local shortExit1 = pamt_s > 0\n                                and halvingAt == 0\n                                and delta_s > 0\n                                and c < fastST\n            local shortExit2 = pamt_s > 0\n                                and halvingAt != 0\n                                and L3 < exitPriceS\n                                and cp.close < AddPerc(exitPriceS, halvingAtS)\n            local shortExit3 = pamt_s > 0 \n                                and halvingAt != 0\n                                and delta_s > halvingAtS\n                                and c > fastST\n                                and c > ma\n \n            if shortExit1 then \n                SET = 'SE1'\n            elseif shortExit2 then\n                exitPriceS = L3\n                SET = 'SE2'\n            elseif shortExit3 then\n                exitPriceS = cp.bid\n                SET = 'SE3'\n            end\n \n            local shortExit = okProfitS\n                                and not okShortDerisk\n                                and not FES\n                                and (shortExit1 or shortExit2 or shortExit3 )\n \n \n---------------------\n-- CORE LOGIC HEDGE MODE\n    -- ENTRY\n            local timerL = Load('timerL', ct)\n            local timerS = Load('timerS', ct)\n            --Log('ct '..ct..' timerL '..timerL..' timerS '..timerS)\n            local slot = function(isLong, amount, timer, trigger, canPlace)\n                local prefix = isLong and 'L' or 'S'\n                local name = prefix\n                local cmd = isLong and PlaceGoLongOrder or PlaceGoShortOrder\n                local price = isLong and longPrice or shortPrice\n                local posId = getPositionId(isLong)\n                local aep = isLong and aep_l or aep_s\n                local pamt = isLong and pamt_l or pamt_s\n                local TOPB = TradeOncePerBar(mainInterval, posId)\n                local filled = isLong and longFilled + 1 or shortFilled + 1\n \n                local oid = Load(name..'oid', '') -- order id\n                if oid != '' then\n                    local order = OrderContainer(oid)\n \n                    if order.isOpen then\n                        if not canPlace then\n                            CancelOrder(oid)\n                            LogWarning('Not allowed right now '..name)\n                        end\n                    elseif order.isFilled then \n                        if isLong then \n                            Save('LFM', longFilled + 1)\n                        else \n                            Save('SFM', shortFilled + 1)\n                        end\n                        oid = '' \n                    else \n                        oid = ''\n                    end\n                else\n                    if canPlace and TOPB and ct >= timer then\n                        SetFee(MakersFee(getMarket))\n                        oid = cmd(price, amount, {market = getMarket, type = MakerOrCancelOrderType, note = name..filled..'-'..trigger, positionId = posId})\n                    end\n                end\n \n                Save(name..'oid', oid)\n            end\n \n            -- variables\n                slot(true, slotSizeL, timerL, LT, longOpen or FOL) -- long slot\n                slot(false, slotSizeS, timerS, ST, shortOpen or FOS) -- short slot\n \n    -- EXIT\n            local updateTakeProfit = function(isLong, exitPrice, ET, canExit)\n                local price = isLong and IfElse(cp.close < exitPrice, exitPrice, cp.ask) \n                                or IfElse(cp.close > exitPrice, exitPrice, cp.bid) \n                local placeDelta = isLong and (price - aep_l) / aep_l * 100\n                                    or (aep_s - price) / aep_s * 100\n                local prefix = isLong and 'L' or 'S'\n                local name = prefix .. ' TP '..placeDelta..'%'\n                local oid = Load(prefix .. 'tp_oid', '')\n                local posId = getPositionId(isLong)\n \n                if oid != '' then\n                    local order = OrderContainer(oid)\n \n                    if order.isOpen then\n                        if not canExit then\n                            CancelOrder(oid)\n                            LogWarning('Exit cancelled '..name)\n                        end\n                    else\n                        oid = ''\n                    end\n                else\n                    if canExit then\n                        SetFee(tpOrderType == MarketOrderType and TakersFee() or MakersFee())\n                        oid = PlaceExitPositionOrder({timeout = mainInterval * 60, price = price, type = tpOrderType, note = name..'-'..ET, positionId = posId})\n                    end\n                end\n \n                Save(prefix .. 'tp_oid', oid)\n            end\n \n            -- variables\n                updateTakeProfit(true, exitPriceL, LET, longExit or FEL)\n                updateTakeProfit(false, exitPriceS, SET, shortExit or FES)\n \n    -- Balance Ratio REDUCTION\n            local updatePositionManagement = function(isLong, currentSize, canReduce)\n                local price = isLong and cp.ask or cp.bid\n                local placeDelta = isLong and (price - aep_l) / aep_l * 100\n                                    or (aep_s - price) / aep_s * 100\n                local prefix = isLong and 'Long' or 'Short'\n                local name = prefix .. ' Size Reduction '..placeDelta..'%'\n                local oid = Load(prefix .. 'pos_oid', '')\n                local posId = getPositionId(isLong)\n                local amount = SubPerc(currentSize, 100 - reduceSize) -- take X% of position\n                local cmd = isLong\n                        and PlaceExitLongOrder\n                        or PlaceExitShortOrder\n                local timer = Load(prefix .. 'pos_timer', Time())\n \n                if oid != '' then\n                    local order = OrderContainer(oid)\n \n                    if order.isOpen then                        \n                        if not canReduce then\n                            CancelOrder(oid)\n                            LogWarning('Reduction cancelled '..name)\n                        end\n                    else\n                        sizeRed = 1\n                        Save('SRCounter', SRCounter + sizeRed)\n                        oid = ''\n                    end\n                else\n                    if canReduce and Time() >= timer then\n                        CancelAllOrders()\n                        SetFee(reduceOrderType == MarketOrderType and TakersFee() or MakersFee())\n                        oid = cmd(price, amount, {market = getMarket, type = reduceOrderType, note = name, timeout = 6000, positionId = posId})\n                        timer = Time() + 60 -- 1min   \n                    end\n                end\n \n                Save(prefix .. 'pos_oid', oid)\n                Save(prefix .. 'pos_timer', timer)\n            end\n \n            -- variables\n                updatePositionManagement(true, pamt_l, okReduce and pamt_l > 0 and balRatio > reduceTrigger and delta_l < delta_s)\n                updatePositionManagement(false, pamt_s, okReduce and pamt_s > 0 and balRatio > reduceTrigger and delta_s < delta_l)\n \n    -- Derisking REDUCTION\n            local derisking = function(isLong, currentSize, price, DT, canDerisk)\n                local amount = SubPerc(currentSize, 100 - reduceSize) -- take X% of position\n                local openDT = Load('openDT', DT)\n                local trimDone = isLong and longTrim or shortTrim\n                if DT == 'ShortHalving' or DT == 'LongHalving' then\n                    reduceOrderType = MakerOrCancelOrderType\n                    amount = currentSize / 2 \n                end\n                local placeDelta = isLong and (price - aep_l) / aep_l * 100\n                                    or (aep_s - price) / aep_s * 100\n                local prefix = isLong and 'Long ' or 'Short '\n                local name = prefix..' Derisking '..placeDelta..'%'\n                local oid = Load(prefix .. 'derisk_oid', '')\n                local posId = getPositionId(isLong)\n                local cmd = isLong\n                            and PlaceExitLongOrder\n                            or PlaceExitShortOrder\n \n                -- amount check \n                    if amount < MinimumTradeAmount(getMarket, price) then \n                        amount = currentSize\n                    end\n \n                if oid != '' then\n                    local order = OrderContainer(oid)\n                     \n                    if order.isOpen then\n                        if not canDerisk then\n                            CancelOrder(oid)\n                            LogWarning('Reduction cancelled '..name)\n                        end\n                        if openDT != DT then \n                            CancelOrder(oid)\n                        end\n                    elseif order.isFilled then\n                        if isLong then\n                            if LDT == 'LongHalving' then\n                                Save('LT', longTrim + 1)\n                            end\n                            Save('timerL', ct + (delay * 60))\n                        else \n                            if SDT == 'ShortHalving' then \n                                Save('ST', shortTrim + 1)\n                            end\n                            Save('timerS', ct + (delay * 60))\n                        end\n                        oid = ''\n                    else\n                        oid = '' \n                    end\n                else\n                    if canDerisk then\n                        CancelAllOrders()\n                        SetFee(reduceOrderType == MarketOrderType and TakersFee() or MakersFee())\n                        oid = cmd(price, amount, {market = getMarket, type = reduceOrderType, note = name..'-'..DT, timeout = mainInterval * 60, positionId = posId})\n                        Save('openDT', DT)\n                    end\n                end\n                Save(prefix .. 'derisk_oid', oid) \n            end\n        -- variables\n            derisking(true, pamt_l, LDP, LDT, okLongDerisk or longFSL)\n            derisking(false, pamt_s, SDP, SDT, okShortDerisk or shortFSL)\n \n    -- Positions Data\n        if pamt_l > 0 then\n            if halvingAt > 0 then \n                Log('Next LONG halving is at '..LDP)\n            end\n            Log('LONG Delta: '..Round(delta_l, 2)..\n                '% | Highest: '..Round(topDeltaL, 2)..\n                '% | Lowest: '..Round(btmDeltaL, 2)..\n                '% | Amount: '..getProfitL)\n        end\n        if pamt_s > 0 then \n            if halvingAt > 0 then \n                Log('Next SHORT halving is at '..SDP)\n            end\n            Log('SHORT Delta: '..Round(delta_s, 2)..\n                '% | Highest: '..Round(topDeltaS, 2)..\n                '% | Lowest: '..Round(btmDeltaS, 2)..\n                '% | Amount: '..getProfitS)\n        end\n \n \n---------------------\n-- DATA SAVING\n    Save(getMarket..'hedge_longPosId', hedge_longPosId)\n    Save(getMarket..'hedge_shortPosId', hedge_shortPosId)\n \n    if botProfit > highestP then \n        Save('highestP', botProfit)\n    elseif botProfit < lowestP then \n        Save('lowestP', botProfit) \n    end\n \n    if pamt_l == 0 then \n        Save('LT', 0) \n        Save('LFM', 0) \n    end\n    if pamt_s == 0 then  \n        Save('ST', 0)\n        Save('SFM', 0)\n    end \n \n \n--------------------- \n-- PLOT\n    -- AEP Plot\n        if aep_l > 0 then\n            local posId = getPositionId(true)\n            Plot(0, 'AvgEP Long', aep_l, {c=Teal, id=posId, w=2})\n            Plot(0, 'SL Long', longSLP, {c=Teal, id=posId, w=1})\n            --Plot(0, 'TP Long', exitPriceL, {c=Teal, id=posId, w=1})\n        end\n    \n        if aep_s > 0 then\n            local posId = getPositionId(false)\n            Plot(0, 'AvgEP Short', aep_s, {c=Purple, id=posId, w=2})\n            Plot(0, 'SL Short', shortSLP, {c=Purple, id=posId, w=1})\n            --Plot(0, 'TP Short', exitPriceS, {c=Purple, id=posId, w=1})\n        end\n \n    ChartSetOptions(1, 'Exposure')\n    local lineLong = IfElse(pamt_l > 0, pamt_l, 0)\n    local lineShort = IfElse(pamt_s > 0, -pamt_s, 0)\n    Plot(1, 'Longs', lineLong, {c=Green, s=Step})\n    Plot(1, 'Shorts', lineShort, {c=Red, s=Step})\n    \n    ChartSetOptions(2, 'Balance Monitor')\n    Plot(2, 'Net Balance', netBalance, {c=Orange, s=Step})\n    Plot(2, 'Trading Balance', maxCost, {c=White, s=Step})\n    Plot(2, 'WorkBal', workBal, {c=Red, s=Step})\n    Plot(2, 'Bot Profit', botProfit, {c=DarkGreen, s=Step})\n    Plot(2, 'Bot Balance', botBalance, {c=Yellow, s=Step}) \n \n    Log('Size Reduction: '..SRCounter..' times')\n \n \n---------------------\n-- FINAL REPORT\n    Finalize(function()\n        CustomReport('Current Balance Ratio', Round(100 * balRatio, 2)..'%')\n        CustomReport('Highest Balance Ratio', Round(100 * BRCounter, 2)..'%')\n        CustomReport('Size Reduction', SRCounter..' times')\n        CustomReport('Final Wallet Balance', Round(walletBal, 5)..' '..profitLabel)\n        CustomReport('Final Net Balance', Round(netBalance, 5)..' '..profitLabel)\n        CustomReport('Highest Profit', Round(highestP, 5)..' '..profitLabel)\n        CustomReport('Lowest Profit', Round(lowestP, 5)..' '..profitLabel)\n        if testWallet then\n            local realprofitPercent = Round(botProfit / startBal * 100, 2) \n            local runprofitPercent = Round(netbotProfit / startBal * 100, 2) \n            CustomReport('Running Profit %: ', runprofitPercent..'%')\n            CustomReport('Realized Profit %: ', realprofitPercent..'%')\n            CustomReport('Profit to Highest Bal Ratio', Round(realprofitPercent / (100 * BRCounter), 2))\n        end    \n    end)\n \n \n---------------------\n-- INFO \n    Log('Profit Monitor -> Current: '..Round(botProfit, 5)..' '..profitLabel..' | Highest: '..Round(highestP, 5)..' '..profitLabel..' | Lowest: '..Round(lowestP, 5)..' '..profitLabel)\n    Log('Balance Monitor -> Wallet: '..Round(walletBal, 5)..' '..profitLabel..\n        ' | Bot: '..Round(botBalance, 5)..' '..profitLabel..\n        ' | Trading: '..Round(maxCost, 5)..' '..profitLabel..\n        ' | Net: '..Round(netBalance, 5)..' '..profitLabel..\n        ' | Working: '..Round(workBal, 5)..' '..profitLabel..\n        ' | Ratio: '..Round(balRatio, 3))\n \n \n---------------------\n-- BALANCE WARNING\n    if not okBalance then\n        LogWarning('TRADING BALANCE < EXCHANGE BALANCE')\n    end\n    if startBal == 0 then \n        LogWarning('Please enter trading balance')\n    end\n \nLog('Market '..getMarket)\nLog('SMOKYBOT MK3')\nLog(' ')",
    "CR": {
      "IV": true,
      "C": null,
      "CR": [
        "SuperTrendExt"
      ],
      "CL": [
        "1765219016 ||| 0 ||| Compiling script...",
        "1765219016 ||| 0 ||| This script is compatible with margin and leverage trading.",
        "1765219016 ||| 0 ||| Tip wallet ERC20: 0xaa28dE4372CA0a8BC36722886E9749f70DF32382",
        "1765219016 ||| 0 ||| High speed updates enabled.",
        "1765219016 ||| 0 ||| Registered input 'Super Trend Setting'",
        "1765219016 ||| 0 ||| Registered input '01A. Short Period'",
        "1765219016 ||| 0 ||| Registered input '02. Short ATR'",
        "1765219016 ||| 0 ||| Registered input '01. Long Period'",
        "1765219016 ||| 0 ||| Registered input '02. Long ATR'",
        "1765219016 ||| 0 ||| Registered input 'Trade Settings'",
        "1765219016 ||| 0 ||| Registered input '01A. Long Entry'",
        "1765219016 ||| 0 ||| Registered input '01B. Long Exit'",
        "1765219016 ||| 0 ||| Registered input '02A. Short Entry'",
        "1765219016 ||| 0 ||| Registered input '02B. Short Exit'",
        "1765219016 ||| 0 ||| Registered input '03. BalRatio Reduction'",
        "1765219016 ||| 0 ||| Registered input '04. Risk Reduction'",
        "1765219016 ||| 0 ||| Registered input '05. Not Hedge'",
        "1765219016 ||| 0 ||| Registered input '06. Only Weekdays'",
        "1765219016 ||| 0 ||| Registered input 'Bot Settings'",
        "1765219016 ||| 0 ||| Registered input '01. Stop at no position'",
        "1765219016 ||| 0 ||| Registered input '02. Recalculate Slot Size'",
        "1765219016 ||| 0 ||| Registered input '03. Force Open Long'",
        "1765219016 ||| 0 ||| Registered input '04. Force Exit Long'",
        "1765219016 ||| 0 ||| Registered input '05. Force Open Short'",
        "1765219016 ||| 0 ||| Registered input '06. Force Exit Short'",
        "1765219016 ||| 0 ||| Registered input '07. Pause at % LOSS'",
        "1765219016 ||| 0 ||| Registered input '08. Pause at % PROFIT'",
        "1765219016 ||| 0 ||| Registered input 'Backtest Settings'",
        "1765219016 ||| 0 ||| Registered input '01. Deactivate on Over Budget'",
        "1765219016 ||| 0 ||| Registered input 'Custom Wallet'",
        "1765219016 ||| 0 ||| Registered input '01. Activate Custom Wallet'",
        "1765219016 ||| 0 ||| Registered input '02. Custom Wallet Balance'",
        "1765219016 ||| 0 ||| Registered input 'Budget'",
        "1765219016 ||| 0 ||| Registered input '01. Starting Balance '",
        "1765219016 ||| 0 ||| Registered input '02. Profit Limit %'",
        "1765219016 ||| 0 ||| Registered input '03. Loss Limit %'",
        "1765219016 ||| 0 ||| Registered input '04. Leverage'",
        "1765219016 ||| 0 ||| Registered input '05. Inverse Contract Value'",
        "1765219016 ||| 0 ||| Registered input 'Safety'",
        "1765219016 ||| 0 ||| Registered input '01.Fix SL %'",
        "1765219016 ||| 0 ||| Registered input '02. Min. Dynamic SL %'",
        "1765219016 ||| 0 ||| Registered input '03. Bal Ratio Trigger'",
        "1765219016 ||| 0 ||| Registered input '04. Size Reduction %'",
        "1765219016 ||| 0 ||| Order type input field 05. Reduction Order Type found. (value: Maker or Cancel)",
        "1765219016 ||| 0 ||| Registered input '06. Profit Hodl %'",
        "1765219016 ||| 0 ||| Registered input '07. Dynamic Hodl'",
        "1765219016 ||| 0 ||| Registered input '08. SL Delay (Min)'",
        "1765219016 ||| 0 ||| Registered input 'Order'",
        "1765219016 ||| 0 ||| Registered input '01. Orders Count'",
        "1765219016 ||| 0 ||| Registered input '02. Risk % per order'",
        "1765219016 ||| 0 ||| Registered input '02A. Fix Orders Distance %'",
        "1765219016 ||| 0 ||| Registered input '02B. Dynamic Order Distance %'",
        "1765219016 ||| 0 ||| Registered input '03A. Min. Order Size '",
        "1765219016 ||| 0 ||| Registered input '03B. Dynamic Order Size'",
        "1765219016 ||| 0 ||| Registered input 'Profit'",
        "1765219016 ||| 0 ||| Registered input '01. Reward to Risk'",
        "1765219016 ||| 0 ||| Registered input '02. Halving %'",
        "1765219016 ||| 0 ||| Order type input field 03. TP Order Type found. (value: Maker or Cancel)",
        "1765219016 ||| 2 ||| WARNING: Warming up SuperTrend...",
        "1765219016 ||| 2 ||| WARNING: Warmup completed.",
        "1765219016 ||| 2 ||| WARNING: Warming up SuperTrend...",
        "1765219016 ||| 2 ||| WARNING: Warmup completed.",
        "1765219016 ||| 0 ||| Size Reduction: 0 times",
        "1765219016 ||| 0 ||| Profit Monitor -> Current: 0 ARS | Highest: 0 ARS | Lowest: 0 ARS",
        "1765219016 ||| 0 ||| Balance Monitor -> Wallet: 0 ARS | Bot: 0 ARS | Trading: 0 ARS | Net: 0 ARS | Working: 0 ARS | Ratio: 0",
        "1765219016 ||| 2 ||| WARNING: Please enter trading balance",
        "1765219016 ||| 0 ||| Market BINANCE_BTC_ARS_",
        "1765219016 ||| 0 ||| SMOKYBOT MK3",
        "1765219016 ||| 0 |||  ",
        "1765219016 ||| 0 ||| Compile test OK."
      ],
      "LCE": [],
      "VCE": [],
      "I": [
        {
          "T": 10,
          "ST": -1,
          "G": "Super Trend Setting",
          "K": "11-11-4-20.Super Trend Setting",
          "EK": "11-11-4-20",
          "N": "Super Trend Setting",
          "TT": "",
          "V": "",
          "D": "",
          "O": null,
          "MIN": 0.0,
          "MAX": 0.0
        },
        {
          "T": 0,
          "ST": -1,
          "G": "Super Trend Setting",
          "K": "12-12-31-36.01A. Short Period",
          "EK": "12-12-31-36",
          "N": "01A. Short Period",
          "TT": "",
          "V": "8",
          "D": "8",
          "O": null,
          "MIN": 0.0,
          "MAX": 0.0
        },
        {
          "T": 0,
          "ST": -1,
          "G": "Super Trend Setting",
          "K": "13-13-26-31.02. Short ATR",
          "EK": "13-13-26-31",
          "N": "02. Short ATR",
          "TT": "",
          "V": "3",
          "D": "3",
          "O": null,
          "MIN": 0.0,
          "MAX": 0.0
        },
        {
          "T": 0,
          "ST": -1,
          "G": "Super Trend Setting",
          "K": "14-14-30-35.01. Long Period",
          "EK": "14-14-30-35",
          "N": "01. Long Period",
          "TT": "",
          "V": "21",
          "D": "21",
          "O": null,
          "MIN": 0.0,
          "MAX": 0.0
        },
        {
          "T": 0,
          "ST": -1,
          "G": "Super Trend Setting",
          "K": "15-15-25-30.02. Long ATR",
          "EK": "15-15-25-30",
          "N": "02. Long ATR",
          "TT": "",
          "V": "8",
          "D": "8",
          "O": null,
          "MIN": 0.0,
          "MAX": 0.0
        },
        {
          "T": 10,
          "ST": -1,
          "G": "Trade Settings",
          "K": "17-17-4-20.Trade Settings",
          "EK": "17-17-4-20",
          "N": "Trade Settings",
          "TT": "",
          "V": "",
          "D": "",
          "O": null,
          "MIN": 0.0,
          "MAX": 0.0
        },
        {
          "T": 2,
          "ST": -1,
          "G": "Trade Settings",
          "K": "18-18-23-28.01A. Long Entry",
          "EK": "18-18-23-28",
          "N": "01A. Long Entry",
          "TT": "Allow bot to open Long",
          "V": "False",
          "D": "False",
          "O": null,
          "MIN": 0.0,
          "MAX": 0.0
        },
        {
          "T": 2,
          "ST": -1,
          "G": "Trade Settings",
          "K": "19-19-26-31.01B. Long Exit",
          "EK": "19-19-26-31",
          "N": "01B. Long Exit",
          "TT": "Allow bot to exit Long",
          "V": "False",
          "D": "False",
          "O": null,
          "MIN": 0.0,
          "MAX": 0.0
        },
        {
          "T": 2,
          "ST": -1,
          "G": "Trade Settings",
          "K": "20-20-24-29.02A. Short Entry",
          "EK": "20-20-24-29",
          "N": "02A. Short Entry",
          "TT": "Allow bot to open Short",
          "V": "False",
          "D": "False",
          "O": null,
          "MIN": 0.0,
          "MAX": 0.0
        },
        {
          "T": 2,
          "ST": -1,
          "G": "Trade Settings",
          "K": "21-21-26-31.02B. Short Exit",
          "EK": "21-21-26-31",
          "N": "02B. Short Exit",
          "TT": "Allow bot to exit Short",
          "V": "False",
          "D": "False",
          "O": null,
          "MIN": 0.0,
          "MAX": 0.0
        },
        {
          "T": 2,
          "ST": -1,
          "G": "Trade Settings",
          "K": "22-22-25-30.03. BalRatio Reduction",
          "EK": "22-22-25-30",
          "N": "03. BalRatio Reduction",
          "TT": "Allow Bal Ratio based size reduction",
          "V": "False",
          "D": "False",
          "O": null,
          "MIN": 0.0,
          "MAX": 0.0
        },
        {
          "T": 2,
          "ST": -1,
          "G": "Trade Settings",
          "K": "23-23-25-30.04. Risk Reduction",
          "EK": "23-23-25-30",
          "N": "04. Risk Reduction",
          "TT": "Allow Signal based size reduction",
          "V": "False",
          "D": "False",
          "O": null,
          "MIN": 0.0,
          "MAX": 0.0
        },
        {
          "T": 2,
          "ST": -1,
          "G": "Trade Settings",
          "K": "24-24-23-28.05. Not Hedge",
          "EK": "24-24-23-28",
          "N": "05. Not Hedge",
          "TT": "Selec this if the market is NOT HEDGE mode",
          "V": "False",
          "D": "False",
          "O": null,
          "MIN": 0.0,
          "MAX": 0.0
        },
        {
          "T": 2,
          "ST": -1,
          "G": "Trade Settings",
          "K": "25-25-29-34.06. Only Weekdays",
          "EK": "25-25-29-34",
          "N": "06. Only Weekdays",
          "TT": "Bot will close any position and not trading during weekend",
          "V": "False",
          "D": "False",
          "O": null,
          "MIN": 0.0,
          "MAX": 0.0
        },
        {
          "T": 10,
          "ST": -1,
          "G": "Bot Settings",
          "K": "27-27-4-20.Bot Settings",
          "EK": "27-27-4-20",
          "N": "Bot Settings",
          "TT": "",
          "V": "",
          "D": "",
          "O": null,
          "MIN": 0.0,
          "MAX": 0.0
        },
        {
          "T": 2,
          "ST": -1,
          "G": "Bot Settings",
          "K": "28-28-24-29.01. Stop at no position",
          "EK": "28-28-24-29",
          "N": "01. Stop at no position",
          "TT": "Deactivate bot when there is no open position.",
          "V": "False",
          "D": "False",
          "O": null,
          "MIN": 0.0,
          "MAX": 0.0
        },
        {
          "T": 2,
          "ST": -1,
          "G": "Bot Settings",
          "K": "29-29-26-31.02. Recalculate Slot Size",
          "EK": "29-29-26-31",
          "N": "02. Recalculate Slot Size",
          "TT": "If activated will ALWAYS calculating slot size. If not activatated slot size will only calculated when there is no open position.",
          "V": "False",
          "D": "False",
          "O": null,
          "MIN": 0.0,
          "MAX": 0.0
        },
        {
          "T": 2,
          "ST": -1,
          "G": "Bot Settings",
          "K": "30-30-20-25.03. Force Open Long",
          "EK": "30-30-20-25",
          "N": "03. Force Open Long",
          "TT": "Force open LONG position",
          "V": "False",
          "D": "False",
          "O": null,
          "MIN": 0.0,
          "MAX": 0.0
        },
        {
          "T": 2,
          "ST": -1,
          "G": "Bot Settings",
          "K": "31-31-20-25.04. Force Exit Long",
          "EK": "31-31-20-25",
          "N": "04. Force Exit Long",
          "TT": "Force exit LONG position",
          "V": "False",
          "D": "False",
          "O": null,
          "MIN": 0.0,
          "MAX": 0.0
        },
        {
          "T": 2,
          "ST": -1,
          "G": "Bot Settings",
          "K": "32-32-20-25.05. Force Open Short",
          "EK": "32-32-20-25",
          "N": "05. Force Open Short",
          "TT": "Force open SHORT position",
          "V": "False",
          "D": "False",
          "O": null,
          "MIN": 0.0,
          "MAX": 0.0
        },
        {
          "T": 2,
          "ST": -1,
          "G": "Bot Settings",
          "K": "33-33-20-25.06. Force Exit Short",
          "EK": "33-33-20-25",
          "N": "06. Force Exit Short",
          "TT": "Force exit SHORT position",
          "V": "False",
          "D": "False",
          "O": null,
          "MIN": 0.0,
          "MAX": 0.0
        },
        {
          "T": 0,
          "ST": -1,
          "G": "Bot Settings",
          "K": "34-34-24-29.07. Pause at % LOSS",
          "EK": "34-34-24-29",
          "N": "07. Pause at % LOSS",
          "TT": "Pause trading until next day UTC when LOSS % below this. 0 is disalbe.",
          "V": "0",
          "D": "0",
          "O": null,
          "MIN": 0.0,
          "MAX": 0.0
        },
        {
          "T": 0,
          "ST": -1,
          "G": "Bot Settings",
          "K": "35-35-26-31.08. Pause at % PROFIT",
          "EK": "35-35-26-31",
          "N": "08. Pause at % PROFIT",
          "TT": "Pause trading until next day UTC when PROFIT % above this. 0 is disable.",
          "V": "0",
          "D": "0",
          "O": null,
          "MIN": 0.0,
          "MAX": 0.0
        },
        {
          "T": 10,
          "ST": -1,
          "G": "Backtest Settings",
          "K": "37-37-4-20.Backtest Settings",
          "EK": "37-37-4-20",
          "N": "Backtest Settings",
          "TT": "",
          "V": "",
          "D": "",
          "O": null,
          "MIN": 0.0,
          "MAX": 0.0
        },
        {
          "T": 2,
          "ST": -1,
          "G": "Backtest Settings",
          "K": "38-38-23-28.01. Deactivate on Over Budget",
          "EK": "38-38-23-28",
          "N": "01. Deactivate on Over Budget",
          "TT": "ONLY FOR BACKTEST. Disable bot when Bal. Ratio hit trigger",
          "V": "False",
          "D": "False",
          "O": null,
          "MIN": 0.0,
          "MAX": 0.0
        },
        {
          "T": 10,
          "ST": -1,
          "G": "Custom Wallet",
          "K": "40-40-4-20.Custom Wallet",
          "EK": "40-40-4-20",
          "N": "Custom Wallet",
          "TT": "",
          "V": "",
          "D": "",
          "O": null,
          "MIN": 0.0,
          "MAX": 0.0
        },
        {
          "T": 2,
          "ST": -1,
          "G": "Custom Wallet",
          "K": "41-41-27-32.01. Activate Custom Wallet",
          "EK": "41-41-27-32",
          "N": "01. Activate Custom Wallet",
          "TT": "Use custom wallet amount. A must in Haaslab",
          "V": "False",
          "D": "False",
          "O": null,
          "MIN": 0.0,
          "MAX": 0.0
        },
        {
          "T": 0,
          "ST": -1,
          "G": "Custom Wallet",
          "K": "42-42-24-29.02. Custom Wallet Balance",
          "EK": "42-42-24-29",
          "N": "02. Custom Wallet Balance",
          "TT": "Amount of custom wallet",
          "V": "0",
          "D": "0",
          "O": null,
          "MIN": 0.0,
          "MAX": 0.0
        },
        {
          "T": 10,
          "ST": -1,
          "G": "Budget",
          "K": "44-44-4-20.Budget",
          "EK": "44-44-4-20",
          "N": "Budget",
          "TT": "",
          "V": "",
          "D": "",
          "O": null,
          "MIN": 0.0,
          "MAX": 0.0
        },
        {
          "T": 0,
          "ST": -1,
          "G": "Budget",
          "K": "45-45-25-30.01. Starting Balance ",
          "EK": "45-45-25-30",
          "N": "01. Starting Balance ",
          "TT": "Starting trading balance which also maximum COST to limit working balance (margin cost + unrealised loss)",
          "V": "0",
          "D": "0",
          "O": null,
          "MIN": 0.0,
          "MAX": 0.0
        },
        {
          "T": 0,
          "ST": -1,
          "G": "Budget",
          "K": "46-46-29-34.02. Profit Limit %",
          "EK": "46-46-29-34",
          "N": "02. Profit Limit %",
          "TT": "Deactivate bot when bot gaining this % amount from the starting balance",
          "V": "0",
          "D": "0",
          "O": null,
          "MIN": 0.0,
          "MAX": 0.0
        },
        {
          "T": 0,
          "ST": -1,
          "G": "Budget",
          "K": "47-47-27-32.03. Loss Limit %",
          "EK": "47-47-27-32",
          "N": "03. Loss Limit %",
          "TT": "Deactivate bot when bot losing this % amount from the highest balance recorded",
          "V": "0",
          "D": "0",
          "O": null,
          "MIN": 0.0,
          "MAX": 0.0
        },
        {
          "T": 0,
          "ST": -1,
          "G": "Budget",
          "K": "48-48-25-30.04. Leverage",
          "EK": "48-48-25-30",
          "N": "04. Leverage",
          "TT": "MUST be filled and same as in exchange setting. Important for trading budget",
          "V": "50",
          "D": "50",
          "O": null,
          "MIN": 0.0,
          "MAX": 0.0
        },
        {
          "T": 0,
          "ST": -1,
          "G": "Budget",
          "K": "49-49-24-29.05. Inverse Contract Value",
          "EK": "49-49-24-29",
          "N": "05. Inverse Contract Value",
          "TT": "ONLY if bot trading on INVERSE Futures then enter the Contract Value. Ignore if not",
          "V": "10",
          "D": "10",
          "O": null,
          "MIN": 0.0,
          "MAX": 0.0
        },
        {
          "T": 10,
          "ST": -1,
          "G": "Safety",
          "K": "51-51-4-20.Safety",
          "EK": "51-51-4-20",
          "N": "Safety",
          "TT": "",
          "V": "",
          "D": "",
          "O": null,
          "MIN": 0.0,
          "MAX": 0.0
        },
        {
          "T": 0,
          "ST": -1,
          "G": "Safety",
          "K": "52-52-26-31.01.Fix SL %",
          "EK": "52-52-26-31",
          "N": "01.Fix SL %",
          "TT": "0 is disable, else DISREGARDING RISK REDUCTION option and signal bot will derisking when % price change againts average entry.",
          "V": "0",
          "D": "0",
          "O": null,
          "MIN": 0.0,
          "MAX": 0.0
        },
        {
          "T": 0,
          "ST": -1,
          "G": "Safety",
          "K": "53-53-27-32.02. Min. Dynamic SL %",
          "EK": "53-53-27-32",
          "N": "02. Min. Dynamic SL %",
          "TT": "Signal based min % price distance from 1st entry to calculate stop loss price.",
          "V": "1",
          "D": "1",
          "O": null,
          "MIN": 0.0,
          "MAX": 0.0
        },
        {
          "T": 0,
          "ST": -1,
          "G": "Safety",
          "K": "54-54-30-35.03. Bal Ratio Trigger",
          "EK": "54-54-30-35",
          "N": "03. Bal Ratio Trigger",
          "TT": "Ratio between working balance and trading balance to trigger size reduction",
          "V": "0.8",
          "D": "0.8",
          "O": null,
          "MIN": 0.0,
          "MAX": 0.0
        },
        {
          "T": 0,
          "ST": -1,
          "G": "Safety",
          "K": "55-55-27-32.04. Size Reduction %",
          "EK": "55-55-27-32",
          "N": "04. Size Reduction %",
          "TT": "SHOULD BE factors of 100. In risk reduction: 1st reduction 25%, 2nd reduction 50% and so on. In balance ratio reduction: balRatio > Bal. Ratio Trigger then fixed 25% reduction",
          "V": "100",
          "D": "100",
          "O": null,
          "MIN": 0.0,
          "MAX": 0.0
        },
        {
          "T": 3,
          "ST": -1,
          "G": "Safety",
          "K": "56-56-32-46.05. Reduction Order Type",
          "EK": "56-56-32-46",
          "N": "05. Reduction Order Type",
          "TT": "",
          "V": "Maker or Cancel",
          "D": "Maker or Cancel",
          "O": {
            "-1": "Default",
            "500": "Limit order",
            "501": "Market order",
            "502": "No-Timeout order",
            "503": "Maker or Cancel",
            "504": "Stop limit order",
            "505": "Stop market order",
            "506": "Take profit limit order",
            "507": "Take profit market order",
            "508": "Trailing stop market order"
          },
          "MIN": 0.0,
          "MAX": 0.0
        },
        {
          "T": 0,
          "ST": -1,
          "G": "Safety",
          "K": "57-57-26-31.06. Profit Hodl %",
          "EK": "57-57-26-31",
          "N": "06. Profit Hodl %",
          "TT": "% of the bot profit taken out or not compounded into trading balance calculation",
          "V": "100",
          "D": "100",
          "O": null,
          "MIN": 0.0,
          "MAX": 0.0
        },
        {
          "T": 2,
          "ST": -1,
          "G": "Safety",
          "K": "58-58-28-33.07. Dynamic Hodl",
          "EK": "58-58-28-33",
          "N": "07. Dynamic Hodl",
          "TT": "After in profit will only take out profit if current profit < 80% of highest profit recorded.",
          "V": "False",
          "D": "False",
          "O": null,
          "MIN": 0.0,
          "MAX": 0.0
        },
        {
          "T": 0,
          "ST": -1,
          "G": "Safety",
          "K": "59-59-22-27.08. SL Delay (Min)",
          "EK": "59-59-22-27",
          "N": "08. SL Delay (Min)",
          "TT": "Stop the bot from opening new long/short order for X minutes after close at loss.",
          "V": "0",
          "D": "0",
          "O": null,
          "MIN": 0.0,
          "MAX": 0.0
        },
        {
          "T": 10,
          "ST": -1,
          "G": "Order",
          "K": "61-61-4-20.Order",
          "EK": "61-61-4-20",
          "N": "Order",
          "TT": "",
          "V": "",
          "D": "",
          "O": null,
          "MIN": 0.0,
          "MAX": 0.0
        },
        {
          "T": 0,
          "ST": -1,
          "G": "Order",
          "K": "62-62-27-32.01. Orders Count",
          "EK": "62-62-27-32",
          "N": "01. Orders Count",
          "TT": "How many total filled orders are allowed for DCA.",
          "V": "1",
          "D": "1",
          "O": null,
          "MIN": 0.0,
          "MAX": 0.0
        },
        {
          "T": 0,
          "ST": -1,
          "G": "Order",
          "K": "63-63-27-32.02. Risk % per order",
          "EK": "63-63-27-32",
          "N": "02. Risk % per order",
          "TT": "1 = risk losing ~1% of trading balance PER ORDER if SL hit from current order price. Total risk PER POSITION = order count * risk.",
          "V": "1",
          "D": "1",
          "O": null,
          "MIN": 0.0,
          "MAX": 0.0
        },
        {
          "T": 0,
          "ST": -1,
          "G": "Order",
          "K": "64-64-30-35.02A. Fix Orders Distance %",
          "EK": "64-64-30-35",
          "N": "02A. Fix Orders Distance %",
          "TT": "Minimum % price distance from filled order to the next.",
          "V": "0",
          "D": "0",
          "O": null,
          "MIN": 0.0,
          "MAX": 0.0
        },
        {
          "T": 2,
          "ST": -1,
          "G": "Order",
          "K": "65-65-28-33.02B. Dynamic Order Distance %",
          "EK": "65-65-28-33",
          "N": "02B. Dynamic Order Distance %",
          "TT": "Auto calculate order distance. If ticked will ignore Order Distance value",
          "V": "True",
          "D": "True",
          "O": null,
          "MIN": 0.0,
          "MAX": 0.0
        },
        {
          "T": 0,
          "ST": -1,
          "G": "Order",
          "K": "66-66-26-31.03A. Min. Order Size ",
          "EK": "66-66-26-31",
          "N": "03A. Min. Order Size ",
          "TT": "Minimum order size if Dynamic Slot Size activated. Static amount if Dynamic Slot Size disabled.",
          "V": "0",
          "D": "0",
          "O": null,
          "MIN": 0.0,
          "MAX": 0.0
        },
        {
          "T": 2,
          "ST": -1,
          "G": "Order",
          "K": "67-67-25-30.03B. Dynamic Order Size",
          "EK": "67-67-25-30",
          "N": "03B. Dynamic Order Size",
          "TT": "Dynamically change order size. Calculated based on distance to SL price.",
          "V": "True",
          "D": "True",
          "O": null,
          "MIN": 0.0,
          "MAX": 0.0
        },
        {
          "T": 10,
          "ST": -1,
          "G": "Profit",
          "K": "69-69-4-20.Profit",
          "EK": "69-69-4-20",
          "N": "Profit",
          "TT": "",
          "V": "",
          "D": "",
          "O": null,
          "MIN": 0.0,
          "MAX": 0.0
        },
        {
          "T": 0,
          "ST": -1,
          "G": "Profit",
          "K": "70-70-19-24.01. Reward to Risk",
          "EK": "70-70-19-24",
          "N": "01. Reward to Risk",
          "TT": "Reward to risk ratio. 2 = reward 2x risk. At this level bot will close position.",
          "V": "3",
          "D": "3",
          "O": null,
          "MIN": 0.0,
          "MAX": 0.0
        },
        {
          "T": 0,
          "ST": -1,
          "G": "Profit",
          "K": "71-71-26-31.02. Halving %",
          "EK": "71-71-26-31",
          "N": "02. Halving %",
          "TT": "% of profit price change to start halving size at doubling rate. 0 is disable. If 1 = 1st at 1%, 2nd when 2% and so on.",
          "V": "0",
          "D": "0",
          "O": null,
          "MIN": 0.0,
          "MAX": 0.0
        },
        {
          "T": 3,
          "ST": -1,
          "G": "Profit",
          "K": "72-72-28-42.03. TP Order Type",
          "EK": "72-72-28-42",
          "N": "03. TP Order Type",
          "TT": "",
          "V": "Maker or Cancel",
          "D": "Maker or Cancel",
          "O": {
            "-1": "Default",
            "500": "Limit order",
            "501": "Market order",
            "502": "No-Timeout order",
            "503": "Maker or Cancel",
            "504": "Stop limit order",
            "505": "Stop market order",
            "506": "Take profit limit order",
            "507": "Take profit market order",
            "508": "Trailing stop market order"
          },
          "MIN": 0.0,
          "MAX": 0.0
        }
      ],
      "O": 500,
      "HT": true,
      "HO": true,
      "SS": false,
      "MS": true,
      "LS": true,
      "MT": false,
      "OD": false,
      "MM": false,
      "RSB": false,
      "TAU": false
    },
    "UID": "02f3cd9afebb46bf9d4c9b6ef5e6e823",
    "SID": "c8dcbe2231d14604837d336cb8ba8b5d",
    "SN": "Smokybot MK3",
    "SD": "",
    "ST": 0,
    "SS": 0,
    "CN": "",
    "IC": false,
    "IV": true,
    "CU": 1765218832,
    "UU": 1765219019,
    "FID": -1
  }
}
