{
  "Success": true,
  "Error": "",
  "Data": {
    "SC": "DefineCommand('SuperTrendExt', 'SuperTrend indicator (extended) by pshai.')\n \n-- Parameters\nlocal h = DefineParameter(ListNumberType, 'high', 'High prices', true, HighPrices())\nlocal l = DefineParameter(ListNumberType, 'low', 'Low prices', true, LowPrices())\nlocal c = DefineParameter(ListNumberType, 'close', 'Close prices', true, ClosePrices())\nlocal src = DefineParameter(ListNumberType, 'source', 'Source prices', true, ClosePrices())\nlocal atrPeriod = DefineParameter(NumberType, 'atrPeriod', 'ATR period length', true, 22)\nlocal atrMult = DefineParameter(NumberType, 'atrMult', 'ATR multiplier', true, 3)\nlocal priceCut = DefineParameter(BooleanType, 'priceCut', 'If true, price (H, L and C) will be the ones flipping ST line. If false, the source will work as the flipper.', false, false)\nlocal wicks = DefineParameter(BooleanType, 'wicks', 'Take wicks into account or not', false, false)\nlocal id = DefineParameter(StringType, 'id', 'Optional unique id', false, '')\n \n-- Data\nlocal hl = src --(h + l) / 2\nlocal atr = ATR(h, l, c, atrPeriod) * atrMult\n \n-- Stuff\nlocal dir = Load('dir'..id, 0)\nlocal result\n \nlocal run = function(offset)\n    if offset == nil then\n        offset = 1\n    end\n \n    -- define which direction to start\n    if dir == 0 then\n        local start = Load('start'..id, offset)\n        local upper = ArrayGet(hl, start) + ArrayGet(atr, start)\n        local lower = ArrayGet(hl, start) - ArrayGet(atr, start)\n \n        if c[offset] > upper then\n            dir = 1\n        elseif c[offset] < lower then\n            dir = -1\n        end\n \n        result = hl[start]\n \n    -- Update short side\n    elseif dir == -1 then\n        local upper = ArrayGet(hl, offset) + ArrayGet(atr, offset)\n        local upperPrev = Load('upper'..id, upper) -- load previous\n        local finalUpper = Min(upper, upperPrev) -- take min\n \n        -- if close/high/src cuts through upper, we switch to other side\n        local flip = priceCut\n                and ((c[offset] >= finalUpper) or (wicks and h[offset] >= finalUpper))\n                or (hl[offset] >= finalUpper)\n \n        if flip then\n            dir = 1\n            Save('lower'..id, ArrayGet(hl, offset) - ArrayGet(atr, offset)) -- \"reset\" lower line\n        end\n \n        Save('upper'..id, finalUpper)\n        result = finalUpper -- set result\n \n    -- update long side\n    elseif dir == 1 then\n        local lower = ArrayGet(hl, offset) - ArrayGet(atr, offset)\n        local lowerPrev = Load('lower'..id, lower) -- load previous\n        local finalLower = Max(lower, lowerPrev) -- take max\n \n        -- if close/high/src cuts through lower, we switch to other side\n        local flip = priceCut\n                and (c[offset] <= finalLower or (wicks and l[offset] <= finalLower))\n                or (hl[offset] <= finalLower)\n \n        if flip then\n            dir = -1\n            Save('upper'..id, ArrayGet(hl, offset) + ArrayGet(atr, offset)) -- \"reset\" upper line\n        end\n \n        Save('lower'..id, finalLower)\n        result = finalLower -- set result\n    end\nend\n \n-- Warmup\nif Load('warmup'..id) == nil then\n    LogWarning('Warming up SuperTrend...')\n \n    local wm_len = ArrayGet(Min(500, #src, #c, #atr), 1)\n \n    for i=wm_len, 1, -1 do\n        run(i)\n    end\n \n    LogWarning('Warmup completed.')\n \n    Save('warmup'..id, false)\nelse\n    run() -- only update current step\nend\n \nSave('dir'..id, dir)\n \nDefineOutput(ListNumberType, result, 'SuperTrend output values')",
    "CR": {
      "IV": true,
      "C": {
        "CN": "SuperTrendExt",
        "CD": "SuperTrend indicator (extended) by pshai.",
        "MC": false,
        "US": false,
        "UL": false,
        "OH": false,
        "P": [
          {
            "Index": 0,
            "Name": "high",
            "Type": 7,
            "IsRequired": true,
            "IsHidden": false,
            "IsField": false,
            "AllowNull": false,
            "Description": "High prices",
            "ScriptType": null,
            "Suggestion": []
          },
          {
            "Index": 0,
            "Name": "low",
            "Type": 7,
            "IsRequired": true,
            "IsHidden": false,
            "IsField": false,
            "AllowNull": false,
            "Description": "Low prices",
            "ScriptType": null,
            "Suggestion": []
          },
          {
            "Index": 0,
            "Name": "close",
            "Type": 7,
            "IsRequired": true,
            "IsHidden": false,
            "IsField": false,
            "AllowNull": false,
            "Description": "Close prices",
            "ScriptType": null,
            "Suggestion": []
          },
          {
            "Index": 0,
            "Name": "source",
            "Type": 7,
            "IsRequired": true,
            "IsHidden": false,
            "IsField": false,
            "AllowNull": false,
            "Description": "Source prices",
            "ScriptType": null,
            "Suggestion": []
          },
          {
            "Index": 0,
            "Name": "atrPeriod",
            "Type": 1,
            "IsRequired": true,
            "IsHidden": false,
            "IsField": false,
            "AllowNull": false,
            "Description": "ATR period length",
            "ScriptType": null,
            "Suggestion": [
              3400,
              4403,
              4205
            ]
          },
          {
            "Index": 0,
            "Name": "atrMult",
            "Type": 1,
            "IsRequired": true,
            "IsHidden": false,
            "IsField": false,
            "AllowNull": false,
            "Description": "ATR multiplier",
            "ScriptType": null,
            "Suggestion": [
              3400,
              4403,
              4205
            ]
          },
          {
            "Index": 0,
            "Name": "priceCut",
            "Type": 3,
            "IsRequired": false,
            "IsHidden": false,
            "IsField": false,
            "AllowNull": true,
            "Description": "If true, price (H, L and C) will be the ones flipping ST line. If false, the source will work as the flipper.",
            "ScriptType": null,
            "Suggestion": [
              3212,
              3210,
              3203,
              3206,
              3211,
              3300,
              3202,
              3205,
              3209,
              3204,
              4803,
              4804,
              4805,
              7204
            ]
          },
          {
            "Index": 0,
            "Name": "wicks",
            "Type": 3,
            "IsRequired": false,
            "IsHidden": false,
            "IsField": false,
            "AllowNull": true,
            "Description": "Take wicks into account or not",
            "ScriptType": null,
            "Suggestion": [
              3212,
              3210,
              3203,
              3206,
              3211,
              3300,
              3202,
              3205,
              3209,
              3204,
              4803,
              4804,
              4805,
              7204
            ]
          },
          {
            "Index": 0,
            "Name": "id",
            "Type": 0,
            "IsRequired": false,
            "IsHidden": false,
            "IsField": false,
            "AllowNull": true,
            "Description": "Optional unique id",
            "ScriptType": null,
            "Suggestion": [
              4406,
              3400,
              4205,
              4200
            ]
          }
        ],
        "O": {
          "Index": 0,
          "Name": "result",
          "Type": 7,
          "IsRequired": false,
          "IsHidden": false,
          "IsField": false,
          "AllowNull": false,
          "Description": "SuperTrend output values",
          "ScriptType": null,
          "Suggestion": []
        },
        "OI": []
      },
      "CR": [],
      "CL": [
        "1765218985 ||| 0 ||| Compiling script...",
        "1765218985 ||| 0 ||| TIP: You might want to draw a chart combined with your strategy. You can do this by using one of the command in the Charting category.",
        "1765218985 ||| 0 ||| TIP: Using OptimizedForInterval() in combination with the technical analysis commands will improve the backtest speed.",
        "1765218985 ||| 0 ||| Field high found.",
        "1765218985 ||| 0 ||| Field low found.",
        "1765218985 ||| 0 ||| Field close found.",
        "1765218985 ||| 0 ||| Field source found.",
        "1765218985 ||| 0 ||| Field atrPeriod found.",
        "1765218985 ||| 0 ||| Field atrMult found.",
        "1765218985 ||| 0 ||| Field priceCut found.",
        "1765218985 ||| 0 ||| Field wicks found.",
        "1765218985 ||| 0 ||| Field id found.",
        "1765218985 ||| 2 ||| WARNING: Warming up SuperTrend...",
        "1765218985 ||| 2 ||| WARNING: Warmup completed.",
        "1765218985 ||| 0 ||| Output found. Type: ListNumbers. Result: (UserData)",
        "1765218985 ||| 0 ||| Compile test OK."
      ],
      "LCE": [],
      "VCE": [],
      "I": [],
      "O": 500,
      "HT": false,
      "HO": false,
      "SS": false,
      "MS": false,
      "LS": false,
      "MT": false,
      "OD": false,
      "MM": false,
      "RSB": false,
      "TAU": false
    },
    "UID": "02f3cd9afebb46bf9d4c9b6ef5e6e823",
    "SID": "63c243f503214cd4b1e3dfe4140c2b8d",
    "SN": "[pshaiCmd] SuperTrend Extended (UPDATED)",
    "SD": "",
    "ST": 0,
    "SS": 0,
    "CN": "SuperTrendExt",
    "IC": true,
    "IV": true,
    "CU": 1765218964,
    "UU": 1765218988,
    "FID": -1
  }
}
