{
  "Success": true,
  "Error": "",
  "Data": {
    "SC": "DefineCommand('VWAP', 'Volume Weighted Average Price')\n \nlocal interval = DefineParameter(NumberType, 'interval', 'Interval for the price data. Set this to zero to use [Main Interval] setting.', false, 0, 'InputInterval, Number')\nlocal resetInterval = DefineParameter(NumberType, 'resetInterval', 'Interval in minutes for resetting the cumulative values. If this value is zero, reset function is ignored.', false, 0, 'InputInterval, Input, Number')\n \nDefineIntervalOptimization(interval)\n \nlocal roundTime = function(time, span)\n    return time - (time % (span * 60))\nend\n \nlocal checkReset = function(isInit, ttime)\n    local time = roundTime(not ttime and Time() or ttime, resetInterval)\n    \n    if isInit then\n        Save('rt', time)\n    elseif time > Load('rt', time) then\n        Save('rt', time)\n        return true\n    end\n    return false\nend\n \nlocal dataLimit = 250\nlocal hlc = HLCPrices(interval)\nlocal v = GetVolume(interval)\n \nlocal cumTyp = Load('ct', 0)\nlocal cumVol = Load('cv', 0)\nlocal result = Load('r', {})\n \nif Load('init') == nil then\n    LogWarning('Running a warmup for VWAP...')\n    \n    local len = #hlc\n    local time_step = CurrentInterval() * 60\n    local time = Time() - (len * time_step)\n    local res = 0\n \n    checkReset(true) -- initialize\n    \n    for i=len, 1, -1 do\n        local p = ArrayGet(hlc, i)\n        local vol = ArrayGet(v, i)\n        \n        if checkReset(false, time) then\n            cumTyp = 0\n            cumVol = 0\n        else\n            cumTyp = cumTyp + p * vol\n            cumVol = cumVol + vol\n        end\n \n        if cumVol > 0 then\n            res = ArrayUnshift(result, cumTyp / cumVol)\n        else\n            res = ArrayUnshift(result, p)\n        end\n \n        result = res\n        time = time + time_step\n    end\n \n    \n    Save('init', false)\nelse\n    local p = ArrayGet(hlc, 1)\n    local vol = ArrayGet(v, 1)\n \n    if checkReset() then\n        cumTyp = 0\n        cumVol = 0\n    end\n    \n    cumTyp = cumTyp + p * vol\n    cumVol = cumVol + vol\n \n    if cumVol > 0 then\n        result = ArrayUnshift(result, cumTyp / cumVol)\n    else\n        result = ArrayUnshift(result, p)\n    end\nend\n \nif #result > dataLimit then\n    result = Grab(result, 0, dataLimit)\nend\n \n \nSave('ct', cumTyp)\nSave('cv', cumVol)\nSave('r', result)\n \nDefineOutput(ListNumberType, result, 'Array containing VWAP values.', 'Plot')",
    "CR": {
      "IV": true,
      "C": {
        "CN": "VWAP",
        "CD": "Volume Weighted Average Price",
        "MC": false,
        "US": false,
        "UL": false,
        "OH": false,
        "P": [
          {
            "Index": 0,
            "Name": "interval",
            "Type": 1,
            "IsRequired": false,
            "IsHidden": false,
            "IsField": false,
            "AllowNull": true,
            "Description": "Interval for the price data. Set this to zero to use [Main Interval] setting.",
            "ScriptType": null,
            "Suggestion": [
              3404,
              4403
            ]
          },
          {
            "Index": 0,
            "Name": "resetInterval",
            "Type": 1,
            "IsRequired": false,
            "IsHidden": false,
            "IsField": false,
            "AllowNull": true,
            "Description": "Interval in minutes for resetting the cumulative values. If this value is zero, reset function is ignored.",
            "ScriptType": null,
            "Suggestion": [
              3404,
              3400,
              3401,
              3402,
              3423,
              3413,
              3420,
              3414,
              3405,
              3406,
              3407,
              3408,
              3409,
              3410,
              3411,
              3422,
              3418,
              3424,
              3415,
              3417,
              3419,
              3416,
              3600,
              3601,
              3602,
              3603,
              3604,
              3605,
              4403
            ]
          }
        ],
        "O": {
          "Index": 0,
          "Name": "result",
          "Type": 7,
          "IsRequired": false,
          "IsHidden": false,
          "IsField": false,
          "AllowNull": false,
          "Description": "Array containing VWAP values.",
          "ScriptType": null,
          "Suggestion": [
            408
          ]
        },
        "OI": []
      },
      "CR": [],
      "CL": [
        "1754586053 ||| 0 ||| Compiling script...",
        "1754586053 ||| 0 ||| Field interval found.",
        "1754586053 ||| 0 ||| DefineParameter(): Input parameter suggestion added: InputInterval",
        "1754586053 ||| 0 ||| DefineParameter(): Input parameter suggestion added: Number",
        "1754586053 ||| 0 ||| Field resetInterval found.",
        "1754586053 ||| 0 ||| DefineParameter(): Input parameter suggestion added: InputInterval",
        "1754586053 ||| 0 ||| DefineParameter(): Input parameter suggestion added: Input",
        "1754586053 ||| 0 ||| DefineParameter(): Output suggestion added: InputAccount",
        "1754586053 ||| 0 ||| DefineParameter(): Output suggestion added: InputAccountMarket",
        "1754586053 ||| 0 ||| DefineParameter(): Output suggestion added: InputButton",
        "1754586053 ||| 0 ||| DefineParameter(): Output suggestion added: InputCdlTypes",
        "1754586053 ||| 0 ||| DefineParameter(): Output suggestion added: InputConstant",
        "1754586053 ||| 0 ||| DefineParameter(): Output suggestion added: InputGroupHeader",
        "1754586053 ||| 0 ||| DefineParameter(): Output suggestion added: InputLrTypes",
        "1754586053 ||| 0 ||| DefineParameter(): Output suggestion added: InputMarket",
        "1754586053 ||| 0 ||| DefineParameter(): Output suggestion added: InputMaTypes",
        "1754586053 ||| 0 ||| DefineParameter(): Output suggestion added: InputOptions",
        "1754586053 ||| 0 ||| DefineParameter(): Output suggestion added: InputOrderType",
        "1754586053 ||| 0 ||| DefineParameter(): Output suggestion added: InputPriceSource",
        "1754586053 ||| 0 ||| DefineParameter(): Output suggestion added: InputPriceSourceMarket",
        "1754586053 ||| 0 ||| DefineParameter(): Output suggestion added: InputSignalManagement",
        "1754586053 ||| 0 ||| DefineParameter(): Output suggestion added: InputSignalTypes",
        "1754586053 ||| 0 ||| DefineParameter(): Output suggestion added: InputSourcePrice",
        "1754586053 ||| 0 ||| DefineParameter(): Output suggestion added: InputTable",
        "1754586053 ||| 0 ||| DefineParameter(): Output suggestion added: InputTableColumn",
        "1754586053 ||| 0 ||| DefineParameter(): Output suggestion added: InputTableColumnDropdown",
        "1754586053 ||| 0 ||| DefineParameter(): Output suggestion added: InputTableOptions",
        "1754586053 ||| 0 ||| DefineParameter(): Output suggestion added: AccountGuid",
        "1754586053 ||| 0 ||| DefineParameter(): Output suggestion added: CurrentInterval",
        "1754586053 ||| 0 ||| DefineParameter(): Output suggestion added: Fee",
        "1754586053 ||| 0 ||| DefineParameter(): Output suggestion added: Leverage",
        "1754586053 ||| 0 ||| DefineParameter(): Output suggestion added: PriceMarket",
        "1754586053 ||| 0 ||| DefineParameter(): Output suggestion added: TradeAmount",
        "1754586053 ||| 0 ||| DefineParameter(): Input parameter suggestion added: Number",
        "1754586053 ||| 2 ||| WARNING: Running a warmup for VWAP...",
        "1754586053 ||| 0 ||| Output found. Type: ListNumbers. Result: (Table)",
        "1754586053 ||| 0 ||| DefineOutput(): Output suggestion added: Plot",
        "1754586053 ||| 0 ||| Compile test OK."
      ],
      "LCE": [],
      "VCE": [],
      "I": [],
      "O": 500,
      "HT": false,
      "HO": false,
      "SS": false,
      "MS": false,
      "LS": false,
      "MT": false,
      "OD": false,
      "MM": false,
      "RSB": false,
      "TAU": false
    },
    "UID": "02f3cd9afebb46bf9d4c9b6ef5e6e823",
    "SID": "be17b9fba7a24f3c94398eecd2dfb01b",
    "SN": "[pshaiCmd] Volume Weighted Average Price (VWAP)",
    "SD": "",
    "ST": 0,
    "SS": 0,
    "CN": "VWAP",
    "IC": true,
    "IV": true,
    "CU": 1754405750,
    "UU": 1754586056,
    "FID": -1
  }
}
