{
  "Success": true,
  "Error": "",
  "Data": {
    "SC": "-- [pshaiBot] YATS Bot\n-- Yet Another Trend Scalper Bot, created by pshai (c) 2020\n-- If you like what I'm doing, you can support me:\n--   BTC: 3EsfrqARW7iPVKjZz6WgkMTrtw6SgJUUdV\n--   ETH: 0x6b5120bdaf7cdfa523ecc0209b0c67cd67dd2140\n--------------------------------\n-- If you have any feedback or need help (with my scripts)...\n-- ...you know where to find me.\n--------------------------------\n-- ~May the profits be with you~\n \n \n \n-- script settings\n    EnableHighSpeedUpdates(true)\n    HideOrderSettings()\n \n-- trading commands\n    local isSpot = MarketType() == SpotTrading\n    local long_entry_cmd = isSpot and PlaceBuyOrder or PlaceGoLongOrder\n    local long_exit_cmd = isSpot and PlaceSellOrder or PlaceExitLongOrder\n    local short_entry_cmd = isSpot and PlaceSellOrder or PlaceGoShortOrder\n    local short_exit_cmd = isSpot and PlaceBuyOrder or PlaceExitShortOrder\n \n-- inputs\n    local tf1 = InputInterval('1. Timeframe (Entry)', 5, 'Timeframe for StochRSI()', 'Intervals')\n    local tf2 = InputInterval('2. Timeframe (Momentum)', 15, 'Timeframe for MOM()', 'Intervals')\n    local tf3 = InputInterval('3. Timeframe (Trend)', 45, 'Timeframe for ADX(), ATR() and MA()s', 'Intervals')\n \n    local period_adx = Input('1. ADX Length', 14, '', 'Period Lengths')\n    local period_atr = Input('2. ATR Length', 14, '', 'Period Lengths')\n    local period_ma1 = Input('3. MA1 Length', 10, '', 'Period Lengths')\n    local period_ma2 = Input('4. MA2 Length', 36, '', 'Period Lengths')\n    local period_mom = Input('5. MOM Length', 100, '', 'Period Lengths')\n    local period_moms = Input('6. MOM Smooth', 9, '', 'Period Lengths')\n    local period_rsi = Input('7. RSI Length', 9, '', 'Period Lengths')\n    local period_stoch = Input('8. STOCH Length', 7, '', 'Period Lengths')\n    local period_smk = Input('9. Smooth %K Length', 5, '', 'Period Lengths')\n    local period_smd = Input('10. Smooth %D Length', 2, '', 'Period Lengths')\n \n    local stoch_ob = Input('1. Short Overbought', 80, '', 'Levels')\n    local stoch_os = Input('2. Long Oversold', 20, '', 'Levels')\n    local adx_limit = Input('3. ADX Limit', 0, 'If ADX is below this level, the bot will not trade!', 'Levels')\n \n    local ma_type1 = InputMaTypes('1. MA1 Type', EmaType, '', 'MA Types')\n    local ma_type2 = InputMaTypes('2. MA2 Type', EmaType, '', 'MA Types')\n \n    local sl_prc = Input('StopLoss %', 0.5)\n \n-- data\n    local h = {\n        tf1 = HighPrices(tf1),\n        tf2 = HighPrices(tf2),\n        tf3 = HighPrices(tf3)\n        }\n \n    local l = {\n        tf1 = LowPrices(tf1),\n        tf2 = LowPrices(tf2),\n        tf3 = LowPrices(tf3)\n        }\n \n    local c = {\n        tf1 = ClosePrices(tf1),\n        tf2 = ClosePrices(tf2),\n        tf3 = ClosePrices(tf3)\n        }\n \n    local cp = CurrentPrice()\n    local adx = ADX(h.tf3, l.tf3, c.tf3, period_adx)\n    local atr = ATR(h.tf3, l.tf3, c.tf3, period_atr)\n    local ma1 = MA(c.tf3, period_ma1, ma_type1)\n    local ma2 = MA(c.tf3, period_ma2, ma_type2)\n    local mom = EMA(MOM(c.tf2, period_mom), period_moms)\n    local rsi = CC_CC_StorchRSI(period_rsi, period_stoch, period_smk, period_smd, c.tf1)\n \n-- plots\n    Plot(0, 'MA1', ma1)\n    Plot(0, 'MA2', ma2, Purple)\n    Plot(1, 'ADX', adx)\n    PlotHorizontalZone(1, '', Red(10), 0, adx_limit)\n    Plot(2, 'MOM', mom)\n    Plot(3, '%K', rsi.slowK, Yellow)\n    Plot(3, '%D', rsi.slowD, Red)\n    PlotHorizontalLine(3, '', Gray, stoch_os, Dashed)\n    PlotHorizontalLine(3, '', Gray, stoch_ob, Dashed)\n \n-- helpers\n    function canTrade()\n        local time = Load('time', Time())\n \n        return Time() >= time\n    end\n \n    function setTimer(minutes)\n        Save('time', Time() + minutes * 60)\n    end\n \n \n-- da logic\n    local rules = {\n        adx = adx > adx_limit,\n        ma_up = ma1 > ma2,\n        ma_dn = ma1 < ma2,\n        mom_up = mom > 0,\n        mom_dn = mom < 0,\n        entry_up = rsi.slowK < rsi.slowD and rsi.slowK < stoch_os,\n        entry_dn = rsi.slowK > rsi.slowD and rsi.slowK > stoch_ob\n        }\n \n    local xid = Load('xid', '') -- order id for the ideal exit\n    local go_long = rules.adx and rules.ma_up and rules.mom_up and rules.entry_up\n    local go_short = rules.adx and rules.ma_dn and rules.mom_dn and rules.entry_dn\n    local bot_pos = GetPositionDirection()\n \n    if bot_pos == NoPosition and canTrade() then\n        if go_long then\n            long_entry_cmd(cp.close, TradeAmount(), {type=MarketOrderType, note='LE'})\n            xid = long_exit_cmd(cp.close + atr, TradeAmount(), {type=NoTimeOutOrderType, note='LX'})\n \n        elseif go_short then\n            short_entry_cmd(cp.close, TradeAmount(), {type=MarketOrderType, note='SE'})\n            xid = short_exit_cmd(cp.close - atr, TradeAmount(), {type=NoTimeOutOrderType, note='SX'})\n        end\n    else\n        if StopLoss(sl_prc) then\n            if xid != '' and IsOrderOpen(xid) then\n                CancelOrder(xid)\n            end\n \n            SetFee(0.075) -- for backtesting and sim runs\n \n            if bot_pos == PositionLong then\n                long_exit_cmd(cp.close, TradeAmount(), {type=MarketOrderType, note='LX-SL'})\n            elseif bot_pos == PositionShort then\n                short_exit_cmd(cp.close, TradeAmount(), {type=MarketOrderType, note='SX-SL'})\n            end\n \n            setTimer(30) -- cooldown if stoploss\n        end\n    end\n \n-- save\n    Save('xid', xid)",
    "CR": {
      "IV": false,
      "C": null,
      "CR": [
        "CC_StorchRSI"
      ],
      "CL": [
        "1762241994 ||| 0 ||| Compiling script...",
        "1762241994 ||| 0 ||| TIP: Using OptimizedForInterval() in combination with the technical analysis commands will improve the backtest speed.",
        "1762241994 ||| 0 ||| High speed updates enabled.",
        "1762241994 ||| 0 ||| Interval input field 1. Timeframe (Entry) found. (value: 5 min)",
        "1762241994 ||| 0 ||| Interval input field 2. Timeframe (Momentum) found. (value: 15 min)",
        "1762241994 ||| 0 ||| Interval input field 3. Timeframe (Trend) found. (value: 45 min)",
        "1762241994 ||| 0 ||| Registered input '1. ADX Length'",
        "1762241994 ||| 0 ||| Registered input '2. ATR Length'",
        "1762241994 ||| 0 ||| Registered input '3. MA1 Length'",
        "1762241994 ||| 0 ||| Registered input '4. MA2 Length'",
        "1762241994 ||| 0 ||| Registered input '5. MOM Length'",
        "1762241994 ||| 0 ||| Registered input '6. MOM Smooth'",
        "1762241994 ||| 0 ||| Registered input '7. RSI Length'",
        "1762241994 ||| 0 ||| Registered input '8. STOCH Length'",
        "1762241994 ||| 0 ||| Registered input '9. Smooth %K Length'",
        "1762241994 ||| 0 ||| Registered input '10. Smooth %D Length'",
        "1762241994 ||| 0 ||| Registered input '1. Short Overbought'",
        "1762241994 ||| 0 ||| Registered input '2. Long Oversold'",
        "1762241994 ||| 0 ||| Registered input '3. ADX Limit'",
        "1762241994 ||| 0 ||| Registered input '1. MA1 Type'",
        "1762241994 ||| 0 ||| Registered input '2. MA2 Type'",
        "1762241994 ||| 0 ||| Registered input 'StopLoss %'",
        "1762241994 ||| 3 ||| ERROR: attempt to call a nil value at [75-78:4-0]",
        "1762241994 ||| 0 ||| Updated input '1. Timeframe (Entry)' from 5 to 5.",
        "1762241994 ||| 0 ||| Updated input '2. Timeframe (Momentum)' from 15 to 15.",
        "1762241994 ||| 0 ||| Updated input '3. Timeframe (Trend)' from 45 to 45.",
        "1762241994 ||| 0 ||| Updated input '1. ADX Length' from 14 to 14.",
        "1762241994 ||| 0 ||| Updated input '2. ATR Length' from 14 to 14.",
        "1762241994 ||| 0 ||| Updated input '3. MA1 Length' from 10 to 10.",
        "1762241994 ||| 0 ||| Updated input '4. MA2 Length' from 36 to 36.",
        "1762241994 ||| 0 ||| Updated input '5. MOM Length' from 100 to 100.",
        "1762241994 ||| 0 ||| Updated input '6. MOM Smooth' from 9 to 9.",
        "1762241994 ||| 0 ||| Updated input '7. RSI Length' from 9 to 9.",
        "1762241994 ||| 0 ||| Updated input '8. STOCH Length' from 7 to 7.",
        "1762241994 ||| 0 ||| Updated input '9. Smooth %K Length' from 5 to 5.",
        "1762241994 ||| 0 ||| Updated input '10. Smooth %D Length' from 2 to 2.",
        "1762241994 ||| 0 ||| Updated input '1. Short Overbought' from 80 to 80.",
        "1762241994 ||| 0 ||| Updated input '2. Long Oversold' from 20 to 20.",
        "1762241994 ||| 0 ||| Updated input '3. ADX Limit' from 0 to 0.",
        "1762241994 ||| 0 ||| Updated input 'StopLoss %' from 0.5 to 0.5."
      ],
      "LCE": [
        {
          "ErrorMessage": "'attempt to call a nil value' at[75-78:4-0]",
          "FromLine": 75,
          "ToLine": 78,
          "FromColumn": 4,
          "ToColumn": 0
        },
        {
          "ErrorMessage": "",
          "FromLine": 75,
          "ToLine": 78,
          "FromColumn": 4,
          "ToColumn": 0
        }
      ],
      "VCE": [],
      "I": [
        {
          "T": 9,
          "ST": -1,
          "G": "Intervals",
          "K": "26-26-16-29.1. Timeframe (Entry)",
          "EK": "26-26-16-29",
          "N": "1. Timeframe (Entry)",
          "TT": "Timeframe for StochRSI()",
          "V": "5",
          "D": "5",
          "O": null,
          "MIN": 0.0,
          "MAX": 0.0
        },
        {
          "T": 9,
          "ST": -1,
          "G": "Intervals",
          "K": "27-27-16-29.2. Timeframe (Momentum)",
          "EK": "27-27-16-29",
          "N": "2. Timeframe (Momentum)",
          "TT": "Timeframe for MOM()",
          "V": "15",
          "D": "15",
          "O": null,
          "MIN": 0.0,
          "MAX": 0.0
        },
        {
          "T": 9,
          "ST": -1,
          "G": "Intervals",
          "K": "28-28-16-29.3. Timeframe (Trend)",
          "EK": "28-28-16-29",
          "N": "3. Timeframe (Trend)",
          "TT": "Timeframe for ADX(), ATR() and MA()s",
          "V": "45",
          "D": "45",
          "O": null,
          "MIN": 0.0,
          "MAX": 0.0
        },
        {
          "T": 0,
          "ST": -1,
          "G": "Period Lengths",
          "K": "30-30-23-28.1. ADX Length",
          "EK": "30-30-23-28",
          "N": "1. ADX Length",
          "TT": "",
          "V": "14",
          "D": "14",
          "O": null,
          "MIN": 0.0,
          "MAX": 0.0
        },
        {
          "T": 0,
          "ST": -1,
          "G": "Period Lengths",
          "K": "31-31-23-28.2. ATR Length",
          "EK": "31-31-23-28",
          "N": "2. ATR Length",
          "TT": "",
          "V": "14",
          "D": "14",
          "O": null,
          "MIN": 0.0,
          "MAX": 0.0
        },
        {
          "T": 0,
          "ST": -1,
          "G": "Period Lengths",
          "K": "32-32-23-28.3. MA1 Length",
          "EK": "32-32-23-28",
          "N": "3. MA1 Length",
          "TT": "",
          "V": "10",
          "D": "10",
          "O": null,
          "MIN": 0.0,
          "MAX": 0.0
        },
        {
          "T": 0,
          "ST": -1,
          "G": "Period Lengths",
          "K": "33-33-23-28.4. MA2 Length",
          "EK": "33-33-23-28",
          "N": "4. MA2 Length",
          "TT": "",
          "V": "36",
          "D": "36",
          "O": null,
          "MIN": 0.0,
          "MAX": 0.0
        },
        {
          "T": 0,
          "ST": -1,
          "G": "Period Lengths",
          "K": "34-34-23-28.5. MOM Length",
          "EK": "34-34-23-28",
          "N": "5. MOM Length",
          "TT": "",
          "V": "100",
          "D": "100",
          "O": null,
          "MIN": 0.0,
          "MAX": 0.0
        },
        {
          "T": 0,
          "ST": -1,
          "G": "Period Lengths",
          "K": "35-35-24-29.6. MOM Smooth",
          "EK": "35-35-24-29",
          "N": "6. MOM Smooth",
          "TT": "",
          "V": "9",
          "D": "9",
          "O": null,
          "MIN": 0.0,
          "MAX": 0.0
        },
        {
          "T": 0,
          "ST": -1,
          "G": "Period Lengths",
          "K": "36-36-23-28.7. RSI Length",
          "EK": "36-36-23-28",
          "N": "7. RSI Length",
          "TT": "",
          "V": "9",
          "D": "9",
          "O": null,
          "MIN": 0.0,
          "MAX": 0.0
        },
        {
          "T": 0,
          "ST": -1,
          "G": "Period Lengths",
          "K": "37-37-25-30.8. STOCH Length",
          "EK": "37-37-25-30",
          "N": "8. STOCH Length",
          "TT": "",
          "V": "7",
          "D": "7",
          "O": null,
          "MIN": 0.0,
          "MAX": 0.0
        },
        {
          "T": 0,
          "ST": -1,
          "G": "Period Lengths",
          "K": "38-38-23-28.9. Smooth %K Length",
          "EK": "38-38-23-28",
          "N": "9. Smooth %K Length",
          "TT": "",
          "V": "5",
          "D": "5",
          "O": null,
          "MIN": 0.0,
          "MAX": 0.0
        },
        {
          "T": 0,
          "ST": -1,
          "G": "Period Lengths",
          "K": "39-39-23-28.10. Smooth %D Length",
          "EK": "39-39-23-28",
          "N": "10. Smooth %D Length",
          "TT": "",
          "V": "2",
          "D": "2",
          "O": null,
          "MIN": 0.0,
          "MAX": 0.0
        },
        {
          "T": 0,
          "ST": -1,
          "G": "Levels",
          "K": "41-41-21-26.1. Short Overbought",
          "EK": "41-41-21-26",
          "N": "1. Short Overbought",
          "TT": "",
          "V": "80",
          "D": "80",
          "O": null,
          "MIN": 0.0,
          "MAX": 0.0
        },
        {
          "T": 0,
          "ST": -1,
          "G": "Levels",
          "K": "42-42-21-26.2. Long Oversold",
          "EK": "42-42-21-26",
          "N": "2. Long Oversold",
          "TT": "",
          "V": "20",
          "D": "20",
          "O": null,
          "MIN": 0.0,
          "MAX": 0.0
        },
        {
          "T": 0,
          "ST": -1,
          "G": "Levels",
          "K": "43-43-22-27.3. ADX Limit",
          "EK": "43-43-22-27",
          "N": "3. ADX Limit",
          "TT": "If ADX is below this level, the bot will not trade!",
          "V": "0",
          "D": "0",
          "O": null,
          "MIN": 0.0,
          "MAX": 0.0
        },
        {
          "T": 3,
          "ST": -1,
          "G": "MA Types",
          "K": "45-45-21-33.1. MA1 Type",
          "EK": "45-45-21-33",
          "N": "1. MA1 Type",
          "TT": "",
          "V": "Ema",
          "D": "Ema",
          "O": {
            "Sma": "Sma",
            "Ema": "Ema",
            "Wma": "Wma",
            "Dema": "Dema",
            "Tema": "Tema",
            "Trima": "Trima",
            "Kama": "Kama",
            "Mama": "Mama",
            "T3": "T3"
          },
          "MIN": 0.0,
          "MAX": 0.0
        },
        {
          "T": 3,
          "ST": -1,
          "G": "MA Types",
          "K": "46-46-21-33.2. MA2 Type",
          "EK": "46-46-21-33",
          "N": "2. MA2 Type",
          "TT": "",
          "V": "Ema",
          "D": "Ema",
          "O": {
            "Sma": "Sma",
            "Ema": "Ema",
            "Wma": "Wma",
            "Dema": "Dema",
            "Tema": "Tema",
            "Trima": "Trima",
            "Kama": "Kama",
            "Mama": "Mama",
            "T3": "T3"
          },
          "MIN": 0.0,
          "MAX": 0.0
        },
        {
          "T": 0,
          "ST": -1,
          "G": "",
          "K": "48-48-19-24.StopLoss %",
          "EK": "48-48-19-24",
          "N": "StopLoss %",
          "TT": "",
          "V": "0.5",
          "D": "0.5",
          "O": null,
          "MIN": 0.0,
          "MAX": 0.0
        }
      ],
      "O": 500,
      "HT": false,
      "HO": true,
      "SS": true,
      "MS": true,
      "LS": true,
      "MT": false,
      "OD": false,
      "MM": false,
      "RSB": false,
      "TAU": false
    },
    "UID": "02f3cd9afebb46bf9d4c9b6ef5e6e823",
    "SID": "3fd8bff29c3347ffa72576ede717a13e",
    "SN": "YATS bot",
    "SD": "",
    "ST": 0,
    "SS": 0,
    "CN": "",
    "IC": false,
    "IV": false,
    "CU": 1752256588,
    "UU": 1762241995,
    "FID": -1
  }
}
