"""
Enumerations for pyHaasAPI v2
Auto-generated from haas_staging definitions.
"""

from enum import Enum

class ArrayFilterTypesEnum(str, Enum):
    ARRAYFILTEREXCLUSIVETYPE = "ArrayFilterExclusiveType"
    ARRAYFILTERGREATERTHANTYPE = "ArrayFilterGreaterThanType"
    ARRAYFILTERINCLUSIVETYPE = "ArrayFilterInclusiveType"
    ARRAYFILTERLESSTHANTYPE = "ArrayFilterLessThanType"

class CandlePatternEnum(str, Enum):
    ABANDONEDBABYTYPE = "AbandonedBabyType"
    ADVANCEBLOCKTYPE = "AdvanceBlockType"
    BELTHOLDTYPE = "BeltHoldType"
    BREAKAWAYTYPE = "BreakawayType"
    CLOSINGMARUBOZUTYPE = "ClosingMarubozuType"
    CONCEALBABYSWALLTYPE = "ConcealBabysWallType"
    COUNTERATTACKTYPE = "CounterAttackType"
    DARKCLOUDCOVERTYPE = "DarkCloudCoverType"
    DOJISTARTYPE = "DojiStarType"
    DOJITYPE = "DojiType"
    DRAGONFLYDOJITYPE = "DragonflyDojiType"
    ENGULFINGTYPE = "EngulfingType"
    EVENINGDOJISTARTYPE = "EveningDojiStarType"
    EVENINGSTARTYPE = "EveningStarType"
    GAPSIDESIDEWHITETYPE = "GapSideSideWhiteType"
    GRAVESTONEDOJITYPE = "GravestoneDojiType"
    HAMMERTYPE = "HammerType"
    HANGINGMANTYPE = "HangingManType"
    HARAMICROSSTYPE = "HaramiCrossType"
    HARAMITYPE = "HaramiType"
    HIGNWAVETYPE = "HignWaveType"
    HIKKAKEMODTYPE = "HikkakeModType"
    HIKKAKETYPE = "HikkakeType"
    HOMINGPIGEONTYPE = "HomingPigeonType"
    IDENTICALTHREECROWSTYPE = "IdenticalThreeCrowsType"
    INNECKTYPE = "InNeckType"
    INVERTEDHAMMERTYPE = "InvertedHammerType"
    KICKINGBYLENGTHTYPE = "KickingByLengthType"
    KICKINGTYPE = "KickingType"
    LADDERBOTTOMTYPE = "LadderBottomType"
    LONGLEGGEDDOJITYPE = "LongLeggedDojiType"
    LONGLINETYPE = "LongLineType"
    MARUBOZUTYPE = "MarubozuType"
    MATHOLDTYPE = "MatHoldType"
    MATCHINGLOWTYPE = "MatchingLowType"
    MORNINGDOJISTARTYPE = "MorningDojiStarType"
    MORNINGSTARTYPE = "MorningStarType"
    ONNECKTYPE = "OnNeckType"
    PIERCINGTYPE = "PiercingType"
    RICKSHAWMANTYPE = "RickshawManType"
    RISEFALLTHREEMETHODSTYPE = "RiseFallThreeMethodsType"
    SEPARATINGLINESTYPE = "SeparatingLinesType"
    SHOOTINGSTARTYPE = "ShootingStarType"
    SHORTLINETYPE = "ShortLineType"
    SIMPLEDOUBLEDOWNCANDLETYPE = "SimpleDoubleDownCandleType"
    SIMPLEDOUBLEUPCANDLETYPE = "SimpleDoubleUpCandleType"
    SIMPLEDOWNCANDLETYPE = "SimpleDownCandleType"
    SIMPLEUPCANDLETYPE = "SimpleUpCandleType"
    SPINNINGTOPTYPE = "SpinningTopType"
    STALLEDPATTERNTYPE = "StalledPatternType"
    STICKSANDWICHTYPE = "StickSandwichType"
    TAKURITYPE = "TakuriType"
    TASUKIGAPTYPE = "TasukiGapType"
    THREEBLACKCROWSTYPE = "ThreeBlackCrowsType"
    THREEINSIDETYPE = "ThreeInsideType"
    THREELINESTRIKETYPE = "ThreeLineStrikeType"
    THREEOUTSIDETYPE = "ThreeOutsideType"
    THREESTARSINSOUTHTYPE = "ThreeStarsInSouthType"
    THREEWHITESOLDIERSTYPE = "ThreeWhiteSoldiersType"
    THRUSTINGTYPE = "ThrustingType"
    TRISTARTYPE = "TristarType"
    TWOCROWSTYPE = "TwoCrowsType"
    UNIQUETHREERIVERTYPE = "UniqueThreeRiverType"
    UPSIDEGAPTWOCROWSTYPE = "UpsideGapTwoCrowsType"
    XSIDEGAPTHREEMETHODSTYPE = "XSideGapThreeMethodsType"

class ShapeType(str, Enum):
    SHAPEADD = "ShapeAdd"
    SHAPECIRCLE = "ShapeCircle"
    SHAPECROSS = "ShapeCross"
    SHAPEDASH = "ShapeDash"
    SHAPEDIAMOND = "ShapeDiamond"
    SHAPESQUARE = "ShapeSquare"
    SHAPETEXT = "ShapeText"
    SHAPETRIANGLEDOWN = "ShapeTriangleDown"
    SHAPETRIANGLEUP = "ShapeTriangleUp"

class AxisType(str, Enum):
    LEFTAXIS = "LeftAxis"
    LINEARAXIS = "LinearAxis"
    PERCENTAGEAXIS = "PercentageAxis"
    RIGHTAXIS = "RightAxis"

class LineStyle(str, Enum):
    DASHED = "Dashed"
    DOTTED = "Dotted"
    SMOOTH = "Smooth"
    SOLID = "Solid"
    SPIKED = "Spiked"
    STEP = "Step"
    STEPAFTER = "StepAfter"
    STEPBEFORE = "StepBefore"

class PlotType(str, Enum):
    CANDLESTICK = "Candlestick"
    CANDLESTICKHLC = "CandlestickHLC"
    CLOSELINE = "CloseLine"
    HLC = "HLC"
    HEIKINASHI = "HeikinAshi"
    LINE = "Line"
    MOUNTAIN = "Mountain"
    OHLC = "OHLC"
    SPREAD = "Spread"
    SPREADCANDLE = "SpreadCandle"

class DataTypesEnum(str, Enum):
    ARRAYDATATYPE = "ArrayDataType"
    BOOLDATATYPE = "BoolDataType"
    COMMANDDATATYPE = "CommandDataType"
    FUNCTIONDATATYPE = "FunctionDataType"
    NILDATATYPE = "NilDataType"
    NUMBERDATATYPE = "NumberDataType"
    TEXTDATATYPE = "TextDataType"
    TUPLEDATATYPE = "TupleDataType"
    UNKNOWNDATATYPE = "UnknownDataType"
    USERDATADATATYPE = "UserDataDataType"
    VOIDDATATYPE = "VoidDataType"

class MarginModeEnum(str, Enum):
    CROSSMARGINMODE = "CrossMarginMode"
    ISOLATEDMARGINMODE = "IsolatedMarginMode"

class MovingAveragesEnum(str, Enum):
    DEMATYPE = "DemaType"
    EMATYPE = "EmaType"
    KAMATYPE = "KamaType"
    MAMATYPE = "MamaType"
    SMATYPE = "SmaType"
    T3TYPE = "T3Type"
    TEMATYPE = "TemaType"
    TRIMATYPE = "TrimaType"
    WMATYPE = "WmaType"

class OrderTypesEnum(str, Enum):
    LIMIT = "LimitOrderType"
    MAKERORCANCEL = "MakerOrCancelOrderType"
    MARKET = "MarketOrderType"
    NOTIMEOUT = "NoTimeOutOrderType"
    STOPLIMIT = "StopLimitOrderType"
    STOPMARKET = "StopMarketOrderType"
    TAKEPROFITLIMIT = "TakeProfitLimitOrderType"
    TAKEPROFITMARKET = "TakeProfitMarketOrderType"

class ParameterTypeEnum(str, Enum):
    BOOLEANTYPE = "BooleanType"
    CALLBACKTYPE = "CallbackType"
    DYNAMICTYPE = "DynamicType"
    ENUMTYPE = "EnumType"
    LISTDYNAMICTYPE = "ListDynamicType"
    LISTNUMBERTYPE = "ListNumberType"
    NUMBERTYPE = "NumberType"
    STRINGTYPE = "StringType"
    VOIDTYPE = "VoidType"

class PositionEnum(str, Enum):
    NOPOSITION = "NoPosition"
    POSITIONBOUGHT = "PositionBought"
    POSITIONLONG = "PositionLong"
    POSITIONSHORT = "PositionShort"
    POSITIONSOLD = "PositionSold"

class PositionModeEnum(str, Enum):
    HEDGEPOSITIONMODE = "HedgePositionMode"
    ONEWAYPOSITIONMODE = "OneWayPositionMode"

class SignalEnum(str, Enum):
    SIGNALBUY = "SignalBuy"
    SIGNALERROR = "SignalError"
    SIGNALEXITLONG = "SignalExitLong"
    SIGNALEXITPOSITION = "SignalExitPosition"
    SIGNALEXITSHORT = "SignalExitShort"
    SIGNALLONG = "SignalLong"
    SIGNALNONE = "SignalNone"
    SIGNALRESERVEDA = "SignalReservedA"
    SIGNALRESERVEDB = "SignalReservedB"
    SIGNALSELL = "SignalSell"
    SIGNALSHORT = "SignalShort"

class SignalTypesEnum(str, Enum):
    BOTHCENTERCROSSTYPE = "BothCenterCrossType"
    BOTHTHRESHOLDTYPE = "BothThresholdType"
    INDICATORCENTERCROSSTYPE = "IndicatorCenterCrossType"
    INDICATORSIGNALCROSSTYPE = "IndicatorSignalCrossType"
    INDICATORTHRESHOLDTYPE = "IndicatorThresholdType"
    SIGNALCENTERCROSSTYPE = "SignalCenterCrossType"
    SIGNALTHRESHOLDTYPE = "SignalThresholdType"

class SourcePriceTypesEnum(str, Enum):
    CLOSEPRICESOURCE = "ClosePriceSource"
    HLCPRICESOURCE = "HLCPriceSource"
    HLPRICESOURCE = "HLPriceSource"
    HIGHPRICESOURCE = "HighPriceSource"
    LOWPRICESOURCE = "LowPriceSource"
    OHLCPRICESOURCE = "OHLCPriceSource"
    OPENPRICESOURCE = "OpenPriceSource"
    VOLUMEPRICESOURCE = "VolumePriceSource"

class TradingEnum(str, Enum):
    LEVERAGETRADING = "LeverageTrading"
    MARGINTRADING = "MarginTrading"
    SPOTTRADING = "SpotTrading"

class TradingLrEnum(str, Enum):
    LR_ANGLE = "LR_Angle"
    LR_DEFAULT = "LR_Default"
    LR_INTERCEPT = "LR_Intercept"
    LR_SLOPE = "LR_Slope"
