"""Add parameter templates table

Revision ID: 66752452cf0e
Revises: ba9d123b0080
Create Date: 2025-07-25 21:54:38.796573

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '66752452cf0e'
down_revision: Union[str, Sequence[str], None] = 'ba9d123b0080'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('parameter_templates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('script_id', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('parameters_json', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['script_id'], ['scripts.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('parameter_templates')
    # ### end Alembic commands ###
