"""Add performance metrics to Backtest model

Revision ID: ba9d123b0080
Revises: 67fcf33f0b93
Create Date: 2025-07-25 21:45:11.533126

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ba9d123b0080'
down_revision: Union[str, Sequence[str], None] = '67fcf33f0b93'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('backtests', sa.Column('sharpe_ratio', sa.Float(), nullable=True))
    op.add_column('backtests', sa.Column('sortino_ratio', sa.Float(), nullable=True))
    op.add_column('backtests', sa.Column('qualitative_assessment', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('backtests', 'qualitative_assessment')
    op.drop_column('backtests', 'sortino_ratio')
    op.drop_column('backtests', 'sharpe_ratio')
    # ### end Alembic commands ###
