<?php
// <summary>
// This file has been generated by Haasonline Trade Server v4.0.7.102
// Production date: 11/4/2025
// </summary>

namespace HaasomeApi\HaasCloud\WebServices;

class CustomAPI
{
    private $connection;
    public CustomAPI($conn)
    {
        $connection = $conn;
    }

    /// <summary>
    /// Gets all the default commands
    /// </summary>
    /// <returns></returns>
    function GetDefaultCommands()
    {
        return $connection->DoCall("CustomAPI", "GET_DEFAULT_COMMANDS");
    }
}
