<?php
// <summary>
// This file has been generated by Haasonline Trade Server v4.0.7.102
// Production date: 11/4/2025
// </summary>

namespace HaasomeApi\HaasCloud\WebServices;

class PriceAPI
{
    private $connection;
    public PriceAPI($conn)
    {
        $connection = $conn;
    }

    /// <summary>
    /// Returns the servertime (UNIX-UTC)
    /// </summary>
    /// <returns></returns>
    function Time()
    {
        return $connection->DoCall("PriceAPI", "TIME");
    }

    /// <summary>
    /// Returns a simple list of all the supported pricesources
    /// </summary>
    /// <returns></returns>
    function AllPricesources()
    {
        return $connection->DoCall("PriceAPI", "ALL_PRICESOURCES");
    }

    /// <summary>
    /// Returns a detailed list of all the supported pricesources
    /// </summary>
    /// <returns></returns>
    function Pricesources()
    {
        return $connection->DoCall("PriceAPI", "PRICESOURCES");
    }

    /// <summary>
    /// Returns a dictionary of the supported price sources and the markets they support
    /// </summary>
    /// <returns></returns>
    function AllMarkets()
    {
        return $connection->DoCall("PriceAPI", "ALL_MARKETS");
    }

    /// <summary>
    /// Returns a list of all the markets which are supported
    /// </summary>
    /// <returns></returns>
    function Marketlist()
    {
        return $connection->DoCall("PriceAPI", "MARKETLIST");
    }

    /// <summary>
    /// Returns a list of all unique markets which are supported
    /// </summary>
    /// <returns></returns>
    function UniqueMarketlist()
    {
        return $connection->DoCall("PriceAPI", "UNIQUE_MARKETLIST");
    }

    /// <summary>
    /// Returns a list of the supported markets
    /// </summary>
    /// <param name="pricesource">Name of the pricesource, like BINANCE</param>
    /// <returns></returns>
    function Markets($pricesource)
    {
        return $connection->DoCall("PriceAPI", "MARKETS", array(
        [
           "pricesource" = $pricesource,
        ];
    }

    /// <summary>
    /// Returns a list of the supported trade markets
    /// </summary>
    /// <param name="pricesource">Name of the pricesource, like BINANCE</param>
    /// <returns></returns>
    function TradeMarkets($pricesource)
    {
        return $connection->DoCall("PriceAPI", "TRADE_MARKETS", array(
        [
           "pricesource" = $pricesource,
        ];
    }

    /// <summary>
    /// Returns the trade market object of a marketTag
    /// </summary>
    /// <param name="markettag"></param>
    /// <returns></returns>
    function TradeMarket($markettag)
    {
        return $connection->DoCall("PriceAPI", "TRADE_MARKET", array(
        [
           "markettag" = $markettag,
        ];
    }

    /// <summary>
    /// Returns a list of all the coins which are supported
    /// </summary>
    /// <returns></returns>
    function Coinlist()
    {
        return $connection->DoCall("PriceAPI", "COINLIST");
    }

    /// <summary>
    /// Returns the last price
    /// </summary>
    /// <param name="market">Name of the market, like BINANCE_BTC_USDT_</param>
    /// <returns></returns>
    function Price($market)
    {
        return $connection->DoCall("PriceAPI", "PRICE", array(
        [
           "market" = $market,
        ];
    }

    /// <summary>
    /// Returns the last price
    /// </summary>
    /// <param name="market">Name of the market, like BINANCE_BTC_USDT_</param>
    /// <returns></returns>
    function LastMinuteTick($market)
    {
        return $connection->DoCall("PriceAPI", "LAST_MINUTE_TICK", array(
        [
           "market" = $market,
        ];
    }

    /// <summary>
    /// Returns the last price
    /// </summary>
    /// <param name="market">Name of the market, like BINANCE_BTC_USDT_</param>
    /// <param name="timestamp"></param>
    /// <returns></returns>
    function SpecificTick($market,$timestamp)
    {
        return $connection->DoCall("PriceAPI", "SPECIFIC_TICK", array(
        [
           "market" = $market,,
           "timestamp" = $timestamp,
        ];
    }

    /// <summary>
    /// Returns the last price
    /// </summary>
    /// <param name="market">Name of the market, like BINANCE_BTC_USDT_</param>
    /// <returns></returns>
    function OldestTick($market)
    {
        return $connection->DoCall("PriceAPI", "OLDEST_TICK", array(
        [
           "market" = $market,
        ];
    }

    /// <summary>
    /// Returns the last price
    /// </summary>
    /// <param name="market">Name of the market, like BINANCE_BTC_USDT_</param>
    /// <returns></returns>
    function Rolling24hTick($market)
    {
        return $connection->DoCall("PriceAPI", "ROLLING_24H_TICK", array(
        [
           "market" = $market,
        ];
    }

    /// <summary>
    /// Returns the orderbook
    /// </summary>
    /// <param name="market">Name of the market, like BINANCE_BTC_USDT_</param>
    /// <returns></returns>
    function Orderbook($market)
    {
        return $connection->DoCall("PriceAPI", "ORDERBOOK", array(
        [
           "market" = $market,
        ];
    }

    /// <summary>
    /// Returns the last trades
    /// </summary>
    /// <param name="market">Name of the market, like BINANCE_BTC_USDT_</param>
    /// <returns></returns>
    function Lasttrades($market)
    {
        return $connection->DoCall("PriceAPI", "LASTTRADES", array(
        [
           "market" = $market,
        ];
    }

    /// <summary>
    /// Returns the 10 very last minutes
    /// </summary>
    /// <param name="market">Name of the market, like BINANCE_BTC_USDT_</param>
    /// <returns></returns>
    function Syncticks($market)
    {
        return $connection->DoCall("PriceAPI", "SYNCTICKS", array(
        [
           "market" = $market,
        ];
    }

    /// <summary>
    /// Returns between 500 and 1440 ticks
    /// </summary>
    /// <param name="market">Name of the market, like BINANCE_BTC_USDT_</param>
    /// <param name="interval"></param>
    /// <param name="depth"></param>
    /// <returns></returns>
    function Lastticks($market,$interval,$depth)
    {
        return $connection->DoCall("PriceAPI", "LASTTICKS", array(
        [
           "market" = $market,,
           "interval" = $interval,,
           "depth" = $depth,
        ];
    }

    /// <summary>
    /// Returns about 40,000 ticks of the last minutes
    /// </summary>
    /// <param name="market">Name of the market, like BINANCE_BTC_USDT_</param>
    /// <returns></returns>
    function Deepticks($market)
    {
        return $connection->DoCall("PriceAPI", "DEEPTICKS", array(
        [
           "market" = $market,
        ];
    }

    /// <summary>
    /// Returns a snapshot of the very last prices
    /// </summary>
    /// <param name="pricesource">Name of the pricesource, like BINANCE</param>
    /// <returns></returns>
    function Snapshot($pricesource)
    {
        return $connection->DoCall("PriceAPI", "SNAPSHOT", array(
        [
           "pricesource" = $pricesource,
        ];
    }

    /// <summary>
    /// Returns a snapshot of the very last prices
    /// </summary>
    /// <param name="marketsstring"></param>
    /// <returns></returns>
    function CustomSnapshotLastTick($marketsstring)
    {
        return $connection->DoCall("PriceAPI", "CUSTOM_SNAPSHOT_LAST_TICK", array(
        [
           "marketsstring" = $marketsstring,
        ];
    }

    /// <summary>
    /// Returns a snapshot of the very last prices
    /// </summary>
    /// <param name="marketsstring"></param>
    /// <returns></returns>
    function CustomSnapshotMinuteTick($marketsstring)
    {
        return $connection->DoCall("PriceAPI", "CUSTOM_SNAPSHOT_MINUTE_TICK", array(
        [
           "marketsstring" = $marketsstring,
        ];
    }

    /// <summary>
    /// Returns average a fiat conversion rates
    /// </summary>
    /// <returns></returns>
    function FiatConversions()
    {
        return $connection->DoCall("PriceAPI", "FIAT_CONVERSIONS");
    }
}
