from enum import Enum
// <summary>
// This file has been generated by Haasonline Trade Server v4.0.7.102
// Production date: 11/4/2025
// </summary>

class EnumUserLabStatus(Enum):
  Created = 0
  Queued = 1
  Running = 2
  Completed = 3
  Cancelled = 4

