from enum import Enum
// <summary>
// This file has been generated by Haasonline Trade Server v4.0.7.102
// Production date: 11/4/2025
// </summary>

class EnumHaasChartLineType(Enum):
  Line = 0
  Bars = 1
  Band = 2
  Circle = 3
  Cloud = 4
  DoubleColor = 5
  DoubleColorFill = 6
  Histogram = 7
  StackedArea = 9
  Volume = 10
  SignalBars = 11
  PricePlotVolume = 13
  Shape = 14

