from enum import Enum
// <summary>
// This file has been generated by Haasonline Trade Server v4.0.7.102
// Production date: 11/4/2025
// </summary>

class EnumHaasOrderType(Enum):
  Limit = 0
  Market = 1
  StopLimit = 2
  StopMarket = 3
  TakeProfitLimit = 4
  TakeProfitMarket = 5
  TrailingStopLimit = 6
  TrailingStopMarket = 7

