from enum import Enum
// <summary>
// This file has been generated by Haasonline Trade Server v4.0.7.102
// Production date: 11/4/2025
// </summary>

class EnumHaasChartStatus(Enum):
  IsPerfect = 0
  IsEmpty = 1
  IsBroken = 2
  CompileError = 3
  IsRunning = 4
  IsLimit = 5

