from enum import Enum
// <summary>
// This file has been generated by Haasonline Trade Server v4.0.7.102
// Production date: 11/4/2025
// </summary>

class EnumHaasScriptMarketType(Enum):
  Spot = 1500
  Margin = 1501
  Leverage = 1502

