from enum import Enum
// <summary>
// This file has been generated by Haasonline Trade Server v4.0.7.102
// Production date: 11/4/2025
// </summary>

class EnumHaasScriptStatus(Enum):
  Private = 0
  Default = 1
  Community = 2
  Store = 3
  ReleaseToCommunity = 4
  ReleaseToStore = 5

