from enum import Enum
// <summary>
// This file has been generated by Haasonline Trade Server v4.0.7.102
// Production date: 11/4/2025
// </summary>

class EnumHaasUserDataType(Enum):
  None = 0
  HaasNumberCollection = 1
  HaasCallback = 2
  HaasEnum = 3
  HaasResultContainer = 4
  HaasColor = 5
  HaasSignal = 6

