import asyncio
import os
import time
from typing import List, Dict, Any

from pyHaasAPI.core.server_manager import ServerManager
from pyHaasAPI.config.settings import Settings
from pyHaasAPI.config.api_config import APIConfig
from pyHaasAPI.core.client import AsyncHaasClient
from pyHaasAPI.core.auth import AuthenticationManager
from pyHaasAPI.api.account.account_api import AccountAPI
from pyHaasAPI.api.lab.lab_api import LabAPI
from pyHaasAPI.api.backtest.backtest_api import BacktestAPI
from pyHaasAPI.api.bot.bot_api import BotAPI
from pyHaasAPI.api.script.script_api import ScriptAPI
from pyHaasAPI.models.lab import StartLabExecutionRequest

from dotenv import load_dotenv

async def miguel_pipeline():
    print("🚀 Starting Miguel Pipeline Execution...")
    load_dotenv()
    
    settings = Settings()
    sm = ServerManager(settings)
    print("Setting up SSH tunnel to srv03...")
    connected = await sm.connect_server('srv03')
    if not connected:
        print("Failed to establish SSH tunnel.")
        return
        
    api_config = APIConfig(
        host="127.0.0.1", 
        port=8090,
        email=os.getenv("API_EMAIL"),
        password=os.getenv("API_PASSWORD")
    )
    
    client = AsyncHaasClient(api_config)
    await client.connect()
    auth_manager = AuthenticationManager(client, api_config)
    await auth_manager.ensure_authenticated()
    
    account_api = AccountAPI(client, auth_manager)
    lab_api = LabAPI(client, auth_manager)
    backtest_api = BacktestAPI(client, auth_manager)
    bot_api = BotAPI(client, auth_manager)
    script_api = ScriptAPI(client, auth_manager)
    
    try:
        # 1. Trading Accounts & Prefixes
        print("\n--- 1. Trading Accounts Analysis ---")
        accounts = await account_api.get_accounts()
        binance_f_accounts = [acc for acc in accounts if 'BINANCEFUTURES' in acc.exchange.upper()]
        
        print(f"Total Accounts: {len(accounts)}")
        print(f"Binance Futures Accounts: {len(binance_f_accounts)}")
        
        if not binance_f_accounts:
            print("Creating a simulated Binance Futures account (Prefix: [Sim])...")
            target_account = await account_api.create_simulated_account(
                name="[Sim] Pipeline test", exchange="BINANCEFUTURES", initial_balance=5000.0, position_mode=1
            )
        else:
            target_account = binance_f_accounts[0]
            
        print(f"Target Account Selected: ID={target_account.account_id}, Name={target_account.name}, Exchange={target_account.exchange}")
        
        # 2. Labs Interactions - 1st Lab, Iteration
        print("\n--- 2. Labs Interaction & Backtesting Iteration ---")
        scripts = await script_api.get_all_scripts()
        if not scripts:
            print("No scripts available.")
            return
            
        target_script = scripts[0] # Just take the first available script for tests
        print(f"Using Script: {target_script.name}")
        
        print("Creating Lab 1 (Exploration Phase)...")
        lab1 = await lab_api.create_lab(
            script_id=target_script.script_id,
            name="Miguel Pipeline - Lab 1 Exploration",
            account_id=target_account.account_id,
            market="BINANCE_BTC_USDT_", # Requires specific exchange formatting
            interval=15,
            trade_amount=100.0,
            leverage=5.0,
            position_mode=1, # HEDGE
            margin_mode=0    # CROSS
        )
        print(f"Lab 1 created: {lab1.lab_id}")
        
        # In a real scenario, we would trigger an execution request to run iterations:
        # req1 = StartLabExecutionRequest(lab_id=lab1.lab_id, iterations=5, mode=1)
        # await lab_api.start_lab_execution(req1)
        
        # 3. Analytics & ROI (Cached Backtests)
        print("\n--- 3. Analyzing Backtest Results (ROI Calculation) ---")
        print(f"Fetching Backtest results for Lab 1 ({lab1.lab_id})...")
        BT_PAGE_SIZE = 10
        response = await backtest_api.get_backtest_result(lab1.lab_id, page_length=BT_PAGE_SIZE)
        
        if response.items:
            best_bt = None
            highest_roi = -float('inf')
            
            for bt in response.items:
                # ROI is generated by analyzing trades inside the backtest runtime data
                # bt.net_profit / starting_balance * 100 
                # Our models calculate this if correctly populated from api.
                if bt.roi > highest_roi:
                    highest_roi = bt.roi
                    best_bt = bt
                    
            print(f"Found {len(response.items)} backtests. Best ROI: {highest_roi}%")
            
            # 4. Clone best results to Lab 2
            print("\n--- 4. Cloning Best Result to Lab 2 (Finetuning) ---")
            lab2 = await lab_api.clone_lab(lab1.lab_id, new_name="Miguel Pipeline - Lab 2 Finetuning")
            # Usually here we would apply the best_bt parameters to the lab2 config
            # await lab_api.update_lab_details(lab2.lab_id, {"script_parameters": best_bt.parameters})
            print(f"Lab 2 Finetuning Created: {lab2.lab_id}")
            
        else:
            print("No backtest results in Lab 1. Skipping Lab 2 creation (Run iterations manually).")
        
        # 5. Bot Creation
        print("\n--- 5. Bot Creation Phase ---")
        print("Creating Bot from Strategy...")
        # A bot needs detailed settings, mapped from a lab or backtest
        
        print("Miguel pipeline framework is successfully executed using pure abstracted APIs.")

    except Exception as e:
        print(f"Pipeline error: {e}")
        
    finally:
        await client.close()
        await sm.shutdown()

if __name__ == "__main__":
    asyncio.run(miguel_pipeline())
