from enum import Enum
// <summary>
// This file has been generated by Haasonline Trade Server v4.0.7.102
// Production date: 11/4/2025
// </summary>

class EnumHaasChatPerson(Enum):
  Echo = 0
  Julia = 1
  Thomas = 2
  Edgar = 3
  Carlos = 4
  Eunomia = 5
  GPT = 6
  Gemini = 7
  David = 8
  Simone = 9

