from enum import Enum
// <summary>
// This file has been generated by Haasonline Trade Server v4.0.7.102
// Production date: 11/4/2025
// </summary>

class EnumHaasChartLineStyle(Enum):
  Smooth = 700
  Spiked = 701
  Step = 702
  StepAfter = 703
  StepBefore = 704

