from enum import Enum
// <summary>
// This file has been generated by Haasonline Trade Server v4.0.7.102
// Production date: 11/4/2025
// </summary>

class EnumUserLabAlgorithm(Enum):
  BruteForce = 0
  Intelligent = 1
  Random = 2
  Cluster = 3

