from enum import Enum
// <summary>
// This file has been generated by Haasonline Trade Server v4.0.7.102
// Production date: 11/4/2025
// </summary>

class EnumLoginResult(Enum):
  Success = 0
  InvalidUsernameOrPassword = 1
  Invalid2FACode = 2
  UnknownDevice = 3
  Failed = 4
  TwoFANeeded = 5
  Blocked = 6
  NotAllowed = 7
  ActivationNeeded = 8
  Banned = 9
  Unapproved = -1

