from enum import Enum
// <summary>
// This file has been generated by Haasonline Trade Server v4.0.7.102
// Production date: 11/4/2025
// </summary>

class EnumHaasOrderTimeInForce(Enum):
  GoodTillCancel = 0
  FillOrKill = 1
  ImmediateOrCancel = 2

