from enum import Enum
// <summary>
// This file has been generated by Haasonline Trade Server v4.0.7.102
// Production date: 11/4/2025
// </summary>

class EnumAccountStatus(Enum):
  Created = 0
  Connected = 1
  KeysError = 2
  Deactivate = 3

