from enum import Enum
// <summary>
// This file has been generated by Haasonline Trade Server v4.0.7.102
// Production date: 11/4/2025
// </summary>

class EnumHaasTradeSignal(Enum):
  SignalLong = 201
  SignalShort = 202
  SignalExitPosition = 203
  SignalNone = 204
  SignalError = 205
  SignalExitLong = 206
  SignalExitShort = 207
  SignalReservedA = 208
  SignalReservedB = 209

