from enum import Enum
// <summary>
// This file has been generated by Haasonline Trade Server v4.0.7.102
// Production date: 11/4/2025
// </summary>

class EnumHaasChartPricePlotStyle(Enum):
  CandleStick = 300
  CandleStickHLC = 301
  HeikinAshi = 302
  OHLC = 303
  HLC = 304
  CloseLine = 305
  Line = 306
  Mountain = 307
  Spread = 308
  SpreadCandle = 309

