from enum import Enum
// <summary>
// This file has been generated by Haasonline Trade Server v4.0.7.102
// Production date: 11/4/2025
// </summary>

class EnumRelationType(Enum):
  None = 0
  Bronze = 1
  Silver = 2
  Golden = 3

