from enum import Enum
// <summary>
// This file has been generated by Haasonline Trade Server v4.0.7.102
// Production date: 11/4/2025
// </summary>

class EnumHaasOrderDirection(Enum):
  Buy = 0
  Sell = 1
  GoLong = 2
  ExitLong = 3
  GoShort = 4
  ExitShort = 5

