from dataclasses import dataclass
// <summary>
// This file has been generated by Haasonline Trade Server v4.0.7.102
// Production date: 11/4/2025
// </summary>

@dataclass
class CloudLastTrade:
  Timestamp: TradeServer.Cluster.WebServer.Servers.RestServerInterface.PublicWebInputDefinition
  IsBuyOrder: TradeServer.Cluster.WebServer.Servers.RestServerInterface.PublicWebInputDefinition
  Price: TradeServer.Cluster.WebServer.Servers.RestServerInterface.PublicWebInputDefinition
  Amount: TradeServer.Cluster.WebServer.Servers.RestServerInterface.PublicWebInputDefinition

