from dataclasses import dataclass
// <summary>
// This file has been generated by Haasonline Trade Server v4.0.7.102
// Production date: 11/4/2025
// </summary>

@dataclass
class CloudTick:
  Timestamp: TradeServer.Cluster.WebServer.Servers.RestServerInterface.PublicWebInputDefinition
  Open: TradeServer.Cluster.WebServer.Servers.RestServerInterface.PublicWebInputDefinition
  High: TradeServer.Cluster.WebServer.Servers.RestServerInterface.PublicWebInputDefinition
  Low: TradeServer.Cluster.WebServer.Servers.RestServerInterface.PublicWebInputDefinition
  Close: TradeServer.Cluster.WebServer.Servers.RestServerInterface.PublicWebInputDefinition
  Volume: TradeServer.Cluster.WebServer.Servers.RestServerInterface.PublicWebInputDefinition
  BuyPrice: TradeServer.Cluster.WebServer.Servers.RestServerInterface.PublicWebInputDefinition
  SellPrice: TradeServer.Cluster.WebServer.Servers.RestServerInterface.PublicWebInputDefinition

