from dataclasses import dataclass
// <summary>
// This file has been generated by Haasonline Trade Server v4.0.7.102
// Production date: 11/4/2025
// </summary>

@dataclass
class CloudTradeContract:
  Type: TradeServer.Cluster.WebServer.Servers.RestServerInterface.PublicWebInputDefinition
  MarginCurrency: TradeServer.Cluster.WebServer.Servers.RestServerInterface.PublicWebInputDefinition
  DisplayName: TradeServer.Cluster.WebServer.Servers.RestServerInterface.PublicWebInputDefinition
  AmountLabel: TradeServer.Cluster.WebServer.Servers.RestServerInterface.PublicWebInputDefinition
  ProfitLabel: TradeServer.Cluster.WebServer.Servers.RestServerInterface.PublicWebInputDefinition
  ContractValue: TradeServer.Cluster.WebServer.Servers.RestServerInterface.PublicWebInputDefinition
  ContractValueCurrency: TradeServer.Cluster.WebServer.Servers.RestServerInterface.PublicWebInputDefinition
  SettlementDate: TradeServer.Cluster.WebServer.Servers.RestServerInterface.PublicWebInputDefinition
  LowestLeverage: TradeServer.Cluster.WebServer.Servers.RestServerInterface.PublicWebInputDefinition
  HighestLeverage: TradeServer.Cluster.WebServer.Servers.RestServerInterface.PublicWebInputDefinition

