from dataclasses import dataclass
// <summary>
// This file has been generated by Haasonline Trade Server v4.0.7.102
// Production date: 11/4/2025
// </summary>

@dataclass
class CloudPriceSourceOAuthAuthentication:
  IsAvailable: TradeServer.Cluster.WebServer.Servers.RestServerInterface.PublicWebInputDefinition
  ButtonBackground: TradeServer.Cluster.WebServer.Servers.RestServerInterface.PublicWebInputDefinition
  IsDarkText: TradeServer.Cluster.WebServer.Servers.RestServerInterface.PublicWebInputDefinition

