from dataclasses import dataclass
// <summary>
// This file has been generated by Haasonline Trade Server v4.0.7.102
// Production date: 11/4/2025
// </summary>

@dataclass
class CloudTradeMarket:
  NormalizedPrimary: TradeServer.Cluster.WebServer.Servers.RestServerInterface.PublicWebInputDefinition
  NormalizedSecondary: TradeServer.Cluster.WebServer.Servers.RestServerInterface.PublicWebInputDefinition
  NormalizedMarginCurrency: TradeServer.Cluster.WebServer.Servers.RestServerInterface.PublicWebInputDefinition
  ExchangeSymbol: TradeServer.Cluster.WebServer.Servers.RestServerInterface.PublicWebInputDefinition
  WebSocketSymbol: TradeServer.Cluster.WebServer.Servers.RestServerInterface.PublicWebInputDefinition
  ExchangeValue: TradeServer.Cluster.WebServer.Servers.RestServerInterface.PublicWebInputDefinition
  PriceStep: TradeServer.Cluster.WebServer.Servers.RestServerInterface.PublicWebInputDefinition
  PriceDecimals: TradeServer.Cluster.WebServer.Servers.RestServerInterface.PublicWebInputDefinition
  AmountStep: TradeServer.Cluster.WebServer.Servers.RestServerInterface.PublicWebInputDefinition
  AmountDecimals: TradeServer.Cluster.WebServer.Servers.RestServerInterface.PublicWebInputDefinition
  PriceDecimalType: TradeServer.Cluster.WebServer.Servers.RestServerInterface.PublicWebInputDefinition
  AmountDecimalType: TradeServer.Cluster.WebServer.Servers.RestServerInterface.PublicWebInputDefinition
  MakersFee: TradeServer.Cluster.WebServer.Servers.RestServerInterface.PublicWebInputDefinition
  TakersFee: TradeServer.Cluster.WebServer.Servers.RestServerInterface.PublicWebInputDefinition
  MinimumTradeAmount: TradeServer.Cluster.WebServer.Servers.RestServerInterface.PublicWebInputDefinition
  MinimumTradeVolume: TradeServer.Cluster.WebServer.Servers.RestServerInterface.PublicWebInputDefinition
  MaximumTradeAmount: TradeServer.Cluster.WebServer.Servers.RestServerInterface.PublicWebInputDefinition
  MaximumTradeVolume: TradeServer.Cluster.WebServer.Servers.RestServerInterface.PublicWebInputDefinition
  IsOpen: TradeServer.Cluster.WebServer.Servers.RestServerInterface.PublicWebInputDefinition
  IsMargin: TradeServer.Cluster.WebServer.Servers.RestServerInterface.PublicWebInputDefinition
  ContractDetails: TradeServer.Cluster.WebServer.Servers.RestServerInterface.PublicWebInputDefinition
  MarginCurrency: TradeServer.Cluster.WebServer.Servers.RestServerInterface.PublicWebInputDefinition
  AmountLabel: TradeServer.Cluster.WebServer.Servers.RestServerInterface.PublicWebInputDefinition
  ProfitLabel: TradeServer.Cluster.WebServer.Servers.RestServerInterface.PublicWebInputDefinition
  PriceSource: TradeServer.Cluster.WebServer.Servers.RestServerInterface.PublicWebInputDefinition
  Primary: TradeServer.Cluster.WebServer.Servers.RestServerInterface.PublicWebInputDefinition
  Secondary: TradeServer.Cluster.WebServer.Servers.RestServerInterface.PublicWebInputDefinition
  ContractName: TradeServer.Cluster.WebServer.Servers.RestServerInterface.PublicWebInputDefinition
  ShortName: TradeServer.Cluster.WebServer.Servers.RestServerInterface.PublicWebInputDefinition
  WalletTag: TradeServer.Cluster.WebServer.Servers.RestServerInterface.PublicWebInputDefinition

