from dataclasses import dataclass
// <summary>
// This file has been generated by Haasonline Trade Server v4.0.7.102
// Production date: 11/4/2025
// </summary>

@dataclass
class HaasCommandInput:
  Index: TradeServer.Cluster.WebServer.Servers.RestServerInterface.PublicWebInputDefinition
  Name: TradeServer.Cluster.WebServer.Servers.RestServerInterface.PublicWebInputDefinition
  Type: TradeServer.Cluster.WebServer.Servers.RestServerInterface.PublicWebInputDefinition
  IsRequired: TradeServer.Cluster.WebServer.Servers.RestServerInterface.PublicWebInputDefinition
  IsHidden: TradeServer.Cluster.WebServer.Servers.RestServerInterface.PublicWebInputDefinition
  IsField: TradeServer.Cluster.WebServer.Servers.RestServerInterface.PublicWebInputDefinition
  AllowNull: TradeServer.Cluster.WebServer.Servers.RestServerInterface.PublicWebInputDefinition
  Description: TradeServer.Cluster.WebServer.Servers.RestServerInterface.PublicWebInputDefinition
  DefaultStorage: TradeServer.Cluster.WebServer.Servers.RestServerInterface.PublicWebInputDefinition
  Suggestion: TradeServer.Cluster.WebServer.Servers.RestServerInterface.PublicWebInputDefinition

