from dataclasses import dataclass
// <summary>
// This file has been generated by Haasonline Trade Server v4.0.7.102
// Production date: 11/4/2025
// </summary>

@dataclass
class HaasScriptExecutor:
  ExecutorId: TradeServer.Cluster.WebServer.Servers.RestServerInterface.PublicWebInputDefinition
  ScriptId: TradeServer.Cluster.WebServer.Servers.RestServerInterface.PublicWebInputDefinition
  CommandName: TradeServer.Cluster.WebServer.Servers.RestServerInterface.PublicWebInputDefinition
  InputParameter: TradeServer.Cluster.WebServer.Servers.RestServerInterface.PublicWebInputDefinition
  Result: TradeServer.Cluster.WebServer.Servers.RestServerInterface.PublicWebInputDefinition
  Cache: TradeServer.Cluster.WebServer.Servers.RestServerInterface.PublicWebInputDefinition

