from dataclasses import dataclass
// <summary>
// This file has been generated by Haasonline Trade Server v4.0.7.102
// Production date: 11/4/2025
// </summary>

@dataclass
class HaasScriptExecutionPackage:
  ScriptId: TradeServer.Cluster.WebServer.Servers.RestServerInterface.PublicWebInputDefinition
  ScriptName: TradeServer.Cluster.WebServer.Servers.RestServerInterface.PublicWebInputDefinition
  ScriptType: TradeServer.Cluster.WebServer.Servers.RestServerInterface.PublicWebInputDefinition
  IsCommand: TradeServer.Cluster.WebServer.Servers.RestServerInterface.PublicWebInputDefinition
  CommandName: TradeServer.Cluster.WebServer.Servers.RestServerInterface.PublicWebInputDefinition
  SourceCode: TradeServer.Cluster.WebServer.Servers.RestServerInterface.PublicWebInputDefinition
  Commands: TradeServer.Cluster.WebServer.Servers.RestServerInterface.PublicWebInputDefinition

