from dataclasses import dataclass
// <summary>
// This file has been generated by Haasonline Trade Server v4.0.7.102
// Production date: 11/4/2025
// </summary>

@dataclass
class HaasBot:
  RecordId: TradeServer.Cluster.WebServer.Servers.RestServerInterface.PublicWebInputDefinition
  UserId: TradeServer.Cluster.WebServer.Servers.RestServerInterface.PublicWebInputDefinition
  BotId: TradeServer.Cluster.WebServer.Servers.RestServerInterface.PublicWebInputDefinition
  BotName: TradeServer.Cluster.WebServer.Servers.RestServerInterface.PublicWebInputDefinition
  ScriptId: TradeServer.Cluster.WebServer.Servers.RestServerInterface.PublicWebInputDefinition
  ScriptVersion: TradeServer.Cluster.WebServer.Servers.RestServerInterface.PublicWebInputDefinition
  AccountId: TradeServer.Cluster.WebServer.Servers.RestServerInterface.PublicWebInputDefinition
  Market: TradeServer.Cluster.WebServer.Servers.RestServerInterface.PublicWebInputDefinition
  ExecutionId: TradeServer.Cluster.WebServer.Servers.RestServerInterface.PublicWebInputDefinition
  IsActivated: TradeServer.Cluster.WebServer.Servers.RestServerInterface.PublicWebInputDefinition
  IsPaused: TradeServer.Cluster.WebServer.Servers.RestServerInterface.PublicWebInputDefinition
  IsFavorite: TradeServer.Cluster.WebServer.Servers.RestServerInterface.PublicWebInputDefinition
  Notes: TradeServer.Cluster.WebServer.Servers.RestServerInterface.PublicWebInputDefinition
  ScriptNote: TradeServer.Cluster.WebServer.Servers.RestServerInterface.PublicWebInputDefinition
  NotesTimestamp: TradeServer.Cluster.WebServer.Servers.RestServerInterface.PublicWebInputDefinition
  RealizedProfit: TradeServer.Cluster.WebServer.Servers.RestServerInterface.PublicWebInputDefinition
  UnrealizedProfit: TradeServer.Cluster.WebServer.Servers.RestServerInterface.PublicWebInputDefinition
  ReturnOnInvestment: TradeServer.Cluster.WebServer.Servers.RestServerInterface.PublicWebInputDefinition
  TradeAmountError: TradeServer.Cluster.WebServer.Servers.RestServerInterface.PublicWebInputDefinition
  AccountError: TradeServer.Cluster.WebServer.Servers.RestServerInterface.PublicWebInputDefinition
  ScriptError: TradeServer.Cluster.WebServer.Servers.RestServerInterface.PublicWebInputDefinition
  UpdateCounter: TradeServer.Cluster.WebServer.Servers.RestServerInterface.PublicWebInputDefinition
  ChartInterval: TradeServer.Cluster.WebServer.Servers.RestServerInterface.PublicWebInputDefinition
  ChartStyle: TradeServer.Cluster.WebServer.Servers.RestServerInterface.PublicWebInputDefinition
  ChartVolume: TradeServer.Cluster.WebServer.Servers.RestServerInterface.PublicWebInputDefinition
  IsWhiteLabel: TradeServer.Cluster.WebServer.Servers.RestServerInterface.PublicWebInputDefinition
  MasterBotId: TradeServer.Cluster.WebServer.Servers.RestServerInterface.PublicWebInputDefinition
  Followers: TradeServer.Cluster.WebServer.Servers.RestServerInterface.PublicWebInputDefinition
  Runtime: TradeServer.Cluster.WebServer.Servers.RestServerInterface.PublicWebInputDefinition
  ScriptPackage: TradeServer.Cluster.WebServer.Servers.RestServerInterface.PublicWebInputDefinition

