from dataclasses import dataclass
// <summary>
// This file has been generated by Haasonline Trade Server v4.0.7.102
// Production date: 11/4/2025
// </summary>

@dataclass
class HaasCommandBase:
  CommandName: TradeServer.Cluster.WebServer.Servers.RestServerInterface.PublicWebInputDefinition
  Command: TradeServer.Cluster.WebServer.Servers.RestServerInterface.PublicWebInputDefinition
  CommandType: TradeServer.Cluster.WebServer.Servers.RestServerInterface.PublicWebInputDefinition
  Category: TradeServer.Cluster.WebServer.Servers.RestServerInterface.PublicWebInputDefinition
  Description: TradeServer.Cluster.WebServer.Servers.RestServerInterface.PublicWebInputDefinition
  ReturnDescription: TradeServer.Cluster.WebServer.Servers.RestServerInterface.PublicWebInputDefinition
  Parameters: TradeServer.Cluster.WebServer.Servers.RestServerInterface.PublicWebInputDefinition
  OutputIndex: TradeServer.Cluster.WebServer.Servers.RestServerInterface.PublicWebInputDefinition
  IsConstant: TradeServer.Cluster.WebServer.Servers.RestServerInterface.PublicWebInputDefinition
  IsPrimary: TradeServer.Cluster.WebServer.Servers.RestServerInterface.PublicWebInputDefinition
  RequiresCall: TradeServer.Cluster.WebServer.Servers.RestServerInterface.PublicWebInputDefinition
  Resizable: TradeServer.Cluster.WebServer.Servers.RestServerInterface.PublicWebInputDefinition
  OutputHidden: TradeServer.Cluster.WebServer.Servers.RestServerInterface.PublicWebInputDefinition
  OutputType: TradeServer.Cluster.WebServer.Servers.RestServerInterface.PublicWebInputDefinition
  OutputSuggestions: TradeServer.Cluster.WebServer.Servers.RestServerInterface.PublicWebInputDefinition
  ChangeTypes: TradeServer.Cluster.WebServer.Servers.RestServerInterface.PublicWebInputDefinition
  ExecutionTimes: TradeServer.Cluster.WebServer.Servers.RestServerInterface.PublicWebInputDefinition

