from dataclasses import dataclass
// <summary>
// This file has been generated by Haasonline Trade Server v4.0.7.102
// Production date: 11/4/2025
// </summary>

@dataclass
class HaasChartAnnotations:
  Name: TradeServer.Cluster.WebServer.Servers.RestServerInterface.PublicWebInputDefinition
  Type: TradeServer.Cluster.WebServer.Servers.RestServerInterface.PublicWebInputDefinition
  Decoration: TradeServer.Cluster.WebServer.Servers.RestServerInterface.PublicWebInputDefinition
  Side: TradeServer.Cluster.WebServer.Servers.RestServerInterface.PublicWebInputDefinition
  Colors: TradeServer.Cluster.WebServer.Servers.RestServerInterface.PublicWebInputDefinition
  Values: TradeServer.Cluster.WebServer.Servers.RestServerInterface.PublicWebInputDefinition
  Timestamps: TradeServer.Cluster.WebServer.Servers.RestServerInterface.PublicWebInputDefinition

