from dataclasses import dataclass
// <summary>
// This file has been generated by Haasonline Trade Server v4.0.7.102
// Production date: 11/4/2025
// </summary>

@dataclass
class HaasScriptCommandRecord:
  CommandName: TradeServer.Cluster.WebServer.Servers.RestServerInterface.PublicWebInputDefinition
  CommandDescription: TradeServer.Cluster.WebServer.Servers.RestServerInterface.PublicWebInputDefinition
  IsManagedTrading: TradeServer.Cluster.WebServer.Servers.RestServerInterface.PublicWebInputDefinition
  IsUnmanagedSpot: TradeServer.Cluster.WebServer.Servers.RestServerInterface.PublicWebInputDefinition
  IsUnmanagedLeverage: TradeServer.Cluster.WebServer.Servers.RestServerInterface.PublicWebInputDefinition
  HasOrderHandling: TradeServer.Cluster.WebServer.Servers.RestServerInterface.PublicWebInputDefinition
  Parameters: TradeServer.Cluster.WebServer.Servers.RestServerInterface.PublicWebInputDefinition
  Output: TradeServer.Cluster.WebServer.Servers.RestServerInterface.PublicWebInputDefinition
  OutputIndex: TradeServer.Cluster.WebServer.Servers.RestServerInterface.PublicWebInputDefinition

