from dataclasses import dataclass
// <summary>
// This file has been generated by Haasonline Trade Server v4.0.7.102
// Production date: 11/4/2025
// </summary>

@dataclass
class HaasScriptFolderRecord:
  UserId: TradeServer.Cluster.WebServer.Servers.RestServerInterface.PublicWebInputDefinition
  FolderId: TradeServer.Cluster.WebServer.Servers.RestServerInterface.PublicWebInputDefinition
  FolderName: TradeServer.Cluster.WebServer.Servers.RestServerInterface.PublicWebInputDefinition
  ParentId: TradeServer.Cluster.WebServer.Servers.RestServerInterface.PublicWebInputDefinition
  CreatedUnix: TradeServer.Cluster.WebServer.Servers.RestServerInterface.PublicWebInputDefinition
  UpdatedUnix: TradeServer.Cluster.WebServer.Servers.RestServerInterface.PublicWebInputDefinition

