from dataclasses import dataclass
// <summary>
// This file has been generated by Haasonline Trade Server v4.0.7.102
// Production date: 11/4/2025
// </summary>

@dataclass
class HaasChartPricePlotColorScheme:
  Up: TradeServer.Cluster.WebServer.Servers.RestServerInterface.PublicWebInputDefinition
  UpFill: TradeServer.Cluster.WebServer.Servers.RestServerInterface.PublicWebInputDefinition
  Down: TradeServer.Cluster.WebServer.Servers.RestServerInterface.PublicWebInputDefinition
  DownFill: TradeServer.Cluster.WebServer.Servers.RestServerInterface.PublicWebInputDefinition
  Marked: TradeServer.Cluster.WebServer.Servers.RestServerInterface.PublicWebInputDefinition
  MarkedFill: TradeServer.Cluster.WebServer.Servers.RestServerInterface.PublicWebInputDefinition

