from dataclasses import dataclass
// <summary>
// This file has been generated by Haasonline Trade Server v4.0.7.102
// Production date: 11/4/2025
// </summary>

@dataclass
class HaasChartPlot:
  PlotId: TradeServer.Cluster.WebServer.Servers.RestServerInterface.PublicWebInputDefinition
  PlotIndex: TradeServer.Cluster.WebServer.Servers.RestServerInterface.PublicWebInputDefinition
  Title: TradeServer.Cluster.WebServer.Servers.RestServerInterface.PublicWebInputDefinition
  Height: TradeServer.Cluster.WebServer.Servers.RestServerInterface.PublicWebInputDefinition
  IsSignalPlot: TradeServer.Cluster.WebServer.Servers.RestServerInterface.PublicWebInputDefinition
  RightAxis: TradeServer.Cluster.WebServer.Servers.RestServerInterface.PublicWebInputDefinition
  LeftAxis: TradeServer.Cluster.WebServer.Servers.RestServerInterface.PublicWebInputDefinition
  PricePlot: TradeServer.Cluster.WebServer.Servers.RestServerInterface.PublicWebInputDefinition
  DataLines: TradeServer.Cluster.WebServer.Servers.RestServerInterface.PublicWebInputDefinition
  Shapes: TradeServer.Cluster.WebServer.Servers.RestServerInterface.PublicWebInputDefinition
  Annotations: TradeServer.Cluster.WebServer.Servers.RestServerInterface.PublicWebInputDefinition
  TradeAnnotations: TradeServer.Cluster.WebServer.Servers.RestServerInterface.PublicWebInputDefinition

