from dataclasses import dataclass
// <summary>
// This file has been generated by Haasonline Trade Server v4.0.7.102
// Production date: 11/4/2025
// </summary>

@dataclass
class HaasChartShapes:
  Type: TradeServer.Cluster.WebServer.Servers.RestServerInterface.PublicWebInputDefinition
  AboveCandle: TradeServer.Cluster.WebServer.Servers.RestServerInterface.PublicWebInputDefinition
  TextColor: TradeServer.Cluster.WebServer.Servers.RestServerInterface.PublicWebInputDefinition
  Color: TradeServer.Cluster.WebServer.Servers.RestServerInterface.PublicWebInputDefinition
  Text: TradeServer.Cluster.WebServer.Servers.RestServerInterface.PublicWebInputDefinition
  Size: TradeServer.Cluster.WebServer.Servers.RestServerInterface.PublicWebInputDefinition

