from dataclasses import dataclass
// <summary>
// This file has been generated by Haasonline Trade Server v4.0.7.102
// Production date: 11/4/2025
// </summary>

@dataclass
class HaasBotTemplate:
  BotId: TradeServer.Cluster.WebServer.Servers.RestServerInterface.PublicWebInputDefinition
  BotName: TradeServer.Cluster.WebServer.Servers.RestServerInterface.PublicWebInputDefinition
  ScriptName: TradeServer.Cluster.WebServer.Servers.RestServerInterface.PublicWebInputDefinition
  ScriptVersion: TradeServer.Cluster.WebServer.Servers.RestServerInterface.PublicWebInputDefinition
  Market: TradeServer.Cluster.WebServer.Servers.RestServerInterface.PublicWebInputDefinition
  DisplayMarket: TradeServer.Cluster.WebServer.Servers.RestServerInterface.PublicWebInputDefinition
  DisplayMarketShort: TradeServer.Cluster.WebServer.Servers.RestServerInterface.PublicWebInputDefinition
  ActivatedSince: TradeServer.Cluster.WebServer.Servers.RestServerInterface.PublicWebInputDefinition
  TimeRunning: TradeServer.Cluster.WebServer.Servers.RestServerInterface.PublicWebInputDefinition
  ReturnOnInvestment: TradeServer.Cluster.WebServer.Servers.RestServerInterface.PublicWebInputDefinition
  Last24HoursROI: TradeServer.Cluster.WebServer.Servers.RestServerInterface.PublicWebInputDefinition
  MaxROI: TradeServer.Cluster.WebServer.Servers.RestServerInterface.PublicWebInputDefinition
  MinROI: TradeServer.Cluster.WebServer.Servers.RestServerInterface.PublicWebInputDefinition
  AverageROI: TradeServer.Cluster.WebServer.Servers.RestServerInterface.PublicWebInputDefinition
  DailyROI: TradeServer.Cluster.WebServer.Servers.RestServerInterface.PublicWebInputDefinition
  Positions: TradeServer.Cluster.WebServer.Servers.RestServerInterface.PublicWebInputDefinition
  Cloned: TradeServer.Cluster.WebServer.Servers.RestServerInterface.PublicWebInputDefinition
  Notes: TradeServer.Cluster.WebServer.Servers.RestServerInterface.PublicWebInputDefinition

