from dataclasses import dataclass
// <summary>
// This file has been generated by Haasonline Trade Server v4.0.7.102
// Production date: 11/4/2025
// </summary>

@dataclass
class MarketTechnicalInformation:
  Timestamp: TradeServer.Cluster.WebServer.Servers.RestServerInterface.PublicWebInputDefinition
  Market: TradeServer.Cluster.WebServer.Servers.RestServerInterface.PublicWebInputDefinition
  TrendIndicators: TradeServer.Cluster.WebServer.Servers.RestServerInterface.PublicWebInputDefinition
  SideWaysIndicators: TradeServer.Cluster.WebServer.Servers.RestServerInterface.PublicWebInputDefinition

