from dataclasses import dataclass
// <summary>
// This file has been generated by Haasonline Trade Server v4.0.7.102
// Production date: 11/4/2025
// </summary>

@dataclass
class RuntimeCustomReport:
  Comparer: TradeServer.Cluster.WebServer.Servers.RestServerInterface.PublicWebInputDefinition
  Keys: TradeServer.Cluster.WebServer.Servers.RestServerInterface.PublicWebInputDefinition
  Values: TradeServer.Cluster.WebServer.Servers.RestServerInterface.PublicWebInputDefinition
  Item: TradeServer.Cluster.WebServer.Servers.RestServerInterface.PublicWebInputDefinition

