from dataclasses import dataclass
// <summary>
// This file has been generated by Haasonline Trade Server v4.0.7.102
// Production date: 11/4/2025
// </summary>

@dataclass
class SignalProviderRecord:
  Id: TradeServer.Cluster.WebServer.Servers.RestServerInterface.PublicWebInputDefinition
  UserId: TradeServer.Cluster.WebServer.Servers.RestServerInterface.PublicWebInputDefinition
  Name: TradeServer.Cluster.WebServer.Servers.RestServerInterface.PublicWebInputDefinition
  Description: TradeServer.Cluster.WebServer.Servers.RestServerInterface.PublicWebInputDefinition
  SecretKey: TradeServer.Cluster.WebServer.Servers.RestServerInterface.PublicWebInputDefinition
  Published: TradeServer.Cluster.WebServer.Servers.RestServerInterface.PublicWebInputDefinition

