from dataclasses import dataclass
// <summary>
// This file has been generated by Haasonline Trade Server v4.0.7.102
// Production date: 11/4/2025
// </summary>

@dataclass
class UserBalanceItem:
  Currency: TradeServer.Cluster.WebServer.Servers.RestServerInterface.PublicWebInputDefinition
  WalletId: TradeServer.Cluster.WebServer.Servers.RestServerInterface.PublicWebInputDefinition
  Available: TradeServer.Cluster.WebServer.Servers.RestServerInterface.PublicWebInputDefinition
  Total: TradeServer.Cluster.WebServer.Servers.RestServerInterface.PublicWebInputDefinition

