from dataclasses import dataclass
// <summary>
// This file has been generated by Haasonline Trade Server v4.0.7.102
// Production date: 11/4/2025
// </summary>

@dataclass
class UserMarginSettings:
  PositionMode: TradeServer.Cluster.WebServer.Servers.RestServerInterface.PublicWebInputDefinition
  MarginMode: TradeServer.Cluster.WebServer.Servers.RestServerInterface.PublicWebInputDefinition
  LongLeverage: TradeServer.Cluster.WebServer.Servers.RestServerInterface.PublicWebInputDefinition
  ShortLeverage: TradeServer.Cluster.WebServer.Servers.RestServerInterface.PublicWebInputDefinition

