from dataclasses import dataclass
// <summary>
// This file has been generated by Haasonline Trade Server v4.0.7.102
// Production date: 11/4/2025
// </summary>

@dataclass
class UserOrderCancelResult:
  IsCancelled: TradeServer.Cluster.WebServer.Servers.RestServerInterface.PublicWebInputDefinition
  IsNotOpen: TradeServer.Cluster.WebServer.Servers.RestServerInterface.PublicWebInputDefinition
  CancelFailed: TradeServer.Cluster.WebServer.Servers.RestServerInterface.PublicWebInputDefinition
  CancelStatus: TradeServer.Cluster.WebServer.Servers.RestServerInterface.PublicWebInputDefinition

