from dataclasses import dataclass
// <summary>
// This file has been generated by Haasonline Trade Server v4.0.7.102
// Production date: 11/4/2025
// </summary>

@dataclass
class UserLabDetails:
  Config: TradeServer.Cluster.WebServer.Servers.RestServerInterface.PublicWebInputDefinition
  Settings: TradeServer.Cluster.WebServer.Servers.RestServerInterface.PublicWebInputDefinition
  Parameters: TradeServer.Cluster.WebServer.Servers.RestServerInterface.PublicWebInputDefinition
  UserId: TradeServer.Cluster.WebServer.Servers.RestServerInterface.PublicWebInputDefinition
  LabId: TradeServer.Cluster.WebServer.Servers.RestServerInterface.PublicWebInputDefinition
  ScriptId: TradeServer.Cluster.WebServer.Servers.RestServerInterface.PublicWebInputDefinition
  Name: TradeServer.Cluster.WebServer.Servers.RestServerInterface.PublicWebInputDefinition
  Type: TradeServer.Cluster.WebServer.Servers.RestServerInterface.PublicWebInputDefinition
  Status: TradeServer.Cluster.WebServer.Servers.RestServerInterface.PublicWebInputDefinition
  ScheduledBacktests: TradeServer.Cluster.WebServer.Servers.RestServerInterface.PublicWebInputDefinition
  CompletedBacktests: TradeServer.Cluster.WebServer.Servers.RestServerInterface.PublicWebInputDefinition
  CreatedAt: TradeServer.Cluster.WebServer.Servers.RestServerInterface.PublicWebInputDefinition
  UpdatedAt: TradeServer.Cluster.WebServer.Servers.RestServerInterface.PublicWebInputDefinition
  StartedAt: TradeServer.Cluster.WebServer.Servers.RestServerInterface.PublicWebInputDefinition
  RunningSince: TradeServer.Cluster.WebServer.Servers.RestServerInterface.PublicWebInputDefinition
  StartUnix: TradeServer.Cluster.WebServer.Servers.RestServerInterface.PublicWebInputDefinition
  EndUnix: TradeServer.Cluster.WebServer.Servers.RestServerInterface.PublicWebInputDefinition
  SendEmail: TradeServer.Cluster.WebServer.Servers.RestServerInterface.PublicWebInputDefinition
  ScriptPackage: TradeServer.Cluster.WebServer.Servers.RestServerInterface.PublicWebInputDefinition
  CancelReason: TradeServer.Cluster.WebServer.Servers.RestServerInterface.PublicWebInputDefinition

