from dataclasses import dataclass
// <summary>
// This file has been generated by Haasonline Trade Server v4.0.7.102
// Production date: 11/4/2025
// </summary>

@dataclass
class UserLabsBacktestSummary:
  Orders: TradeServer.Cluster.WebServer.Servers.RestServerInterface.PublicWebInputDefinition
  Trades: TradeServer.Cluster.WebServer.Servers.RestServerInterface.PublicWebInputDefinition
  Positions: TradeServer.Cluster.WebServer.Servers.RestServerInterface.PublicWebInputDefinition
  FeeCosts: TradeServer.Cluster.WebServer.Servers.RestServerInterface.PublicWebInputDefinition
  RealizedProfits: TradeServer.Cluster.WebServer.Servers.RestServerInterface.PublicWebInputDefinition
  ReturnOnInvestment: TradeServer.Cluster.WebServer.Servers.RestServerInterface.PublicWebInputDefinition
  CustomReport: TradeServer.Cluster.WebServer.Servers.RestServerInterface.PublicWebInputDefinition

