from dataclasses import dataclass
// <summary>
// This file has been generated by Haasonline Trade Server v4.0.7.102
// Production date: 11/4/2025
// </summary>

@dataclass
class UserAccount:
  UserId: TradeServer.Cluster.WebServer.Servers.RestServerInterface.PublicWebInputDefinition
  AccountId: TradeServer.Cluster.WebServer.Servers.RestServerInterface.PublicWebInputDefinition
  Name: TradeServer.Cluster.WebServer.Servers.RestServerInterface.PublicWebInputDefinition
  ExchangeCode: TradeServer.Cluster.WebServer.Servers.RestServerInterface.PublicWebInputDefinition
  ExchangeType: TradeServer.Cluster.WebServer.Servers.RestServerInterface.PublicWebInputDefinition
  Status: TradeServer.Cluster.WebServer.Servers.RestServerInterface.PublicWebInputDefinition
  IsSimulated: TradeServer.Cluster.WebServer.Servers.RestServerInterface.PublicWebInputDefinition
  IsTestNet: TradeServer.Cluster.WebServer.Servers.RestServerInterface.PublicWebInputDefinition
  IsPublic: TradeServer.Cluster.WebServer.Servers.RestServerInterface.PublicWebInputDefinition
  IsWhiteLabel: TradeServer.Cluster.WebServer.Servers.RestServerInterface.PublicWebInputDefinition
  PositionMode: TradeServer.Cluster.WebServer.Servers.RestServerInterface.PublicWebInputDefinition
  MarginSettings: TradeServer.Cluster.WebServer.Servers.RestServerInterface.PublicWebInputDefinition
  Version: TradeServer.Cluster.WebServer.Servers.RestServerInterface.PublicWebInputDefinition

