<?php
// <summary>
// This file has been generated by Haasonline Trade Server v4.0.7.102
// Production date: 11/4/2025
// </summary>

namespace HaasomeApi\HaasCloud\WebServices;

class HaasScriptAPI
{
    private $connection;
    public HaasScriptAPI($conn)
    {
        $connection = $conn;
    }

    /// <summary>
    /// 
    /// </summary>
    /// <returns></returns>
    function GetCommands()
    {
        return $connection->DoCall("HaasScriptAPI", "GET_COMMANDS");
    }

    /// <summary>
    /// 
    /// </summary>
    /// <returns></returns>
    function GetBlocks()
    {
        return $connection->DoCall("HaasScriptAPI", "GET_BLOCKS");
    }

    /// <summary>
    /// 
    /// </summary>
    /// <param name="scriptid"></param>
    /// <returns></returns>
    function GetCommand($scriptid)
    {
        return $connection->DoCall("HaasScriptAPI", "GET_COMMAND", array(
        [
           "scriptid" = $scriptid,
        ];
    }

    /// <summary>
    /// 
    /// </summary>
    /// <param name="scriptid"></param>
    /// <returns></returns>
    function GetBlock($scriptid)
    {
        return $connection->DoCall("HaasScriptAPI", "GET_BLOCK", array(
        [
           "scriptid" = $scriptid,
        ];
    }

    /// <summary>
    /// 
    /// </summary>
    /// <param name="scriptid"></param>
    /// <returns></returns>
    function GetScriptItem($scriptid)
    {
        return $connection->DoCall("HaasScriptAPI", "GET_SCRIPT_ITEM", array(
        [
           "scriptid" = $scriptid,
        ];
    }

    /// <summary>
    /// 
    /// </summary>
    /// <returns></returns>
    function GetAllScriptItems()
    {
        return $connection->DoCall("HaasScriptAPI", "GET_ALL_SCRIPT_ITEMS");
    }

    /// <summary>
    /// 
    /// </summary>
    /// <returns></returns>
    function GetScriptCommands()
    {
        return $connection->DoCall("HaasScriptAPI", "GET_SCRIPT_COMMANDS");
    }

    /// <summary>
    /// 
    /// </summary>
    /// <param name="scriptid"></param>
    /// <returns></returns>
    function GetScriptRecord($scriptid)
    {
        return $connection->DoCall("HaasScriptAPI", "GET_SCRIPT_RECORD", array(
        [
           "scriptid" = $scriptid,
        ];
    }

    /// <summary>
    /// 
    /// </summary>
    /// <returns></returns>
    function GetAllScriptRecords()
    {
        return $connection->DoCall("HaasScriptAPI", "GET_ALL_SCRIPT_RECORDS");
    }

    /// <summary>
    /// 
    /// </summary>
    /// <param name="name"></param>
    /// <param name="description"></param>
    /// <param name="script"></param>
    /// <param name="type"></param>
    /// <returns></returns>
    function AddScript($name,$description,$script,$type)
    {
        return $connection->DoCall("HaasScriptAPI", "ADD_SCRIPT", array(
        [
           "name" = $name,,
           "description" = $description,,
           "script" = $script,,
           "type" = $type,
        ];
    }

    /// <summary>
    /// 
    /// </summary>
    /// <param name="record"></param>
    /// <returns></returns>
    function AddScriptEnterprise($record)
    {
        $connection->DoCall("HaasScriptAPI", "ADD_SCRIPT_ENTERPRISE", array(
        [
           "record" = $record,
        ];
    }

    /// <summary>
    /// 
    /// </summary>
    /// <param name="scriptid"></param>
    /// <param name="name"></param>
    /// <param name="description"></param>
    /// <param name="script"></param>
    /// <returns></returns>
    function EditScript($scriptid,$name,$description,$script)
    {
        $connection->DoCall("HaasScriptAPI", "EDIT_SCRIPT", array(
        [
           "scriptid" = $scriptid,,
           "name" = $name,,
           "description" = $description,,
           "script" = $script,
        ];
    }

    /// <summary>
    /// 
    /// </summary>
    /// <param name="scriptid"></param>
    /// <param name="scriptname"></param>
    /// <param name="scriptdescription"></param>
    /// <param name="record"></param>
    /// <returns></returns>
    function EditScriptEnterprise($scriptid,$scriptname,$scriptdescription,$record)
    {
        $connection->DoCall("HaasScriptAPI", "EDIT_SCRIPT_ENTERPRISE", array(
        [
           "scriptid" = $scriptid,,
           "scriptname" = $scriptname,,
           "scriptdescription" = $scriptdescription,,
           "record" = $record,
        ];
    }

    /// <summary>
    /// 
    /// </summary>
    /// <param name="scriptid"></param>
    /// <param name="sourcecode"></param>
    /// <param name="settings"></param>
    /// <returns></returns>
    function EditScriptSourcecode($scriptid,$sourcecode,$settings)
    {
        $connection->DoCall("HaasScriptAPI", "EDIT_SCRIPT_SOURCECODE", array(
        [
           "scriptid" = $scriptid,,
           "sourcecode" = $sourcecode,,
           "settings" = $settings,
        ];
    }

    /// <summary>
    /// 
    /// </summary>
    /// <param name="scriptid"></param>
    /// <param name="record"></param>
    /// <returns></returns>
    function EditScriptSourcecodeEnterprise($scriptid,$record)
    {
        $connection->DoCall("HaasScriptAPI", "EDIT_SCRIPT_SOURCECODE_ENTERPRISE", array(
        [
           "scriptid" = $scriptid,,
           "record" = $record,
        ];
    }

    /// <summary>
    /// 
    /// </summary>
    /// <param name="record"></param>
    /// <param name="missingcommands"></param>
    /// <returns></returns>
    function CreateExecutionPackagesForEnterprise($record,$missingcommands)
    {
        $connection->DoCall("HaasScriptAPI", "CREATE_EXECUTION_PACKAGES_FOR_ENTERPRISE", array(
        [
           "record" = $record,,
           "missingcommands" = $missingcommands,
        ];
    }

    /// <summary>
    /// 
    /// </summary>
    /// <param name="scriptid"></param>
    /// <param name="name"></param>
    /// <param name="description"></param>
    /// <returns></returns>
    function EditScriptSpecifications($scriptid,$name,$description)
    {
        return $connection->DoCall("HaasScriptAPI", "EDIT_SCRIPT_SPECIFICATIONS", array(
        [
           "scriptid" = $scriptid,,
           "name" = $name,,
           "description" = $description,
        ];
    }

    /// <summary>
    /// 
    /// </summary>
    /// <param name="scriptid"></param>
    /// <returns></returns>
    function GetScriptExecutionPackage($scriptid)
    {
        $connection->DoCall("HaasScriptAPI", "GET_SCRIPT_EXECUTION_PACKAGE", array(
        [
           "scriptid" = $scriptid,
        ];
    }

    /// <summary>
    /// 
    /// </summary>
    /// <param name="scriptid"></param>
    /// <returns></returns>
    function DeleteScript($scriptid)
    {
        return $connection->DoCall("HaasScriptAPI", "DELETE_SCRIPT", array(
        [
           "scriptid" = $scriptid,
        ];
    }

    /// <summary>
    /// 
    /// </summary>
    /// <param name="scriptid"></param>
    /// <returns></returns>
    function PublishScript($scriptid)
    {
        return $connection->DoCall("HaasScriptAPI", "PUBLISH_SCRIPT", array(
        [
           "scriptid" = $scriptid,
        ];
    }

    /// <summary>
    /// 
    /// </summary>
    /// <param name="scriptid"></param>
    /// <returns></returns>
    function PublishCommunityScript($scriptid)
    {
        return $connection->DoCall("HaasScriptAPI", "PUBLISH_COMMUNITY_SCRIPT", array(
        [
           "scriptid" = $scriptid,
        ];
    }

    /// <summary>
    /// 
    /// </summary>
    /// <param name="scriptid"></param>
    /// <returns></returns>
    function UnpublishScript($scriptid)
    {
        return $connection->DoCall("HaasScriptAPI", "UNPUBLISH_SCRIPT", array(
        [
           "scriptid" = $scriptid,
        ];
    }

    /// <summary>
    /// Returns a list of the backup versions
    /// </summary>
    /// <param name="scriptid"></param>
    /// <returns></returns>
    function GetBackupVersions($scriptid)
    {
        return $connection->DoCall("HaasScriptAPI", "GET_BACKUP_VERSIONS", array(
        [
           "scriptid" = $scriptid,
        ];
    }

    /// <summary>
    /// Creates a backup of the given script
    /// </summary>
    /// <param name="scriptid"></param>
    /// <returns></returns>
    function CreateNewBackup($scriptid)
    {
        return $connection->DoCall("HaasScriptAPI", "CREATE_NEW_BACKUP", array(
        [
           "scriptid" = $scriptid,
        ];
    }

    /// <summary>
    /// Restores a backup
    /// </summary>
    /// <param name="scriptid"></param>
    /// <param name="wantedversion"></param>
    /// <returns></returns>
    function RestoreBackup($scriptid,$wantedversion)
    {
        return $connection->DoCall("HaasScriptAPI", "RESTORE_BACKUP", array(
        [
           "scriptid" = $scriptid,,
           "wantedversion" = $wantedversion,
        ];
    }

    /// <summary>
    /// Opens the backup file as new script
    /// </summary>
    /// <param name="scriptid"></param>
    /// <param name="wantedversion"></param>
    /// <returns></returns>
    function GetBackup($scriptid,$wantedversion)
    {
        return $connection->DoCall("HaasScriptAPI", "GET_BACKUP", array(
        [
           "scriptid" = $scriptid,,
           "wantedversion" = $wantedversion,
        ];
    }

    /// <summary>
    /// Searches to find code within the scripts
    /// </summary>
    /// <param name="searchkey"></param>
    /// <returns></returns>
    function SearchInScripts($searchkey)
    {
        return $connection->DoCall("HaasScriptAPI", "SEARCH_IN_SCRIPTS", array(
        [
           "searchkey" = $searchkey,
        ];
    }

    /// <summary>
    /// Returns a shareId
    /// </summary>
    /// <param name="scriptid"></param>
    /// <param name="scriptname"></param>
    /// <param name="scriptdescription"></param>
    /// <param name="status"></param>
    /// <param name="allowedusers"></param>
    /// <returns></returns>
    function ShareScript($scriptid,$scriptname,$scriptdescription,$status,$allowedusers)
    {
        return $connection->DoCall("HaasScriptAPI", "SHARE_SCRIPT", array(
        [
           "scriptid" = $scriptid,,
           "scriptname" = $scriptname,,
           "scriptdescription" = $scriptdescription,,
           "status" = $status,,
           "allowedusers" = $allowedusers,
        ];
    }

    /// <summary>
    /// Returns a shared script
    /// </summary>
    /// <param name="pagesize"></param>
    /// <returns></returns>
    function GetLatestSharedScript($pagesize)
    {
        return $connection->DoCall("HaasScriptAPI", "GET_LATEST_SHARED_SCRIPT", array(
        [
           "pagesize" = $pagesize,
        ];
    }

    /// <summary>
    /// Returns a shared script
    /// </summary>
    /// <param name="shareid"></param>
    /// <returns></returns>
    function GetSharedScript($shareid)
    {
        return $connection->DoCall("HaasScriptAPI", "GET_SHARED_SCRIPT", array(
        [
           "shareid" = $shareid,
        ];
    }

    /// <summary>
    /// Returns a shared script
    /// </summary>
    /// <param name="shareid"></param>
    /// <returns></returns>
    function GetSharedScriptWithAuth($shareid)
    {
        return $connection->DoCall("HaasScriptAPI", "GET_SHARED_SCRIPT_WITH_AUTH", array(
        [
           "shareid" = $shareid,
        ];
    }

    /// <summary>
    /// Returns a shared script
    /// </summary>
    /// <param name="shareid"></param>
    /// <returns></returns>
    function SaveSharedScript($shareid)
    {
        return $connection->DoCall("HaasScriptAPI", "SAVE_SHARED_SCRIPT", array(
        [
           "shareid" = $shareid,
        ];
    }

    /// <summary>
    /// Increases the view count for a specific shared script
    /// </summary>
    /// <param name="shareid"></param>
    /// <returns></returns>
    function SharedScriptViewed($shareid)
    {
        return $connection->DoCall("HaasScriptAPI", "SHARED_SCRIPT_VIEWED", array(
        [
           "shareid" = $shareid,
        ];
    }

    /// <summary>
    /// Increases the view count for a specific shared script
    /// </summary>
    /// <param name="shareid"></param>
    /// <returns></returns>
    function SharedScriptForked($shareid)
    {
        return $connection->DoCall("HaasScriptAPI", "SHARED_SCRIPT_FORKED", array(
        [
           "shareid" = $shareid,
        ];
    }

    /// <summary>
    /// Increases the view count for a specific shared script
    /// </summary>
    /// <param name="shareid"></param>
    /// <returns></returns>
    function SharedScriptDownloaded($shareid)
    {
        return $connection->DoCall("HaasScriptAPI", "SHARED_SCRIPT_DOWNLOADED", array(
        [
           "shareid" = $shareid,
        ];
    }

    /// <summary>
    /// Increases the view count for a specific shared script
    /// </summary>
    /// <param name="shareid"></param>
    /// <returns></returns>
    function DeleteSharedScript($shareid)
    {
        return $connection->DoCall("HaasScriptAPI", "DELETE_SHARED_SCRIPT", array(
        [
           "shareid" = $shareid,
        ];
    }

    /// <summary>
    /// Returns the folders of a specific user
    /// </summary>
    /// <returns></returns>
    function GetAllScriptFolders()
    {
        return $connection->DoCall("HaasScriptAPI", "GET_ALL_SCRIPT_FOLDERS");
    }

    /// <summary>
    /// Creates a folder for a specific user
    /// </summary>
    /// <param name="foldername"></param>
    /// <param name="parentid"></param>
    /// <returns></returns>
    function CreateFolder($foldername,$parentid)
    {
        return $connection->DoCall("HaasScriptAPI", "CREATE_FOLDER", array(
        [
           "foldername" = $foldername,,
           "parentid" = $parentid,
        ];
    }

    /// <summary>
    /// Returns the folders of a specific user
    /// </summary>
    /// <param name="folderid"></param>
    /// <param name="name"></param>
    /// <returns></returns>
    function EditFolder($folderid,$name)
    {
        return $connection->DoCall("HaasScriptAPI", "EDIT_FOLDER", array(
        [
           "folderid" = $folderid,,
           "name" = $name,
        ];
    }

    /// <summary>
    /// Returns the folders of a specific user
    /// </summary>
    /// <param name="folderid"></param>
    /// <returns></returns>
    function DeleteFolder($folderid)
    {
        return $connection->DoCall("HaasScriptAPI", "DELETE_FOLDER", array(
        [
           "folderid" = $folderid,
        ];
    }

    /// <summary>
    /// Creates a folder for a specific user
    /// </summary>
    /// <param name="scriptid"></param>
    /// <param name="folderid"></param>
    /// <returns></returns>
    function MoveScriptToFolder($scriptid,$folderid)
    {
        return $connection->DoCall("HaasScriptAPI", "MOVE_SCRIPT_TO_FOLDER", array(
        [
           "scriptid" = $scriptid,,
           "folderid" = $folderid,
        ];
    }
}
