<?php
// <summary>
// This file has been generated by Haasonline Trade Server v4.0.7.102
// Production date: 11/4/2025
// </summary>

namespace HaasomeApi\HaasCloud\WebServices;

class InterfaceAPI
{
    private $connection;
    public InterfaceAPI($conn)
    {
        $connection = $conn;
    }

    /// <summary>
    /// 
    /// </summary>
    /// <param name="ct"></param>
    /// <returns></returns>
    function Initialize($ct)
    {
        $connection->DoCall("InterfaceAPI", "Initialize", array(
        [
           "ct" = $ct,
        ];
    }

    /// <summary>
    /// Returns the market information page
    /// </summary>
    /// <param name="market">Name of the market, like BINANCE_BTC_USDT_</param>
    /// <returns></returns>
    function MarketInfo($market)
    {
        return $connection->DoCall("InterfaceAPI", "MARKET_INFO", array(
        [
           "market" = $market,
        ];
    }

    /// <summary>
    /// Returns the market price information page
    /// </summary>
    /// <param name="market">Name of the market, like BINANCE_BTC_USDT_</param>
    /// <returns></returns>
    function MarketPriceInfo($market)
    {
        return $connection->DoCall("InterfaceAPI", "MARKET_PRICE_INFO", array(
        [
           "market" = $market,
        ];
    }

    /// <summary>
    /// Returns the market price technical analysis page
    /// </summary>
    /// <param name="market">Name of the market, like BINANCE_BTC_USDT_</param>
    /// <returns></returns>
    function MarketTaInfo($market)
    {
        return $connection->DoCall("InterfaceAPI", "MARKET_TA_INFO", array(
        [
           "market" = $market,
        ];
    }

    /// <summary>
    /// Sends a question to ChatAI Bot Julia (support)
    /// </summary>
    /// <param name="chatid"></param>
    /// <param name="message"></param>
    /// <returns></returns>
    function AskJulia($chatid,$message)
    {
        return $connection->DoCall("InterfaceAPI", "ASK_JULIA", array(
        [
           "chatid" = $chatid,,
           "message" = $message,
        ];
    }

    /// <summary>
    /// Sends a question to ChatAI Bot Thomas (haasscript)
    /// </summary>
    /// <param name="chatid"></param>
    /// <param name="message"></param>
    /// <returns></returns>
    function AskThomas($chatid,$message)
    {
        return $connection->DoCall("InterfaceAPI", "ASK_THOMAS", array(
        [
           "chatid" = $chatid,,
           "message" = $message,
        ];
    }

    /// <summary>
    /// Sends a question to ChatAI Bot Simone (news tracker)
    /// </summary>
    /// <param name="chatid"></param>
    /// <param name="message"></param>
    /// <returns></returns>
    function AskSimone($chatid,$message)
    {
        return $connection->DoCall("InterfaceAPI", "ASK_SIMONE", array(
        [
           "chatid" = $chatid,,
           "message" = $message,
        ];
    }

    /// <summary>
    /// Sends a question to ChatAI Bot David (crypto guru)
    /// </summary>
    /// <param name="chatid"></param>
    /// <param name="message"></param>
    /// <returns></returns>
    function AskDavid($chatid,$message)
    {
        return $connection->DoCall("InterfaceAPI", "ASK_DAVID", array(
        [
           "chatid" = $chatid,,
           "message" = $message,
        ];
    }

    /// <summary>
    /// Sends a question to one of the ChatAI bots
    /// </summary>
    /// <param name="bot"></param>
    /// <param name="chatid"></param>
    /// <param name="messageid"></param>
    /// <param name="message"></param>
    /// <returns></returns>
    function AskQuestion($bot,$chatid,$messageid,$message)
    {
        return $connection->DoCall("InterfaceAPI", "ASK_QUESTION", array(
        [
           "bot" = $bot,,
           "chatid" = $chatid,,
           "messageid" = $messageid,,
           "message" = $message,
        ];
    }
}
