<?php
// <summary>
// This file has been generated by Haasonline Trade Server v4.0.7.102
// Production date: 11/4/2025
// </summary>

namespace HaasomeApi\HaasCloud\WebServices;

class PortfolioAPI
{
    private $connection;
    public PortfolioAPI($conn)
    {
        $connection = $conn;
    }

    /// <summary>
    /// Returns the wallet and total balance
    /// </summary>
    /// <param name="pricesource">Name of the pricesource, like BINANCE</param>
    /// <param name="fromcurrency"></param>
    /// <param name="tocurrency"></param>
    /// <param name="amount"></param>
    /// <param name="timestamp"></param>
    /// <returns></returns>
    function Convert($pricesource,$fromcurrency,$tocurrency,$amount,$timestamp)
    {
        return $connection->DoCall("PortfolioAPI", "CONVERT", array(
        [
           "pricesource" = $pricesource,,
           "fromcurrency" = $fromcurrency,,
           "tocurrency" = $tocurrency,,
           "amount" = $amount,,
           "timestamp" = $timestamp,
        ];
    }

    /// <summary>
    /// Returns the balance mutation per user
    /// </summary>
    /// <param name="accountids"></param>
    /// <param name="nextpageid"></param>
    /// <param name="pagelength"></param>
    /// <returns></returns>
    function GetBalanceMutations($accountids,$nextpageid,$pagelength)
    {
        return $connection->DoCall("PortfolioAPI", "GET_BALANCE_MUTATIONS", array(
        [
           "accountids" = $accountids,,
           "nextpageid" = $nextpageid,,
           "pagelength" = $pagelength,
        ];
    }

    /// <summary>
    /// Returns the balance mutation per user
    /// </summary>
    /// <returns></returns>
    function GetTicks()
    {
        return $connection->DoCall("PortfolioAPI", "GET_TICKS");
    }

    /// <summary>
    /// Returns the balance mutation per user
    /// </summary>
    /// <param name="market">Name of the market, like BINANCE_BTC_USDT_</param>
    /// <param name="startunix"></param>
    /// <param name="endunix"></param>
    /// <returns></returns>
    function GetRange($market,$startunix,$endunix)
    {
        return $connection->DoCall("PortfolioAPI", "GET_RANGE", array(
        [
           "market" = $market,,
           "startunix" = $startunix,,
           "endunix" = $endunix,
        ];
    }
}
