<?php
// <summary>
// This file has been generated by Haasonline Trade Server v4.0.7.102
// Production date: 11/4/2025
// </summary>

namespace HaasomeApi\HaasCloud\WebServices;

class SignalAPI
{
    private $connection;
    public SignalAPI($conn)
    {
        $connection = $conn;
    }

    /// <summary>
    /// Use this webhook to send signals to the HaasCloud
    /// </summary>
    /// <param name="id"></param>
    /// <param name="secret"></param>
    /// <param name="signal"></param>
    /// <returns></returns>
    function StoreSignal($id,$secret,$signal)
    {
        return $connection->DoCall("SignalAPI", "STORE_SIGNAL", array(
        [
           "id" = $id,,
           "secret" = $secret,,
           "signal" = $signal,
        ];
    }

    /// <summary>
    /// This returns a list of all the user its signals
    /// </summary>
    /// <returns></returns>
    function MySignals()
    {
        return $connection->DoCall("SignalAPI", "MY_SIGNALS");
    }

    /// <summary>
    /// 
    /// </summary>
    /// <param name="id"></param>
    /// <param name="action"></param>
    /// <param name="investmenttype"></param>
    /// <param name="amount"></param>
    /// <param name="maxlag"></param>
    /// <param name="timestamp"></param>
    /// <returns></returns>
    function PushSignal($id,$action,$investmenttype,$amount,$maxlag,$timestamp)
    {
        $connection->DoCall("SignalAPI", "PUSH_SIGNAL", array(
        [
           "id" = $id,,
           "action" = $action,,
           "investmenttype" = $investmenttype,,
           "amount" = $amount,,
           "maxlag" = $maxlag,,
           "timestamp" = $timestamp,
        ];
    }
}
