from dataclasses import dataclass
// <summary>
// This file has been generated by Haasonline Trade Server v4.0.7.102
// Production date: 11/4/2025
// </summary>

@dataclass
class AppLoginResult:
  IsSuccess: TradeServer.Cluster.WebServer.Servers.RestServerInterface.PublicWebInputDefinition
  Error: TradeServer.Cluster.WebServer.Servers.RestServerInterface.PublicWebInputDefinition
  Details: TradeServer.Cluster.WebServer.Servers.RestServerInterface.PublicWebInputDefinition

