from dataclasses import dataclass
// <summary>
// This file has been generated by Haasonline Trade Server v4.0.7.102
// Production date: 11/4/2025
// </summary>

@dataclass
class CloudMarket:
  PriceSource: TradeServer.Cluster.WebServer.Servers.RestServerInterface.PublicWebInputDefinition
  Primary: TradeServer.Cluster.WebServer.Servers.RestServerInterface.PublicWebInputDefinition
  Secondary: TradeServer.Cluster.WebServer.Servers.RestServerInterface.PublicWebInputDefinition
  ContractName: TradeServer.Cluster.WebServer.Servers.RestServerInterface.PublicWebInputDefinition
  ShortName: TradeServer.Cluster.WebServer.Servers.RestServerInterface.PublicWebInputDefinition
  WalletTag: TradeServer.Cluster.WebServer.Servers.RestServerInterface.PublicWebInputDefinition

