from dataclasses import dataclass
// <summary>
// This file has been generated by Haasonline Trade Server v4.0.7.102
// Production date: 11/4/2025
// </summary>

@dataclass
class CloudPriceSource:
  ExchangeFamily: TradeServer.Cluster.WebServer.Servers.RestServerInterface.PublicWebInputDefinition
  ExchangeName: TradeServer.Cluster.WebServer.Servers.RestServerInterface.PublicWebInputDefinition
  ExchangeCode: TradeServer.Cluster.WebServer.Servers.RestServerInterface.PublicWebInputDefinition
  ExchangeColor: TradeServer.Cluster.WebServer.Servers.RestServerInterface.PublicWebInputDefinition
  SpotTrading: TradeServer.Cluster.WebServer.Servers.RestServerInterface.PublicWebInputDefinition
  MarginTrading: TradeServer.Cluster.WebServer.Servers.RestServerInterface.PublicWebInputDefinition
  LeverageTrading: TradeServer.Cluster.WebServer.Servers.RestServerInterface.PublicWebInputDefinition
  HasTestNetSupport: TradeServer.Cluster.WebServer.Servers.RestServerInterface.PublicWebInputDefinition
  ApiVersions: TradeServer.Cluster.WebServer.Servers.RestServerInterface.PublicWebInputDefinition
  AuthenticationMethods: TradeServer.Cluster.WebServer.Servers.RestServerInterface.PublicWebInputDefinition
  PublicKeyLabel: TradeServer.Cluster.WebServer.Servers.RestServerInterface.PublicWebInputDefinition
  SecretKeyLabel: TradeServer.Cluster.WebServer.Servers.RestServerInterface.PublicWebInputDefinition
  AdditionalFieldLabel: TradeServer.Cluster.WebServer.Servers.RestServerInterface.PublicWebInputDefinition
  OAuth: TradeServer.Cluster.WebServer.Servers.RestServerInterface.PublicWebInputDefinition
  PublicKeyRules: TradeServer.Cluster.WebServer.Servers.RestServerInterface.PublicWebInputDefinition
  SecretKeyRules: TradeServer.Cluster.WebServer.Servers.RestServerInterface.PublicWebInputDefinition
  AdditionalKeyRules: TradeServer.Cluster.WebServer.Servers.RestServerInterface.PublicWebInputDefinition
  Location: TradeServer.Cluster.WebServer.Servers.RestServerInterface.PublicWebInputDefinition
  FoundedYear: TradeServer.Cluster.WebServer.Servers.RestServerInterface.PublicWebInputDefinition
  AffiliationLink: TradeServer.Cluster.WebServer.Servers.RestServerInterface.PublicWebInputDefinition
  Website: TradeServer.Cluster.WebServer.Servers.RestServerInterface.PublicWebInputDefinition
  Email: TradeServer.Cluster.WebServer.Servers.RestServerInterface.PublicWebInputDefinition
  Twitter: TradeServer.Cluster.WebServer.Servers.RestServerInterface.PublicWebInputDefinition
  Telegram: TradeServer.Cluster.WebServer.Servers.RestServerInterface.PublicWebInputDefinition
  Facebook: TradeServer.Cluster.WebServer.Servers.RestServerInterface.PublicWebInputDefinition
  Discord: TradeServer.Cluster.WebServer.Servers.RestServerInterface.PublicWebInputDefinition
  GitBookApi: TradeServer.Cluster.WebServer.Servers.RestServerInterface.PublicWebInputDefinition
  Rating: TradeServer.Cluster.WebServer.Servers.RestServerInterface.PublicWebInputDefinition
  IsForexDriver: TradeServer.Cluster.WebServer.Servers.RestServerInterface.PublicWebInputDefinition
  IsLoginRequired: TradeServer.Cluster.WebServer.Servers.RestServerInterface.PublicWebInputDefinition
  IsBetaDriver: TradeServer.Cluster.WebServer.Servers.RestServerInterface.PublicWebInputDefinition

