from dataclasses import dataclass
// <summary>
// This file has been generated by Haasonline Trade Server v4.0.7.102
// Production date: 11/4/2025
// </summary>

@dataclass
class HaasChartDataLine:
  Guid: TradeServer.Cluster.WebServer.Servers.RestServerInterface.PublicWebInputDefinition
  Name: TradeServer.Cluster.WebServer.Servers.RestServerInterface.PublicWebInputDefinition
  Interval: TradeServer.Cluster.WebServer.Servers.RestServerInterface.PublicWebInputDefinition
  Color: TradeServer.Cluster.WebServer.Servers.RestServerInterface.PublicWebInputDefinition
  Width: TradeServer.Cluster.WebServer.Servers.RestServerInterface.PublicWebInputDefinition
  Type: TradeServer.Cluster.WebServer.Servers.RestServerInterface.PublicWebInputDefinition
  Style: TradeServer.Cluster.WebServer.Servers.RestServerInterface.PublicWebInputDefinition
  Decoration: TradeServer.Cluster.WebServer.Servers.RestServerInterface.PublicWebInputDefinition
  Side: TradeServer.Cluster.WebServer.Servers.RestServerInterface.PublicWebInputDefinition
  LineShapeType: TradeServer.Cluster.WebServer.Servers.RestServerInterface.PublicWebInputDefinition
  Visible: TradeServer.Cluster.WebServer.Servers.RestServerInterface.PublicWebInputDefinition
  Behind: TradeServer.Cluster.WebServer.Servers.RestServerInterface.PublicWebInputDefinition
  IgnoreOnAxis: TradeServer.Cluster.WebServer.Servers.RestServerInterface.PublicWebInputDefinition
  DrawTrailingLine: TradeServer.Cluster.WebServer.Servers.RestServerInterface.PublicWebInputDefinition
  FixedValue: TradeServer.Cluster.WebServer.Servers.RestServerInterface.PublicWebInputDefinition
  ConnectedLines: TradeServer.Cluster.WebServer.Servers.RestServerInterface.PublicWebInputDefinition
  DataSets: TradeServer.Cluster.WebServer.Servers.RestServerInterface.PublicWebInputDefinition
  DataPoints: TradeServer.Cluster.WebServer.Servers.RestServerInterface.PublicWebInputDefinition

