from dataclasses import dataclass
// <summary>
// This file has been generated by Haasonline Trade Server v4.0.7.102
// Production date: 11/4/2025
// </summary>

@dataclass
class HaasScriptBacktestRecord:
  RecordId: TradeServer.Cluster.WebServer.Servers.RestServerInterface.PublicWebInputDefinition
  Unix: TradeServer.Cluster.WebServer.Servers.RestServerInterface.PublicWebInputDefinition
  UserId: TradeServer.Cluster.WebServer.Servers.RestServerInterface.PublicWebInputDefinition
  BacktestId: TradeServer.Cluster.WebServer.Servers.RestServerInterface.PublicWebInputDefinition
  BacktestStart: TradeServer.Cluster.WebServer.Servers.RestServerInterface.PublicWebInputDefinition
  BacktestEnd: TradeServer.Cluster.WebServer.Servers.RestServerInterface.PublicWebInputDefinition
  BacktestTag: TradeServer.Cluster.WebServer.Servers.RestServerInterface.PublicWebInputDefinition
  ExecutionStart: TradeServer.Cluster.WebServer.Servers.RestServerInterface.PublicWebInputDefinition
  ExecutionEnd: TradeServer.Cluster.WebServer.Servers.RestServerInterface.PublicWebInputDefinition
  ScriptTag: TradeServer.Cluster.WebServer.Servers.RestServerInterface.PublicWebInputDefinition
  AccountTag: TradeServer.Cluster.WebServer.Servers.RestServerInterface.PublicWebInputDefinition
  MarketTag: TradeServer.Cluster.WebServer.Servers.RestServerInterface.PublicWebInputDefinition
  ProfitTags: TradeServer.Cluster.WebServer.Servers.RestServerInterface.PublicWebInputDefinition
  ROITags: TradeServer.Cluster.WebServer.Servers.RestServerInterface.PublicWebInputDefinition
  IsArchived: TradeServer.Cluster.WebServer.Servers.RestServerInterface.PublicWebInputDefinition
  Runtime: TradeServer.Cluster.WebServer.Servers.RestServerInterface.PublicWebInputDefinition
  Chart: TradeServer.Cluster.WebServer.Servers.RestServerInterface.PublicWebInputDefinition
  Logs: TradeServer.Cluster.WebServer.Servers.RestServerInterface.PublicWebInputDefinition

