from dataclasses import dataclass
// <summary>
// This file has been generated by Haasonline Trade Server v4.0.7.102
// Production date: 11/4/2025
// </summary>

@dataclass
class HaasScriptShared:
  ShareId: TradeServer.Cluster.WebServer.Servers.RestServerInterface.PublicWebInputDefinition
  Status: TradeServer.Cluster.WebServer.Servers.RestServerInterface.PublicWebInputDefinition
  Timestamp: TradeServer.Cluster.WebServer.Servers.RestServerInterface.PublicWebInputDefinition
  Author: TradeServer.Cluster.WebServer.Servers.RestServerInterface.PublicWebInputDefinition
  SourceCode: TradeServer.Cluster.WebServer.Servers.RestServerInterface.PublicWebInputDefinition
  ScriptType: TradeServer.Cluster.WebServer.Servers.RestServerInterface.PublicWebInputDefinition
  ScriptName: TradeServer.Cluster.WebServer.Servers.RestServerInterface.PublicWebInputDefinition
  ScriptDescription: TradeServer.Cluster.WebServer.Servers.RestServerInterface.PublicWebInputDefinition
  CommandRecords: TradeServer.Cluster.WebServer.Servers.RestServerInterface.PublicWebInputDefinition
  LuaCommands: TradeServer.Cluster.WebServer.Servers.RestServerInterface.PublicWebInputDefinition
  VisualCommands: TradeServer.Cluster.WebServer.Servers.RestServerInterface.PublicWebInputDefinition
  Version: TradeServer.Cluster.WebServer.Servers.RestServerInterface.PublicWebInputDefinition
  Versions: TradeServer.Cluster.WebServer.Servers.RestServerInterface.PublicWebInputDefinition
  ViewCount: TradeServer.Cluster.WebServer.Servers.RestServerInterface.PublicWebInputDefinition
  ForkCount: TradeServer.Cluster.WebServer.Servers.RestServerInterface.PublicWebInputDefinition
  DownloadCount: TradeServer.Cluster.WebServer.Servers.RestServerInterface.PublicWebInputDefinition

