from dataclasses import dataclass
// <summary>
// This file has been generated by Haasonline Trade Server v4.0.7.102
// Production date: 11/4/2025
// </summary>

@dataclass
class HaasScriptOlderVersion:
  Id: TradeServer.Cluster.WebServer.Servers.RestServerInterface.PublicWebInputDefinition
  ScriptId: TradeServer.Cluster.WebServer.Servers.RestServerInterface.PublicWebInputDefinition
  Version: TradeServer.Cluster.WebServer.Servers.RestServerInterface.PublicWebInputDefinition
  Created: TradeServer.Cluster.WebServer.Servers.RestServerInterface.PublicWebInputDefinition
  SourceCode: TradeServer.Cluster.WebServer.Servers.RestServerInterface.PublicWebInputDefinition

