from dataclasses import dataclass
// <summary>
// This file has been generated by Haasonline Trade Server v4.0.7.102
// Production date: 11/4/2025
// </summary>

@dataclass
class HaasChartPricePlot:
  Market: TradeServer.Cluster.WebServer.Servers.RestServerInterface.PublicWebInputDefinition
  Interval: TradeServer.Cluster.WebServer.Servers.RestServerInterface.PublicWebInputDefinition
  Candles: TradeServer.Cluster.WebServer.Servers.RestServerInterface.PublicWebInputDefinition
  Colors: TradeServer.Cluster.WebServer.Servers.RestServerInterface.PublicWebInputDefinition
  Style: TradeServer.Cluster.WebServer.Servers.RestServerInterface.PublicWebInputDefinition
  Side: TradeServer.Cluster.WebServer.Servers.RestServerInterface.PublicWebInputDefinition

