from dataclasses import dataclass
// <summary>
// This file has been generated by Haasonline Trade Server v4.0.7.102
// Production date: 11/4/2025
// </summary>

@dataclass
class HaasChartColorScheme:
  Font: TradeServer.Cluster.WebServer.Servers.RestServerInterface.PublicWebInputDefinition
  Axis: TradeServer.Cluster.WebServer.Servers.RestServerInterface.PublicWebInputDefinition
  Grid: TradeServer.Cluster.WebServer.Servers.RestServerInterface.PublicWebInputDefinition
  Text: TradeServer.Cluster.WebServer.Servers.RestServerInterface.PublicWebInputDefinition
  Background: TradeServer.Cluster.WebServer.Servers.RestServerInterface.PublicWebInputDefinition
  PriceGhostLine: TradeServer.Cluster.WebServer.Servers.RestServerInterface.PublicWebInputDefinition
  VolumeGhostLine: TradeServer.Cluster.WebServer.Servers.RestServerInterface.PublicWebInputDefinition

