from dataclasses import dataclass
// <summary>
// This file has been generated by Haasonline Trade Server v4.0.7.102
// Production date: 11/4/2025
// </summary>

@dataclass
class HaasBotPositionRecord:
  RecordId: TradeServer.Cluster.WebServer.Servers.RestServerInterface.PublicWebInputDefinition
  BotId: TradeServer.Cluster.WebServer.Servers.RestServerInterface.PublicWebInputDefinition
  PositionId: TradeServer.Cluster.WebServer.Servers.RestServerInterface.PublicWebInputDefinition
  PositionTag: TradeServer.Cluster.WebServer.Servers.RestServerInterface.PublicWebInputDefinition
  Position: TradeServer.Cluster.WebServer.Servers.RestServerInterface.PublicWebInputDefinition
  OpenTime: TradeServer.Cluster.WebServer.Servers.RestServerInterface.PublicWebInputDefinition
  CloseTime: TradeServer.Cluster.WebServer.Servers.RestServerInterface.PublicWebInputDefinition
  Profits: TradeServer.Cluster.WebServer.Servers.RestServerInterface.PublicWebInputDefinition

