from dataclasses import dataclass
// <summary>
// This file has been generated by Haasonline Trade Server v4.0.7.102
// Production date: 11/4/2025
// </summary>

@dataclass
class HaasScriptItemWithDependencies:
  Dependencies: TradeServer.Cluster.WebServer.Servers.RestServerInterface.PublicWebInputDefinition
  CompileResult: TradeServer.Cluster.WebServer.Servers.RestServerInterface.PublicWebInputDefinition
  UserId: TradeServer.Cluster.WebServer.Servers.RestServerInterface.PublicWebInputDefinition
  ScriptId: TradeServer.Cluster.WebServer.Servers.RestServerInterface.PublicWebInputDefinition
  ScriptName: TradeServer.Cluster.WebServer.Servers.RestServerInterface.PublicWebInputDefinition
  ScriptDescription: TradeServer.Cluster.WebServer.Servers.RestServerInterface.PublicWebInputDefinition
  ScriptType: TradeServer.Cluster.WebServer.Servers.RestServerInterface.PublicWebInputDefinition
  ScriptStatus: TradeServer.Cluster.WebServer.Servers.RestServerInterface.PublicWebInputDefinition
  CommandName: TradeServer.Cluster.WebServer.Servers.RestServerInterface.PublicWebInputDefinition
  IsCommand: TradeServer.Cluster.WebServer.Servers.RestServerInterface.PublicWebInputDefinition
  IsValid: TradeServer.Cluster.WebServer.Servers.RestServerInterface.PublicWebInputDefinition
  CreatedUnix: TradeServer.Cluster.WebServer.Servers.RestServerInterface.PublicWebInputDefinition
  UpdatedUnix: TradeServer.Cluster.WebServer.Servers.RestServerInterface.PublicWebInputDefinition
  FolderId: TradeServer.Cluster.WebServer.Servers.RestServerInterface.PublicWebInputDefinition

