from dataclasses import dataclass
// <summary>
// This file has been generated by Haasonline Trade Server v4.0.7.102
// Production date: 11/4/2025
// </summary>

@dataclass
class MarketIndicatorTable:
  IndicatorName: TradeServer.Cluster.WebServer.Servers.RestServerInterface.PublicWebInputDefinition
  Intervals: TradeServer.Cluster.WebServer.Servers.RestServerInterface.PublicWebInputDefinition
  Rows: TradeServer.Cluster.WebServer.Servers.RestServerInterface.PublicWebInputDefinition

