from dataclasses import dataclass
// <summary>
// This file has been generated by Haasonline Trade Server v4.0.7.102
// Production date: 11/4/2025
// </summary>

@dataclass
class RuntimeOrdersReport:
  Filled: TradeServer.Cluster.WebServer.Servers.RestServerInterface.PublicWebInputDefinition
  PartiallyFilled: TradeServer.Cluster.WebServer.Servers.RestServerInterface.PublicWebInputDefinition
  Cancelled: TradeServer.Cluster.WebServer.Servers.RestServerInterface.PublicWebInputDefinition
  Failed: TradeServer.Cluster.WebServer.Servers.RestServerInterface.PublicWebInputDefinition
  Total: TradeServer.Cluster.WebServer.Servers.RestServerInterface.PublicWebInputDefinition
  AverageOpenTime: TradeServer.Cluster.WebServer.Servers.RestServerInterface.PublicWebInputDefinition
  LastCompletedOrder: TradeServer.Cluster.WebServer.Servers.RestServerInterface.PublicWebInputDefinition
  ProfitableTrades: TradeServer.Cluster.WebServer.Servers.RestServerInterface.PublicWebInputDefinition
  LoosingTrades: TradeServer.Cluster.WebServer.Servers.RestServerInterface.PublicWebInputDefinition
  BiggestWin: TradeServer.Cluster.WebServer.Servers.RestServerInterface.PublicWebInputDefinition
  BiggestLoss: TradeServer.Cluster.WebServer.Servers.RestServerInterface.PublicWebInputDefinition

