from dataclasses import dataclass
// <summary>
// This file has been generated by Haasonline Trade Server v4.0.7.102
// Production date: 11/4/2025
// </summary>

@dataclass
class RuntimeProfitReport:
  StartPrice: TradeServer.Cluster.WebServer.Servers.RestServerInterface.PublicWebInputDefinition
  StartBalance: TradeServer.Cluster.WebServer.Servers.RestServerInterface.PublicWebInputDefinition
  PriceChange: TradeServer.Cluster.WebServer.Servers.RestServerInterface.PublicWebInputDefinition
  BalanceChange: TradeServer.Cluster.WebServer.Servers.RestServerInterface.PublicWebInputDefinition
  GrossProfits: TradeServer.Cluster.WebServer.Servers.RestServerInterface.PublicWebInputDefinition
  RealizedProfits: TradeServer.Cluster.WebServer.Servers.RestServerInterface.PublicWebInputDefinition
  UnrealizedProfits: TradeServer.Cluster.WebServer.Servers.RestServerInterface.PublicWebInputDefinition
  ReturnOnInvestment: TradeServer.Cluster.WebServer.Servers.RestServerInterface.PublicWebInputDefinition
  RoiMargin: TradeServer.Cluster.WebServer.Servers.RestServerInterface.PublicWebInputDefinition
  CustomRoiMargin: TradeServer.Cluster.WebServer.Servers.RestServerInterface.PublicWebInputDefinition
  RealizedProfitsHistory: TradeServer.Cluster.WebServer.Servers.RestServerInterface.PublicWebInputDefinition
  ReturnOnInvestmentHistory: TradeServer.Cluster.WebServer.Servers.RestServerInterface.PublicWebInputDefinition

