from dataclasses import dataclass
// <summary>
// This file has been generated by Haasonline Trade Server v4.0.7.102
// Production date: 11/4/2025
// </summary>

@dataclass
class RuntimeReport:
  AccountId: TradeServer.Cluster.WebServer.Servers.RestServerInterface.PublicWebInputDefinition
  Market: TradeServer.Cluster.WebServer.Servers.RestServerInterface.PublicWebInputDefinition
  AmountLabel: TradeServer.Cluster.WebServer.Servers.RestServerInterface.PublicWebInputDefinition
  MarginLabel: TradeServer.Cluster.WebServer.Servers.RestServerInterface.PublicWebInputDefinition
  ProfitLabel: TradeServer.Cluster.WebServer.Servers.RestServerInterface.PublicWebInputDefinition
  Fees: TradeServer.Cluster.WebServer.Servers.RestServerInterface.PublicWebInputDefinition
  Profits: TradeServer.Cluster.WebServer.Servers.RestServerInterface.PublicWebInputDefinition
  Orders: TradeServer.Cluster.WebServer.Servers.RestServerInterface.PublicWebInputDefinition
  Positions: TradeServer.Cluster.WebServer.Servers.RestServerInterface.PublicWebInputDefinition
  Performance: TradeServer.Cluster.WebServer.Servers.RestServerInterface.PublicWebInputDefinition

