from dataclasses import dataclass
// <summary>
// This file has been generated by Haasonline Trade Server v4.0.7.102
// Production date: 11/4/2025
// </summary>

@dataclass
class RuntimePerformanceReport:
  SharpeRatio: TradeServer.Cluster.WebServer.Servers.RestServerInterface.PublicWebInputDefinition
  SortinoRatio: TradeServer.Cluster.WebServer.Servers.RestServerInterface.PublicWebInputDefinition
  WinPercentage: TradeServer.Cluster.WebServer.Servers.RestServerInterface.PublicWebInputDefinition
  WinLossPercentage: TradeServer.Cluster.WebServer.Servers.RestServerInterface.PublicWebInputDefinition
  ProfitFactor: TradeServer.Cluster.WebServer.Servers.RestServerInterface.PublicWebInputDefinition
  CPCIndex: TradeServer.Cluster.WebServer.Servers.RestServerInterface.PublicWebInputDefinition
  TailRatio: TradeServer.Cluster.WebServer.Servers.RestServerInterface.PublicWebInputDefinition
  CommonSenseRatio: TradeServer.Cluster.WebServer.Servers.RestServerInterface.PublicWebInputDefinition
  OutlierWinRatio: TradeServer.Cluster.WebServer.Servers.RestServerInterface.PublicWebInputDefinition
  OutlierLossRatio: TradeServer.Cluster.WebServer.Servers.RestServerInterface.PublicWebInputDefinition
  ProfitMarginRatio: TradeServer.Cluster.WebServer.Servers.RestServerInterface.PublicWebInputDefinition
  BiggestWin: TradeServer.Cluster.WebServer.Servers.RestServerInterface.PublicWebInputDefinition
  BiggestLoss: TradeServer.Cluster.WebServer.Servers.RestServerInterface.PublicWebInputDefinition
  HighestPointInProfit: TradeServer.Cluster.WebServer.Servers.RestServerInterface.PublicWebInputDefinition
  LowestPointInProfit: TradeServer.Cluster.WebServer.Servers.RestServerInterface.PublicWebInputDefinition
  TotalMarginUsed: TradeServer.Cluster.WebServer.Servers.RestServerInterface.PublicWebInputDefinition
  AvgMarginUsed: TradeServer.Cluster.WebServer.Servers.RestServerInterface.PublicWebInputDefinition
  AvgProfit: TradeServer.Cluster.WebServer.Servers.RestServerInterface.PublicWebInputDefinition
  IsSet: TradeServer.Cluster.WebServer.Servers.RestServerInterface.PublicWebInputDefinition
  Peak: TradeServer.Cluster.WebServer.Servers.RestServerInterface.PublicWebInputDefinition
  Trough: TradeServer.Cluster.WebServer.Servers.RestServerInterface.PublicWebInputDefinition
  MaxDrawDown: TradeServer.Cluster.WebServer.Servers.RestServerInterface.PublicWebInputDefinition

