from dataclasses import dataclass
// <summary>
// This file has been generated by Haasonline Trade Server v4.0.7.102
// Production date: 11/4/2025
// </summary>

@dataclass
class RuntimePosition:
  PositionGuid: TradeServer.Cluster.WebServer.Servers.RestServerInterface.PublicWebInputDefinition
  PositionId: TradeServer.Cluster.WebServer.Servers.RestServerInterface.PublicWebInputDefinition
  AccountId: TradeServer.Cluster.WebServer.Servers.RestServerInterface.PublicWebInputDefinition
  Market: TradeServer.Cluster.WebServer.Servers.RestServerInterface.PublicWebInputDefinition
  Leverage: TradeServer.Cluster.WebServer.Servers.RestServerInterface.PublicWebInputDefinition
  Direction: TradeServer.Cluster.WebServer.Servers.RestServerInterface.PublicWebInputDefinition
  MarketType: TradeServer.Cluster.WebServer.Servers.RestServerInterface.PublicWebInputDefinition
  ProfitLabel: TradeServer.Cluster.WebServer.Servers.RestServerInterface.PublicWebInputDefinition
  AmountLabel: TradeServer.Cluster.WebServer.Servers.RestServerInterface.PublicWebInputDefinition
  PriceDecimals: TradeServer.Cluster.WebServer.Servers.RestServerInterface.PublicWebInputDefinition
  AmountDecimals: TradeServer.Cluster.WebServer.Servers.RestServerInterface.PublicWebInputDefinition
  OpenTime: TradeServer.Cluster.WebServer.Servers.RestServerInterface.PublicWebInputDefinition
  CloseTime: TradeServer.Cluster.WebServer.Servers.RestServerInterface.PublicWebInputDefinition
  IsClosed: TradeServer.Cluster.WebServer.Servers.RestServerInterface.PublicWebInputDefinition
  AveragePrice: TradeServer.Cluster.WebServer.Servers.RestServerInterface.PublicWebInputDefinition
  Total: TradeServer.Cluster.WebServer.Servers.RestServerInterface.PublicWebInputDefinition
  Available: TradeServer.Cluster.WebServer.Servers.RestServerInterface.PublicWebInputDefinition
  InOrder: TradeServer.Cluster.WebServer.Servers.RestServerInterface.PublicWebInputDefinition
  EnterOrders: TradeServer.Cluster.WebServer.Servers.RestServerInterface.PublicWebInputDefinition
  ExitOrders: TradeServer.Cluster.WebServer.Servers.RestServerInterface.PublicWebInputDefinition
  CurrentPrice: TradeServer.Cluster.WebServer.Servers.RestServerInterface.PublicWebInputDefinition
  FeeCosts: TradeServer.Cluster.WebServer.Servers.RestServerInterface.PublicWebInputDefinition
  RealizedProfits: TradeServer.Cluster.WebServer.Servers.RestServerInterface.PublicWebInputDefinition
  UnrealizedProfits: TradeServer.Cluster.WebServer.Servers.RestServerInterface.PublicWebInputDefinition
  ROI: TradeServer.Cluster.WebServer.Servers.RestServerInterface.PublicWebInputDefinition
  HighestPointInProfit: TradeServer.Cluster.WebServer.Servers.RestServerInterface.PublicWebInputDefinition
  LowestPointInProfit: TradeServer.Cluster.WebServer.Servers.RestServerInterface.PublicWebInputDefinition
  IsSet: TradeServer.Cluster.WebServer.Servers.RestServerInterface.PublicWebInputDefinition
  Peak: TradeServer.Cluster.WebServer.Servers.RestServerInterface.PublicWebInputDefinition
  Trough: TradeServer.Cluster.WebServer.Servers.RestServerInterface.PublicWebInputDefinition
  MaxDrawDown: TradeServer.Cluster.WebServer.Servers.RestServerInterface.PublicWebInputDefinition

