from dataclasses import dataclass
// <summary>
// This file has been generated by Haasonline Trade Server v4.0.7.102
// Production date: 11/4/2025
// </summary>

@dataclass
class RuntimePositionsReport:
  ClosedPositions: TradeServer.Cluster.WebServer.Servers.RestServerInterface.PublicWebInputDefinition
  WinningPositions: TradeServer.Cluster.WebServer.Servers.RestServerInterface.PublicWebInputDefinition
  AverageProfits: TradeServer.Cluster.WebServer.Servers.RestServerInterface.PublicWebInputDefinition
  AveragePositionSize: TradeServer.Cluster.WebServer.Servers.RestServerInterface.PublicWebInputDefinition
  AveragePositionMargin: TradeServer.Cluster.WebServer.Servers.RestServerInterface.PublicWebInputDefinition
  TotalEnterMargin: TradeServer.Cluster.WebServer.Servers.RestServerInterface.PublicWebInputDefinition
  AverageWin: TradeServer.Cluster.WebServer.Servers.RestServerInterface.PublicWebInputDefinition
  BiggestWin: TradeServer.Cluster.WebServer.Servers.RestServerInterface.PublicWebInputDefinition
  TotalWin: TradeServer.Cluster.WebServer.Servers.RestServerInterface.PublicWebInputDefinition
  AverageLoss: TradeServer.Cluster.WebServer.Servers.RestServerInterface.PublicWebInputDefinition
  BiggestLoss: TradeServer.Cluster.WebServer.Servers.RestServerInterface.PublicWebInputDefinition
  TotalLoss: TradeServer.Cluster.WebServer.Servers.RestServerInterface.PublicWebInputDefinition
  ProfitHistory: TradeServer.Cluster.WebServer.Servers.RestServerInterface.PublicWebInputDefinition

