from dataclasses import dataclass
// <summary>
// This file has been generated by Haasonline Trade Server v4.0.7.102
// Production date: 11/4/2025
// </summary>

@dataclass
class UserOrderExecutionRequest:
  RequestId: TradeServer.Cluster.WebServer.Servers.RestServerInterface.PublicWebInputDefinition
  UserId: TradeServer.Cluster.WebServer.Servers.RestServerInterface.PublicWebInputDefinition
  AccountId: TradeServer.Cluster.WebServer.Servers.RestServerInterface.PublicWebInputDefinition
  BotId: TradeServer.Cluster.WebServer.Servers.RestServerInterface.PublicWebInputDefinition
  Market: TradeServer.Cluster.WebServer.Servers.RestServerInterface.PublicWebInputDefinition
  Type: TradeServer.Cluster.WebServer.Servers.RestServerInterface.PublicWebInputDefinition
  Direction: TradeServer.Cluster.WebServer.Servers.RestServerInterface.PublicWebInputDefinition
  OrderPrice: TradeServer.Cluster.WebServer.Servers.RestServerInterface.PublicWebInputDefinition
  TriggerPrice: TradeServer.Cluster.WebServer.Servers.RestServerInterface.PublicWebInputDefinition
  TriggerPriceType: TradeServer.Cluster.WebServer.Servers.RestServerInterface.PublicWebInputDefinition
  Amount: TradeServer.Cluster.WebServer.Servers.RestServerInterface.PublicWebInputDefinition
  PostOnly: TradeServer.Cluster.WebServer.Servers.RestServerInterface.PublicWebInputDefinition
  ReduceOnly: TradeServer.Cluster.WebServer.Servers.RestServerInterface.PublicWebInputDefinition
  HiddenOrder: TradeServer.Cluster.WebServer.Servers.RestServerInterface.PublicWebInputDefinition
  TimeInForce: TradeServer.Cluster.WebServer.Servers.RestServerInterface.PublicWebInputDefinition
  Notes: TradeServer.Cluster.WebServer.Servers.RestServerInterface.PublicWebInputDefinition
  IsMarketOrder: TradeServer.Cluster.WebServer.Servers.RestServerInterface.PublicWebInputDefinition

