from dataclasses import dataclass
// <summary>
// This file has been generated by Haasonline Trade Server v4.0.7.102
// Production date: 11/4/2025
// </summary>

@dataclass
class UserTrade:
  RecordId: TradeServer.Cluster.WebServer.Servers.RestServerInterface.PublicWebInputDefinition
  UserId: TradeServer.Cluster.WebServer.Servers.RestServerInterface.PublicWebInputDefinition
  AccountId: TradeServer.Cluster.WebServer.Servers.RestServerInterface.PublicWebInputDefinition
  TradeId: TradeServer.Cluster.WebServer.Servers.RestServerInterface.PublicWebInputDefinition
  OrderId: TradeServer.Cluster.WebServer.Servers.RestServerInterface.PublicWebInputDefinition
  Unix: TradeServer.Cluster.WebServer.Servers.RestServerInterface.PublicWebInputDefinition
  Type: TradeServer.Cluster.WebServer.Servers.RestServerInterface.PublicWebInputDefinition
  Market: TradeServer.Cluster.WebServer.Servers.RestServerInterface.PublicWebInputDefinition
  Direction: TradeServer.Cluster.WebServer.Servers.RestServerInterface.PublicWebInputDefinition
  TradePrice: TradeServer.Cluster.WebServer.Servers.RestServerInterface.PublicWebInputDefinition
  TradeAmount: TradeServer.Cluster.WebServer.Servers.RestServerInterface.PublicWebInputDefinition
  FeeCosts: TradeServer.Cluster.WebServer.Servers.RestServerInterface.PublicWebInputDefinition
  FeeCurrency: TradeServer.Cluster.WebServer.Servers.RestServerInterface.PublicWebInputDefinition
  Notes: TradeServer.Cluster.WebServer.Servers.RestServerInterface.PublicWebInputDefinition
  SearchTag: TradeServer.Cluster.WebServer.Servers.RestServerInterface.PublicWebInputDefinition
  FeeCostsInBTC: TradeServer.Cluster.WebServer.Servers.RestServerInterface.PublicWebInputDefinition
  FeeCostsInUSD: TradeServer.Cluster.WebServer.Servers.RestServerInterface.PublicWebInputDefinition
  VolumeInBTC: TradeServer.Cluster.WebServer.Servers.RestServerInterface.PublicWebInputDefinition
  VolumeInUSD: TradeServer.Cluster.WebServer.Servers.RestServerInterface.PublicWebInputDefinition

