from dataclasses import dataclass
// <summary>
// This file has been generated by Haasonline Trade Server v4.0.7.102
// Production date: 11/4/2025
// </summary>

@dataclass
class UserLabParameter:
  Key: TradeServer.Cluster.WebServer.Servers.RestServerInterface.PublicWebInputDefinition
  Type: TradeServer.Cluster.WebServer.Servers.RestServerInterface.PublicWebInputDefinition
  Options: TradeServer.Cluster.WebServer.Servers.RestServerInterface.PublicWebInputDefinition
  IsEnabled: TradeServer.Cluster.WebServer.Servers.RestServerInterface.PublicWebInputDefinition
  IsSpecific: TradeServer.Cluster.WebServer.Servers.RestServerInterface.PublicWebInputDefinition

