from dataclasses import dataclass
// <summary>
// This file has been generated by Haasonline Trade Server v4.0.7.102
// Production date: 11/4/2025
// </summary>

@dataclass
class UserBalanceMutation:
  Id: TradeServer.Cluster.WebServer.Servers.RestServerInterface.PublicWebInputDefinition
  UserId: TradeServer.Cluster.WebServer.Servers.RestServerInterface.PublicWebInputDefinition
  AccountId: TradeServer.Cluster.WebServer.Servers.RestServerInterface.PublicWebInputDefinition
  MutationId: TradeServer.Cluster.WebServer.Servers.RestServerInterface.PublicWebInputDefinition
  WalletId: TradeServer.Cluster.WebServer.Servers.RestServerInterface.PublicWebInputDefinition
  Currency: TradeServer.Cluster.WebServer.Servers.RestServerInterface.PublicWebInputDefinition
  Timestamp: TradeServer.Cluster.WebServer.Servers.RestServerInterface.PublicWebInputDefinition
  Type: TradeServer.Cluster.WebServer.Servers.RestServerInterface.PublicWebInputDefinition
  Amount: TradeServer.Cluster.WebServer.Servers.RestServerInterface.PublicWebInputDefinition

