from dataclasses import dataclass
// <summary>
// This file has been generated by Haasonline Trade Server v4.0.7.102
// Production date: 11/4/2025
// </summary>

@dataclass
class UserLabConfig:
  MaxPopulation: TradeServer.Cluster.WebServer.Servers.RestServerInterface.PublicWebInputDefinition
  MaxGenerations: TradeServer.Cluster.WebServer.Servers.RestServerInterface.PublicWebInputDefinition
  MaxElites: TradeServer.Cluster.WebServer.Servers.RestServerInterface.PublicWebInputDefinition
  MixRate: TradeServer.Cluster.WebServer.Servers.RestServerInterface.PublicWebInputDefinition
  AdjustRate: TradeServer.Cluster.WebServer.Servers.RestServerInterface.PublicWebInputDefinition

