from dataclasses import dataclass
// <summary>
// This file has been generated by Haasonline Trade Server v4.0.7.102
// Production date: 11/4/2025
// </summary>

@dataclass
class UserPosition:
  PositionId: TradeServer.Cluster.WebServer.Servers.RestServerInterface.PublicWebInputDefinition
  Direction: TradeServer.Cluster.WebServer.Servers.RestServerInterface.PublicWebInputDefinition
  Market: TradeServer.Cluster.WebServer.Servers.RestServerInterface.PublicWebInputDefinition
  Leverage: TradeServer.Cluster.WebServer.Servers.RestServerInterface.PublicWebInputDefinition
  MarginMode: TradeServer.Cluster.WebServer.Servers.RestServerInterface.PublicWebInputDefinition
  Price: TradeServer.Cluster.WebServer.Servers.RestServerInterface.PublicWebInputDefinition
  Amount: TradeServer.Cluster.WebServer.Servers.RestServerInterface.PublicWebInputDefinition
  Margin: TradeServer.Cluster.WebServer.Servers.RestServerInterface.PublicWebInputDefinition
  ProfitLoss: TradeServer.Cluster.WebServer.Servers.RestServerInterface.PublicWebInputDefinition
  ProfitLossRatio: TradeServer.Cluster.WebServer.Servers.RestServerInterface.PublicWebInputDefinition
  LiquidationPrice: TradeServer.Cluster.WebServer.Servers.RestServerInterface.PublicWebInputDefinition

