from dataclasses import dataclass
// <summary>
// This file has been generated by Haasonline Trade Server v4.0.7.102
// Production date: 11/4/2025
// </summary>

@dataclass
class UserOrder:
  Unix: TradeServer.Cluster.WebServer.Servers.RestServerInterface.PublicWebInputDefinition
  OrderId: TradeServer.Cluster.WebServer.Servers.RestServerInterface.PublicWebInputDefinition
  StopOrderId: TradeServer.Cluster.WebServer.Servers.RestServerInterface.PublicWebInputDefinition
  Market: TradeServer.Cluster.WebServer.Servers.RestServerInterface.PublicWebInputDefinition
  Direction: TradeServer.Cluster.WebServer.Servers.RestServerInterface.PublicWebInputDefinition
  Type: TradeServer.Cluster.WebServer.Servers.RestServerInterface.PublicWebInputDefinition
  OrderPrice: TradeServer.Cluster.WebServer.Servers.RestServerInterface.PublicWebInputDefinition
  TriggerPrice: TradeServer.Cluster.WebServer.Servers.RestServerInterface.PublicWebInputDefinition
  OrderAmount: TradeServer.Cluster.WebServer.Servers.RestServerInterface.PublicWebInputDefinition
  TradeAmount: TradeServer.Cluster.WebServer.Servers.RestServerInterface.PublicWebInputDefinition
  Status: TradeServer.Cluster.WebServer.Servers.RestServerInterface.PublicWebInputDefinition
  BotId: TradeServer.Cluster.WebServer.Servers.RestServerInterface.PublicWebInputDefinition
  Notes: TradeServer.Cluster.WebServer.Servers.RestServerInterface.PublicWebInputDefinition

