from dataclasses import dataclass
// <summary>
// This file has been generated by Haasonline Trade Server v4.0.7.102
// Production date: 11/4/2025
// </summary>

@dataclass
class UserLabsBacktestResult:
  RecordId: TradeServer.Cluster.WebServer.Servers.RestServerInterface.PublicWebInputDefinition
  UserId: TradeServer.Cluster.WebServer.Servers.RestServerInterface.PublicWebInputDefinition
  LabId: TradeServer.Cluster.WebServer.Servers.RestServerInterface.PublicWebInputDefinition
  BacktestId: TradeServer.Cluster.WebServer.Servers.RestServerInterface.PublicWebInputDefinition
  NoGeneration: TradeServer.Cluster.WebServer.Servers.RestServerInterface.PublicWebInputDefinition
  NoPopulation: TradeServer.Cluster.WebServer.Servers.RestServerInterface.PublicWebInputDefinition
  Status: TradeServer.Cluster.WebServer.Servers.RestServerInterface.PublicWebInputDefinition
  Settings: TradeServer.Cluster.WebServer.Servers.RestServerInterface.PublicWebInputDefinition
  Parameters: TradeServer.Cluster.WebServer.Servers.RestServerInterface.PublicWebInputDefinition
  Runtime: TradeServer.Cluster.WebServer.Servers.RestServerInterface.PublicWebInputDefinition
  Chart: TradeServer.Cluster.WebServer.Servers.RestServerInterface.PublicWebInputDefinition
  Logs: TradeServer.Cluster.WebServer.Servers.RestServerInterface.PublicWebInputDefinition
  Summary: TradeServer.Cluster.WebServer.Servers.RestServerInterface.PublicWebInputDefinition
  ServiceId: TradeServer.Cluster.WebServer.Servers.RestServerInterface.PublicWebInputDefinition
  IsElite: TradeServer.Cluster.WebServer.Servers.RestServerInterface.PublicWebInputDefinition

